# Generated by Django 3.1.12 on 2021-06-10 18:57

import autoslug.fields
from django.db import migrations, models

import core.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cache',
            field=core.fields.json_field.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='hidden',
            field=models.BooleanField(
                blank=True, default=False, help_text='Hide this item from search results.'
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=True,
                populate_from='get_slug',
                unique=True,
                verbose_name='slug',
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='collection_set',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.CharField(
                blank=True,
                help_text='The title can be used for the detail page header and title tag, SERP result card header, etc. It should be a noun phrase!',
                max_length=120,
                verbose_name='title',
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
