# Generated by Django 3.1.13 on 2021-08-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0004_remove_collection_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='cache',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='tags',
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(
                blank=True,
                help_text='This value can be used as a page header and/or title attribute.',
                max_length=120,
                verbose_name='title',
            ),
        ),
    ]
