# Generated by Django 3.2.7 on 2021-10-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_collectioninclusion'),
        ('collections', '0005_auto_20210820_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='quotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='collections',
                through='quotes.CollectionInclusion',
                to='quotes.Quote',
            ),
        ),
    ]
