# Generated by Django 3.0.7 on 2020-08-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'ordering': ('url',)},
        ),
    ]
