# Generated by Django 3.0.7 on 2020-08-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_auto_20200825_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticPage',
        ),
    ]
