# Generated by Django 3.0.7 on 2020-09-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0004_staticpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'ordering': ['url']},
        ),
    ]
