# Generated by Django 3.1.3 on 2020-11-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0002_auto_20201127_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulation',
            name='certainty',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'No credible evidence'),
                    (1, 'Some credible evidence'),
                    (2, 'A preponderance of evidence'),
                    (3, 'Beyond reasonable doubt'),
                    (4, 'Beyond any shadow of a doubt'),
                ],
                default=1,
                verbose_name='certainty',
            ),
            preserve_default=False,
        ),
    ]
