# Generated by Django 3.1.8 on 2021-05-02 19:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0002_auto_20210428_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulation',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=True,
                null=True,
                populate_from='get_slug',
                unique=True,
                verbose_name='slug',
            ),
        ),
    ]
