# Generated by Django 3.1.4 on 2020-12-03 20:08

from django.db import migrations

import modularhistory.fields
import modularhistory.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0003_postulation_certainty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulation',
            name='elaboration',
            field=modularhistory.fields.HTMLField(
                blank=True,
                null=True,
                paragraphed=True,
                processor=modularhistory.fields.html_field.process,
                verbose_name='elaboration',
            ),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='summary',
            field=modularhistory.fields.HTMLField(
                paragraphed=False,
                processor=modularhistory.fields.html_field.process,
                unique=True,
                verbose_name='statement',
            ),
        ),
    ]
