# Generated by Django 3.1.9 on 2021-05-08 23:30

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0003_postulation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulation',
            name='related_occurrences',
        ),
        migrations.RemoveField(
            model_name='postulation',
            name='related_topics',
        ),
        migrations.AddField(
            model_name='postulation',
            name='version',
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text='record revision number'
            ),
        ),
    ]
