# Generated by Django 3.1.9 on 2021-05-12 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0003_postulation_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulationsupport',
            old_name='supported_fact',
            new_name='supported_postulation',
        ),
        migrations.AlterField(
            model_name='postulationsupport',
            name='supported_postulation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='supported_postulation_supports',
                to='postulations.postulation',
            ),
        ),
    ]
