# Generated by Django 3.1.9 on 2021-05-12 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0004_auto_20210512_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulation',
            old_name='supportive_facts',
            new_name='supportive_postulations',
        ),
        migrations.RenameField(
            model_name='postulationsupport',
            old_name='supportive_fact',
            new_name='supportive_postulation',
        ),
        migrations.AlterField(
            model_name='postulation',
            name='supportive_postulations',
            field=models.ManyToManyField(
                related_name='supported_postulations',
                through='postulations.PostulationSupport',
                to='postulations.Postulation',
                verbose_name='supportive postulations',
            ),
        ),
        migrations.AlterField(
            model_name='postulationsupport',
            name='supportive_postulation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='supportive_postulation_supports',
                to='postulations.postulation',
            ),
        ),
    ]
