# Generated by Django 3.1.7 on 2021-04-05 02:28

from django.db import migrations

import core.fields
import core.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0005_auto_20201205_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulation',
            name='notes',
            field=core.fields.HTMLField(
                blank=True,
                null=True,
                paragraphed=True,
                processor=core.fields.html_field.process,
            ),
        ),
    ]
