# Generated by Django 3.1.9 on 2021-05-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0005_auto_20210512_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulation',
            name='related_topics',
        ),
    ]
