# Generated by Django 3.1.9 on 2021-05-12 18:48

from django.db import migrations

import core.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0006_remove_postulation_related_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulation',
            name='related_entities',
        ),
        migrations.RemoveField(
            model_name='postulation',
            name='related_occurrences',
        ),
        migrations.AddField(
            model_name='postulation',
            name='computations',
            field=core.fields.json_field.JSONField(blank=True, default=dict, null=True),
        ),
    ]
