# Generated by Django 3.1.9 on 2021-05-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0016_auto_20210517_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulationcitation',
            old_name='postulation',
            new_name='content_object',
        ),
    ]
