# Generated by Django 3.1.9 on 2021-05-18 17:19

import django.db.models.deletion
from django.db import migrations, models

import core.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0021_postulation_cached_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulation',
            name='_cached_citations',
            field=core.fields.json_field.JSONField(default=list, editable=False),
        ),
        migrations.AlterField(
            model_name='postulationcitation',
            name='content_object',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='citations',
                to='postulations.postulation',
            ),
        ),
    ]
