# Generated by Django 3.1.9 on 2021-05-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0022_auto_20210518_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulation',
            old_name='cached_tags',
            new_name='_cached_tags',
        ),
    ]
