# Generated by Django 3.1.9 on 2021-05-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0024_delete_occurrencefactrelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulation',
            old_name='new_tags',
            new_name='tags',
        ),
    ]
