# Generated by Django 3.1.9 on 2021-05-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0027_remove_postulation__cached_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulation',
            name='_cached_citations',
        ),
    ]
