# Generated by Django 3.1.9 on 2021-05-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0028_remove_postulation__cached_citations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulation',
            name='related_entities',
        ),
        migrations.RemoveField(
            model_name='postulation',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='postulation',
            name='supportive_postulations',
        ),
        migrations.RemoveField(
            model_name='postulation',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='postulationcitation',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='postulationcitation',
            name='source',
        ),
        migrations.RemoveField(
            model_name='postulationsupport',
            name='supported_postulation',
        ),
        migrations.RemoveField(
            model_name='postulationsupport',
            name='supportive_postulation',
        ),
        migrations.AlterUniqueTogether(
            name='topicfactrelation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topicfactrelation',
            name='fact',
        ),
        migrations.RemoveField(
            model_name='topicfactrelation',
            name='topic',
        ),
        migrations.DeleteModel(
            name='EntityFactRelation',
        ),
        migrations.DeleteModel(
            name='Postulation',
        ),
        migrations.DeleteModel(
            name='PostulationCitation',
        ),
        migrations.DeleteModel(
            name='PostulationSupport',
        ),
        migrations.DeleteModel(
            name='TopicFactRelation',
        ),
    ]
