# Generated by Django 3.1.4 on 2020-12-03 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='verifier',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='verifications',
                to=settings.AUTH_USER_MODEL,
                verbose_name='verifier',
            ),
        ),
    ]
