# Generated by Django 3.1.13 on 2021-08-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_auto_20201203_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
