# Generated by Django 3.0.1 on 2019-12-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='places.Location')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_places.location_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Location')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
            bases=('places.location',),
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Location')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('places.location',),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Location')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
            bases=('places.location',),
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Location')),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
            bases=('places.location',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Location')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('places.location',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.Location')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('places.location',),
        ),
    ]
