# Generated by Django 3.0.4 on 2020-03-10 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('places.venue', 'venue'), ('places.city', 'city'), ('places.county', 'county'), ('places.state', 'state'), ('places.region', 'region'), ('places.country', 'country'), ('places.continent', 'continent')], db_index=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('preposition', models.CharField(choices=[('in', 'in'), ('at', 'at')], default='in', max_length=2)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='places', to='places.Place')),
            ],
            options={
                'unique_together': {('name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Cities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Countries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='County',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Counties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Venues',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
    ]
