# Generated by Django 3.0.7 on 2020-09-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'verbose_name_plural': 'Continents'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={},
        ),
    ]
