# Generated by Django 3.1.2 on 2020-10-20 14:13

from django.db import migrations
import modularhistory.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='computations',
            field=modularhistory.fields.json_field.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
