# Generated by Django 3.1.2 on 2020-10-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_squashed_0002_auto_20200909_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={},
        ),
    ]
