# Generated by Django 3.0.1 on 2019-12-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
    ]
