# Generated by Django 3.0.1 on 2020-01-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20191229_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
