# Generated by Django 3.0.1 on 2020-01-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='verified',
        ),
    ]
