# Generated by Django 3.0.1 on 2020-01-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='preposition',
            field=models.CharField(choices=[('in', 'in'), ('at', 'at')], default='in', max_length=2),
        ),
    ]
