# Generated by Django 3.0.4 on 2020-03-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_venue_preposition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('name', 'location')},
        ),
    ]
