# Generated by Django 3.0.4 on 2020-03-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20200306_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='type2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
