# Generated by Django 3.0.4 on 2020-03-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_place_type2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type2',
            field=models.CharField(blank=True, choices=[('places.continent', 'places.continent'), ('places.country', 'places.country'), ('places.region', 'places.region'), ('places.state', 'places.state'), ('places.county', 'places.county'), ('places.city', 'places.city'), ('places.venue', 'places.venue')], max_length=40, null=True),
        ),
    ]
