# Generated by Django 3.0.4 on 2020-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200306_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='preposition',
        ),
        migrations.AddField(
            model_name='place',
            name='preposition2',
            field=models.CharField(choices=[('in', 'in'), ('at', 'at')], default='in', max_length=2),
        ),
        migrations.DeleteModel(
            name='LocationTag',
        ),
    ]
