# Generated by Django 3.0.4 on 2020-03-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20200306_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='preposition2',
            new_name='preposition',
        ),
    ]
