# Generated by Django 3.0.4 on 2020-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0062_occurrencechain_description'),
        ('sources', '0168_auto_20200304_1151'),
        ('places', '0010_auto_20200306_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continent',
            name='place_ptr',
        ),
        migrations.RemoveField(
            model_name='country',
            name='place_ptr',
        ),
        migrations.RemoveField(
            model_name='county',
            name='place_ptr',
        ),
        migrations.RemoveField(
            model_name='region',
            name='place_ptr',
        ),
        migrations.RemoveField(
            model_name='state',
            name='place_ptr',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='place_ptr',
        ),
        migrations.RemoveField(
            model_name='place',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('places.venue', 'venue'), ('places.city', 'city'), ('places.county', 'county'), ('places.state', 'state'), ('places.region', 'region'), ('places.country', 'country'), ('places.continent', 'continent')], db_index=True, default='places.city', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Cities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Countries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='County',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Counties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Venues',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
    ]
