# Generated by Django 3.0.4 on 2020-03-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20200306_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='type2',
        ),
    ]
