# Generated by Django 3.1.11 on 2021-05-22 15:58

from django.db import migrations

import apps.dates.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=apps.dates.fields.HistoricDateTimeField(
                blank=True, null=True, verbose_name='date'
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=apps.dates.fields.HistoricDateTimeField(
                blank=True, null=True, verbose_name='date'
            ),
        ),
    ]
