# Generated by Django 3.1.13 on 2021-08-22 01:32

import django.db.models.deletion
from django.db import migrations, models

import apps.topics.models.taggable
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20210820_2138'),
        ('images', '0002_auto_20210820_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='images_image_set',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='images_video_set',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
        migrations.CreateModel(
            name='TopicRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                (
                    'content_object',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='topic_relations',
                        to='images.image',
                        verbose_name='image',
                    ),
                ),
                (
                    'topic',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images_topicrelation_set',
                        to='topics.topic',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='image',
            name='new_tags',
            field=apps.topics.models.taggable.TagsField(
                blank=True,
                related_name='image_set',
                through='images.TopicRelation',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
    ]
