# Generated by Django 3.1.11 on 2021-05-28 22:23

import autoslug.fields
from django.db import migrations, models

import core.fields
import core.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_convert_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                paragraphed=False,
                processed=True,
                processor=core.fields.html_field.process,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                paragraphed=None,
                processed=True,
                processor=core.fields.html_field.process,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                blank=True,
                default='',
                editable=True,
                populate_from='get_slug',
                unique=True,
                verbose_name='slug',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(
                blank=True,
                default='',
                help_text='The title can be used for the detail page header and title tag, SERP result card header, etc. It should be a noun phrase!',
                max_length=120,
                verbose_name='title',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                paragraphed=False,
                processed=True,
                processor=core.fields.html_field.process,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                paragraphed=None,
                processed=True,
                processor=core.fields.html_field.process,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_code',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                blank=True,
                default='',
                editable=True,
                populate_from='get_slug',
                unique=True,
                verbose_name='slug',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
