# Generated by Django 3.1.13 on 2021-08-26 02:21

from django.db import migrations

import core.fields
import core.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20210822_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=core.fields.HTMLField(
                paragraphed=False, processed=True, processor=core.fields.html_field.process
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=core.fields.HTMLField(
                paragraphed=False, processed=True, processor=core.fields.html_field.process
            ),
        ),
    ]
