# Generated by Django 3.1.3 on 2020-12-01 19:54

from django.db import migrations, models

import core.fields.historic_datetime_field


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20201129_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=core.fields.historic_datetime_field.HistoricDateTimeField(
                null=True, verbose_name='date'
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_is_circa',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='whether the date is estimated/imprecise',
                verbose_name='date is circa',
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=core.fields.historic_datetime_field.HistoricDateTimeField(
                null=True, verbose_name='date'
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_is_circa',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='whether the date is estimated/imprecise',
                verbose_name='date is circa',
            ),
        ),
    ]
