# Generated by Django 3.1.11 on 2021-06-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20210531_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_string',
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=100,
                null=True,
                verbose_name='date string',
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_string',
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=100,
                null=True,
                verbose_name='date string',
            ),
        ),
    ]
