# Generated by Django 3.2.7 on 2021-10-21 01:44

import django.db.models.deletion
from django.db import migrations, models

import apps.topics.models.taggable
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0014_auto_20210912_2142'),
        ('images', '0007_auto_20210826_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTopicRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                (
                    'content_object',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='topic_relations',
                        to='images.video',
                        verbose_name='video',
                    ),
                ),
                (
                    'topic',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images_videotopicrelation_set',
                        to='topics.topic',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=apps.topics.models.taggable.TagsField(
                blank=True,
                related_name='video_set',
                through='images.VideoTopicRelation',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
    ]
