# Generated by Django 3.1.4 on 2020-12-02 23:33

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20201201_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '0x0', adapt_rotation=False, allow_fullsize=True, free_crop=True, help_text='Not yet fully implemented.', hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
