# Generated by Django 3.1.4 on 2020-12-03 23:16

import functools

from django.db import migrations, models

import core.fields.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20201203_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='links',
            new_name='urls',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(
                height_field='height',
                null=True,
                upload_to=functools.partial(
                    core.fields.file_field._generate_upload_path,
                    *(),
                    **{'path': 'images/'}
                ),
                verbose_name='image',
                width_field='width',
            ),
        ),
    ]
