# Generated by Django 3.1.4 on 2020-12-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_auto_20201203_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='height'
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(
                choices=[
                    ('image', 'Image'),
                    ('photo', 'Photo'),
                    ('illustration', 'Illustration'),
                    ('painting', 'Painting'),
                    ('portrait', 'Portrait'),
                    ('diagram', 'Diagram'),
                    ('reconstruction', 'Reconstruction'),
                    ('photomontage', 'Photomontage'),
                    ('model', 'Model'),
                ],
                default='image',
                max_length=14,
                verbose_name='image type',
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='width'
            ),
        ),
    ]
