# Generated by Django 3.1.8 on 2021-04-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20201216_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(
                blank=True,
                help_text='The title can be used for the detail page header and title tag, SERP result card header, etc.',
                max_length=120,
                null=True,
                verbose_name='title',
            ),
        ),
    ]
