# Generated by Django 3.1.8 on 2021-05-03 16:26

from django.db import migrations

import core.fields
import core.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=core.fields.HTMLField(
                blank=True,
                null=True,
                paragraphed=False,
                processed=True,
                processor=core.fields.html_field.process,
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=core.fields.HTMLField(
                blank=True,
                null=True,
                paragraphed=False,
                processed=True,
                processor=core.fields.html_field.process,
            ),
        ),
    ]
