# Generated by Django 3.1.8 on 2021-05-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_auto_20210503_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='key',
        ),
        migrations.RemoveField(
            model_name='video',
            name='key',
        ),
    ]
