# Generated by Django 3.1.9 on 2021-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20210428_2009'),
        ('images', '0014_auto_20210505_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='new_tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='image_set',
                to='topics.Topic',
                verbose_name='citations',
            ),
        ),
        migrations.AddField(
            model_name='video',
            name='new_tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='video_set',
                to='topics.Topic',
                verbose_name='citations',
            ),
        ),
    ]
