# Generated by Django 3.1.9 on 2021-05-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20210428_2009'),
        ('images', '0015_auto_20210515_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='new_tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='image_set',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='new_tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='video_set',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
    ]
