# Generated by Django 3.1.9 on 2021-05-18 16:24

from django.db import migrations

import core.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_auto_20210517_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cached_tags',
            field=core.fields.json_field.JSONField(default=list, editable=False),
        ),
        migrations.AddField(
            model_name='video',
            name='cached_tags',
            field=core.fields.json_field.JSONField(default=list, editable=False),
        ),
    ]
