# Generated by Django 3.1.9 on 2021-05-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_auto_20210518_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='new_tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='new_tags',
            new_name='tags',
        ),
    ]
