# Generated by Django 3.1.9 on 2021-05-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_auto_20210519_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='_cached_tags',
        ),
        migrations.RemoveField(
            model_name='video',
            name='_cached_tags',
        ),
    ]
