# When composite actions support `uses` (https://github.com/actions/runner/issues/646),
# this can be converted to a composite action. In the meantime, we are using
# https://github.com/mithro/actions-includes to allow `uses`.

name: 'Setup'
description: 'Set up Python and install dependencies'
inputs:
  os:
    description: 'Operating system'
    required: true
  python-version:
    description: 'Python version'
    required: true
runs:
  # https://github.com/mithro/actions-includes
  using: "includes"
  steps:
    # Set up Python.
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Get full Python version
      id: full-python-version
      shell: bash
      run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info[:3]))")
    # Modify hosts file.
    - name: Add hosts to /etc/hosts
      run: |
        sudo echo "127.0.0.1 postgres" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 redis" | sudo tee -a /etc/hosts
      shell: bash
    # Install and configure Poetry.
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1.1.3
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    # Load cached .venv, if it exists.
    - name: Cache Python virtual environment
      uses: actions/cache@v2
      id: venv-cache
      with:
        path: .venv
        key: venv-${{ inputs.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
    # Make sure Poetry environment is healthy.
    - name: Test poetry environment
      id: venv-test
      if: ${{ steps.venv-cache.outputs.cache-hit == 'true' }}
      run: poetry run invoke debug
    # Install Python dependencies if necessary.
    - name: Install Python dependencies
      if: ${{ steps.venv-cache.outputs.cache-hit != 'true' || failure() }}
      run: |
        sudo apt-get install -y graphviz graphviz-dev
        poetry install
    # Load cached node_modules dir, if it exists.
    - name: Cache node modules
      uses: actions/cache@v2.1.5
      id: node-modules-cache
      with:
        path: frontend/node_modules
        key: node-modules-${{ inputs.os }}-${{ hashFiles('**/package-lock.json') }}
    # Install node modules if necessary.
    - name: Install JavaScript dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: |
        cd frontend
        npm ci
        cd ..
