# Generated by Django 3.1.13 on 2021-08-24 15:28

from django.db import migrations

import apps.entities.models.model_with_related_entities


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_auto_20210824_1528'),
        ('quotes', '0013_auto_20210823_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='related_entities',
            field=apps.entities.models.model_with_related_entities.RelatedEntitiesField(
                blank=True,
                related_name='quote_set',
                through='quotes.EntityRelation',
                to='entities.Entity',
                verbose_name='related entities',
            ),
        ),
    ]
