# See https://pre-commit.com for more information.
# See https://pre-commit.com/hooks.html for more hooks.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: expand-github-workflows
        # https://github.com/mithro/actions-includes
        name: Expand GitHub workflows
        entry: bash -c "echo 'Expand GitHub workflows from workflows-src.'"
        # entry: bash -c 'python -m actions_includes ./.github/workflows-src/workflow-a.yml ./.github/workflows/workflow-a.yml'
        language: system
        types: [python]
        pass_filenames: false
