# See https://pre-commit.com for more information.
# See https://pre-commit.com/hooks.html for more hooks.
repos:
  - repo: local
    hooks:
      - id: autoformat
        name: Autoformat code
        # To enable autoformatting without Poetry installed, we could use Docker:
        # [[ $(docker images -q django:latest 2> /dev/null) == '' ]] && docker image build -t django:latest -f Dockerfile.django; docker run -v $HOME/modularhistory:/modularhistory django:latest invoke qa.autoformat"
        entry: bash -c "poetry --help 2> /dev/null && [[ -d ".venv" ]] && poetry run invoke qa.autoformat"
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: expand-github-workflows
        # https://github.com/mithro/actions-includes
        name: Expand GitHub workflows
        entry: bash -c "docker-compose up github_workflow_preprocessor"
        files: '.github/workflows-src/*.yml'
        language: system
        pass_filenames: false
