version: "3.8"

services:
  dev:
    depends_on:
      - django
      - react
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - .:/modularhistory
  
  django:
    command: sh init.sh
    depends_on:
      - postgres
      - redis
      - redis-commander
      - mongo
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=modularhistory.settings
      - DOCKERIZED=True
      - POSTGRES_HOST=postgres
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8001/ht/ || exit 1"]
      timeout: 7s
      interval: 15s
      retries: 2
      start_period: 10s
    image: "$IMAGE_NAME:$SHA"
    networks:
      default:
        ipv4_address: 172.27.0.6
    ports:
      - "8001:8001"
    restart: "unless-stopped"
    user: www-data
    volumes:
      - ./init.sh:/modularhistory/init.sh
      - ./static:/modularhistory/static
      - ./media:/modularhistory/media
      - ./.backups:/modularhistory/.backups
      - /var/lib/lxd/storage-pools/coresvcs/containers/webserver/rootfs/etc/letsencrypt:/etc/letsencrypt

  mongo:
    env_file: .env
    image: mongo
    ports:
      - "27017:27017"
    restart: "always"
    volumes:
      - data:/data
  
  postgres:
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres
    ports:
      - "5432:5432"
    restart: "always"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - .backups/init.sql:/docker-entrypoint-initdb.d/init.sql

  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    command: npm run dev
    depends_on:
      - django
    links:
      - django:drf
    networks:
      default:
        ipv4_address: 172.27.0.7
    ports:
      - "3000:3000"
    volumes:
      - .:/modularhistory
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: "always"
    volumes:
      - "data:/data"

  redis-commander:
    container_name: redis-commander
    depends_on:
      - redis
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      # - HTTP_USER=www-data
      # - HTTP_PASSWORD=
    ports:
      - "8081:8081"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/24

volumes:
  # `data` is used by both redis and mongodb
  data:
  postgres_data:
