version: "3.8"

services:
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot

  dev:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    volumes:
      - .:/modularhistory
  
  db:
    image: postgres
    env_file: .env
    # environment:
    #   - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    restart: "always"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  modularhistory:
    # build: .
    image: "$IMAGE_NAME:$SHA"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=modularhistory.settings
      - DB_HOST=db
    expose:
      - "8000"
    restart: "on-failure"
    volumes:
      - static:/modularhistory/static
      - media:/modularhistory/media
  
  nginx:
    image: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - certbot
      - modularhistory
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
      - static:/modularhistory/static
      - media:/modularhistory/media
      - nginx_logs:/var/log/nginx/
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: "always"
    volumes:
      - "redis:/data"

volumes: 
  postgres_data:
  nginx_logs:
  redis:
  certbot:
  letsencrypt:
  static:
  media:
