version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=modularhistory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  
  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
  
  nginx:
    image: nginx
    volumes: ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1337:80
    volumes:
      - static:/modularhistory/static
      - media:/modularhistory/media
    depends_on:
      - modularhistory
    networks:
      modularhistory_default:
        ipv4_address: 172.17.0.5
  
  modularhistory:
    build: .
    container_name: modularhistory
    env_file: .env
    environment:
      - DB_HOST=db
    volumes:
      - static:/modularhistory/static
      - media:/modularhistory/media
    expose:
      - "8000"
    depends_on:
      - db
      - cache
  
  dev:
    build: .
    env_file: .env
    environment:
      - DB_HOST=db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/modularhistory
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache

volumes: 
  postgres_data:
  static:
  media:

networks:
  home:
    driver: bridge
    ipam:
     config:
       - subnet: 172.17.0.0/16
         gateway: 10.5.0.1
