
version: "3.8"

x-common-env-vars: &common-env-vars
  DOCKERIZED: "True"
  REDIS_HOST: "redis"
  POSTGRES_HOST: "postgres"

services:
  celery:
    command: bash config/scripts/init/celery.sh
    depends_on:
      - django
      - redis
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
    env_file: .env
    environment:
      <<: *common-env-vars
      IS_CELERY: "True"
    healthcheck:
      test: celery -A core inspect ping -d celery@$$HOSTNAME
      timeout: 30s
      interval: 30s
      retries: 3
      start_period: 20s
    image: "ghcr.io/modularhistory/django:$SHA"
    networks:
      default:
        ipv4_address: 172.27.0.11
    user: www-data
    volumes:
      - ./.backups:/modularhistory/.backups
      - ./.init:/modularhistory/.init
      - ./_static:/modularhistory/_static
      - ./_media:/modularhistory/_media

  celery_beat:
    command: bash config/scripts/init/celery_beat.sh
    depends_on:
      - celery
      - django
      - redis
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
    env_file: .env
    environment:
      <<: *common-env-vars
    image: "ghcr.io/modularhistory/django:$SHA"
    networks:
      default:
        ipv4_address: 172.27.0.12

  django:
    command: bash config/scripts/init/django.sh
    depends_on:
      - postgres
      - redis
      - elasticsearch
    deploy:
      restart_policy:
        condition: on-failure
    env_file: .env
    environment:
      <<: *common-env-vars
      DJANGO_SETTINGS_MODULE: "core.settings"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8000/healthcheck/ || exit 1",
        ]
      timeout: 7s
      interval: 30s
      retries: 2
      start_period: 30s
    image: "ghcr.io/modularhistory/django:$SHA"
    networks:
      default:
        ipv4_address: 172.27.0.8
    ports:
      - "8000:8000"
    user: www-data
    volumes:
      # NOTE: www-data must be granted permission to write to these directories
      # both in the container and on the host machine. Permissions to write in
      # the container are granted in Dockerfile.django. Permissions to write on
      # the host machine have been granted manually; e.g.,
      #     sudo chown -R www-data:www-data .backups && sudo chmod g+w -R .backups
      - ./.backups:/modularhistory/.backups
      - ./.init:/modularhistory/.init
      - ./_static:/modularhistory/_static
      - ./_media:/modularhistory/_media

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html
      - node.name=modularhistory-es
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.ml.enabled=false
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - search_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      default:
        ipv4_address: 172.27.0.15

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.8.1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      default:
        ipv4_address: 172.27.0.16

  mongo:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    env_file: .env
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data

  postgres:
    deploy:
      restart_policy:
        condition: any
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres
    networks:
      default:
        ipv4_address: 172.27.0.6
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.init:/docker-entrypoint-initdb.d

  react:
    command: npm run start
    depends_on:
      - django
    deploy:
      restart_policy:
        condition: on-failure
    env_file: .env
    environment:
      NEXTAUTH_URL: "https://modularhistory.com"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/ || exit 1"]
      timeout: 7s
      interval: 7s
      retries: 3
      start_period: 12s
    image: "ghcr.io/modularhistory/react:$SHA"
    networks:
      default:
        ipv4_address: 172.27.0.9
    ports:
      - "3000:3000"
    volumes:
      - ./_static:/modularhistory/_static

  redis:
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 10s
      retries: 3
    image: redis
    networks:
      default:
        ipv4_address: 172.27.0.7
    ports:
      - "6379:6379"
    volumes:
      - "data:/data"

  redisinsight:
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    env_file: .env
    environment:
      REDIS_HOSTS: "local:redis:6379"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8001/healthcheck/ || exit 1",
        ]
      timeout: 7s
      interval: 15s
      retries: 2
      start_period: 10s
    networks:
      default:
        ipv4_address: 172.27.0.14
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - "redisinsight:/db"

  webserver:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.webserver
      args:
        CERTBOT_EMAIL: jacob@modularhistory.com
        DOMAINS: modularhistory.com,www.modularhistory.com
        DDCLIENT_PROTOCOL: cloudflare
        DDCLIENT_LOGIN: $CLOUDFLARE_EMAIL
        DDCLIENT_PASSWORD: $CLOUDFLARE_PASSWORD
    depends_on:
      - django
      - react
    deploy:
      restart_policy:
        condition: on-failure
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 1m
      timeout: 10s
      retries: 3
    image: "ghcr.io/modularhistory/webserver:$SHA"
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./_media:/modularhistory/_media
      - ./_static:/modularhistory/_static
      - ./config/nginx/prod:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot
    networks:
      default:
        ipv4_address: 172.27.0.5

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/24

volumes:
  # `data` is used by both redis and mongodb
  data:
  letsencrypt:
  certbot:
  postgres_data:
  search_data:
  redisinsight:
