version: "3.8"

services:
  db:
    image: postgres
    env_file: .env
    # environment:
    #   - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  
  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
  
  nginx:
    image: nginx
    ports:
      - 1337:80
    volumes:
      - static:/modularhistory/static
      - media:/modularhistory/media
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro

  
  modularhistory:
    image: "$IMAGE_NAME:$SHA"
    # container_name: modularhistory
    env_file: .env
    environment:
      - DB_HOST=db
    volumes:
      - static:/modularhistory/static
      - media:/modularhistory/media
    expose:
      - "8000"
    depends_on:
      - db
      - cache
      - nginx
  
  dev:
    build: .
    env_file: .env
    environment:
      - DB_HOST=db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/modularhistory
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache

volumes: 
  postgres_data:
  static:
  media:
