version: "3.8"

services:
  webserver:
    depends_on:
      - certbot
      - next

  next:
    depends_on:
      - django
      - celery
      - celery_beat

  django:
    environment:
      DOMAIN: "modularhistory.com"

  cypress:
    environment:
      - CYPRESS_baseUrl=https://www.modularhistory.com/
