version: "3.8"

services:
  nextjs:
    depends_on:
      - django
      - celery
      - celery_beat
    environment:
      NEXTAUTH_URL: "https://modularhistory.orega.org"
      NODE_ENV: "production"
    volumes:
      - ./.env:/.env

  django:
    environment:
      DOMAIN: "modularhistory.orega.org"
