version: "3.8"

services:
  dev:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    volumes:
      - .:/modularhistory
  
  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    restart: "always"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  modularhistory:
    # build: .
    image: "$IMAGE_NAME:$SHA"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=modularhistory.settings
      - DB_HOST=db
    expose:
      - "8000"
    restart: "on-failure"
    volumes:
      - static:/modularhistory/static
      - media:/modularhistory/media
  
  nginx:
    image: staticfloat/nginx-certbot
    depends_on:
      - modularhistory
    ports:
      - "80:80"
      - "443:443"
    environment:
      CERTBOT_EMAIL: modularhistory@gmail.com
    restart: "unless-stopped"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
      - static:/modularhistory/static
      - media:/modularhistory/media
      - logs:/var/log/
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: "always"
    volumes:
      - "redis:/data"

volumes: 
  postgres_data:
  logs:
  redis:
  letsencrypt:
  static:
  media:
