version: "3.8"

services:
  dev:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    volumes:
      - .:/modularhistory
  
  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    restart: "always"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  modularhistory:
    image: "$IMAGE_NAME:$SHA"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=modularhistory.settings
      - DB_HOST=db
    expose:
      - "8000"
    restart: "on-failure"
    volumes:
      - static:/modularhistory/static
      - media:/modularhistory/media

  nginx:
    image: nginx
    depends_on:
      - modularhistory
    networks:
      default:
        ipv4_address: 172.27.0.5
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    volumes:
      - /var/lib/lxd/storage-pools/coresvcs/containers/webserver/rootfs/etc/letsencrypt/live:/etc/letsencrypt/live
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/modularhistory/static
      - media:/modularhistory/media
      - letsencrypt:/etc/letsencrypt
      - logs:/var/log/
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: "always"
    volumes:
      - "redis:/data"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/24

volumes: 
  postgres_data:
  logs:
  redis:
  letsencrypt:
  static:
  media:
