version: "3.8"

services:
  next:
    depends_on:
      - django
      - celery
      - celery_beat

  django:
    environment:
      DOMAIN: "modularhistory.orega.org"

  cypress:
    environment:
      - CYPRESS_baseUrl=https://www.modularhistory.orega.org/
