# Generated by Django 3.1.12 on 2021-06-04 07:21

import django.db.models.deletion
from django.db import migrations, models

import apps.sources.models.sources.speech


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('topics', '0001_initial'),
        ('sources', '0001_initial'),
        ('propositions', '0003_auto_20210604_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='release',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='source',
                to='propositions.publication',
            ),
        ),
        migrations.AddField(
            model_name='source',
            name='tags',
            field=models.ManyToManyField(
                blank=True, related_name='source_set', to='topics.Topic', verbose_name='tags'
            ),
        ),
        migrations.AddField(
            model_name='repository',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='repositories',
                to='places.place',
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='repository',
            field=models.ForeignKey(
                help_text='the library or institution housing the collection',
                on_delete=django.db.models.deletion.CASCADE,
                to='sources.repository',
            ),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.publication',),
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.publication',),
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.publication',),
        ),
        migrations.AddField(
            model_name='webpage',
            name='original_edition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subsequent_editions',
                to='sources.webpage',
            ),
        ),
        migrations.AddField(
            model_name='webpage',
            name='website',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='sources.website',
            ),
        ),
        migrations.AddField(
            model_name='speech',
            name='utterance',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='speech',
                to='propositions.proposition',
                validators=[apps.sources.models.sources.speech.SpeechTypeValidator],
            ),
        ),
        migrations.AddField(
            model_name='section',
            name='work',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='sources.book'
            ),
        ),
        migrations.AddField(
            model_name='piece',
            name='original_edition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subsequent_editions',
                to='sources.piece',
            ),
        ),
        migrations.AddField(
            model_name='entry',
            name='original_edition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subsequent_editions',
                to='sources.entry',
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='document',
                to='sources.collection',
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='original_edition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subsequent_editions',
                to='sources.document',
            ),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='correspondence',
                to='sources.collection',
            ),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='original_edition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subsequent_editions',
                to='sources.correspondence',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'repository')},
        ),
        migrations.AddField(
            model_name='book',
            name='original_edition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subsequent_editions',
                to='sources.book',
            ),
        ),
        migrations.AddField(
            model_name='article',
            name='original_edition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subsequent_editions',
                to='sources.article',
            ),
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='sources.publication'
            ),
        ),
        migrations.AddField(
            model_name='affidavit',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='affidavit',
                to='sources.collection',
            ),
        ),
        migrations.AddField(
            model_name='affidavit',
            name='original_edition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subsequent_editions',
                to='sources.affidavit',
            ),
        ),
    ]
