# Generated by Django 3.1.12 on 2021-06-07 18:27

import django.db.models.deletion
from django.db import migrations, models

import apps.dates.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20210604_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='number'
            ),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='sources.publication',
                verbose_name='publication',
            ),
        ),
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='volume'
            ),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                ('editors', models.CharField(blank=True, max_length=100)),
                (
                    'original_publication_date',
                    apps.dates.fields.HistoricDateTimeField(blank=True, null=True),
                ),
                (
                    'publisher',
                    models.CharField(
                        help_text='the organization that published the report',
                        max_length=100,
                        verbose_name='publisher',
                    ),
                ),
                (
                    'number',
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name='report number'
                    ),
                ),
                (
                    'original_edition',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='subsequent_editions',
                        to='sources.report',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sources.source', models.Model),
        ),
    ]
