# Generated by Django 3.1.12 on 2021-06-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20210607_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='type',
            field=models.CharField(
                choices=[
                    ('correspondence', 'correspondence'),
                    ('email', 'email'),
                    ('letter', 'letter'),
                    ('memorandum', 'memorandum'),
                ],
                default='correspondence',
                max_length=14,
                verbose_name='correspondence type',
            ),
        ),
    ]
