# Generated by Django 3.1.13 on 2021-08-20 21:53

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_auto_20210816_2011'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sourceattribution',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sourcecontainment',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='source',
            name='hidden',
        ),
        migrations.AddField(
            model_name='source',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sourceattribution',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sourcecontainment',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
