# Generated by Django 3.1.13 on 2021-08-22 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_remove_source_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='new_tags',
            new_name='tags',
        ),
    ]
