# Generated by Django 3.2.8 on 2021-10-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_auto_20211021_0144'),
        ('sources', '0017_collectioninclusion'),
    ]

    operations = []
