# Generated by Django 3.1.8 on 2021-04-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS ltree')]
