# Generated by Django 3.1.12 on 2021-06-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0008_collectioninclusion'),
        ('entities', '0006_auto_20210610_1810'),
        ('collections', '0002_auto_20210610_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='entities',
            field=models.ManyToManyField(
                blank=True,
                related_name='collections',
                through='entities.CollectionInclusion',
                to='entities.Entity',
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='propositions',
            field=models.ManyToManyField(
                blank=True,
                related_name='collections',
                through='propositions.CollectionInclusion',
                to='propositions.Proposition',
            ),
        ),
    ]
