# Generated by Django 3.1.8 on 2021-04-18 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=140)),
                ('date', models.DateTimeField()),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'initial_post',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='forums.post'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='parent_thread',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='forums.thread'
            ),
        ),
    ]
