# Generated by Django 3.1.4 on 2020-12-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201203_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='locked',
        ),
    ]
