# Generated by Django 3.1.13 on 2021-07-27 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_socialaccount_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='social_accounts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
