# Generated by Django 3.1.13 on 2021-09-07 04:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'old_path',
                    models.CharField(
                        db_index=True,
                        help_text='Example: /events/search/',
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex='^\\/[-\\w/\\.\\/]+\\/$'
                            )
                        ],
                        verbose_name='redirect from',
                    ),
                ),
                (
                    'new_path',
                    models.CharField(
                        blank=True,
                        help_text='Absolute path or full URL',
                        max_length=200,
                        verbose_name='redirect to',
                    ),
                ),
                (
                    'site',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='sites.site',
                        verbose_name='site',
                    ),
                ),
            ],
            options={
                'verbose_name': 'redirect',
                'verbose_name_plural': 'redirects',
                'ordering': ['old_path'],
                'unique_together': {('site', 'old_path')},
            },
        ),
    ]
