# Generated by Django 3.2.7 on 2021-09-11 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='new_path',
            field=models.CharField(
                blank=True,
                help_text='Absolute path or full URL',
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(regex='^\\/[-\\w/\\.\\/]+$')
                ],
                verbose_name='redirect to',
            ),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=models.CharField(
                db_index=True,
                help_text='Example: /events/search/',
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(regex='^\\/[-\\w/\\.\\/]+$')
                ],
                verbose_name='redirect from',
            ),
        ),
    ]
