#!/bin/bash

# For debugging:
echo "Successfully pulled to $(pwd)."

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"
prompt_to_run_setup_script=false
setup_sha_file=".venv/.setup.sha"

# Check if the setup script hasn't yet been run.
[[ ! -f $setup_sha_file ]] && prompt_to_run_setup_script=true
# Check if the setup script has been modified.
echo "$changed_files" | grep --quiet 'setup.sh' && prompt_to_run_setup_script=true
# Check if last time the setup script was run was with an older version of the script.
[[ "$(head -n1 < $setup_sha_file | cut -d ' ' -f1)" == "$(shasum setup.sh | head -n1 | cut -d ' ' -f1)" ]] && prompt_to_run_setup_script=true

# Update hooks.
if [[ -d config/hooks ]]; then
  for filepath in config/hooks/*; do
    filename=$(basename "$filepath")
    if [[ $filename = "post-merge" ]]; then
      # To avoid having this hook overwrite itself, prompt to rerun the setup script.
      prompt_to_run_setup_script=true
    else
      cmp --silent ".git/hooks/$filename" "$filepath" || {
        cat "$filepath" > ".git/hooks/$filename"
        sudo chmod +x ".git/hooks/$filename"
        echo "Updated $filename hook."
      }
    fi
  done
fi

# Prompt to rerun the setup script if necessary.
if [[ $prompt_to_run_setup_script = true ]]; then
  echo "
    The setup script has been updated. Please run it:
      bash setup.sh
  "
fi
