#!/bin/bash

committed_filepaths="$(git diff --stat --name-only origin/main)"
bold=$(tput bold)
normal=$(tput sgr0)

# If any model files have been modified, check if migrations are required.
echo "$committed_filepaths" | grep --quiet "models" && {
    # https://docs.djangoproject.com/en/3.1/ref/django-admin/#makemigrations
    echo "Checking if migrations are required..."
    docker-compose run django_helper python manage.py makemigrations --check --no-input --dry-run &>/dev/null || {
        echo "
        ${bold}Migrations are required${normal}.
        To see what migrations need to be generated, run:
            docker-compose run django_helper python manage.py makemigrations --dry-run
        Then, to create the migration files, run:
            docker-compose run django_helper python manage.py makemigrations
        Finally, to apply the migrations, run:
            docker-compose run django_helper python manage.py migrate
        "; exit 1
    }
    echo "No migrations are required."
}

# If workflow YAML files (for CI) have been modified, preprocess the files.
echo "$committed_filepaths" | grep --quiet ".github/" && {
    echo "Preprocessing workflow files..."
    docker-compose up github_workflow_preprocessor &>/dev/null || {
        echo "Failed to pre-process workflow files."
        echo "For more output, try running the following:"
        echo "  docker-compose up github_workflow_preprocessor"
    }
    git diff --quiet .github/workflows || {
        git add .github/workflows && git commit -m 'update workflow'
    }
}

echo "Finished pre-push tasks."
