#!/bin/bash

staged_files="$(git diff --name-only --staged)"

# Autoformat Python code.
echo "$staged_files" | grep --quiet ".py" && {
    echo "Autoformatting code..."
    poetry --help &>/dev/null && [[ -d ".venv" ]] && {
        comma_delimited_filepaths="$(echo staged_files | grep '.py' | tr '\n' ',')"
        poetry run invoke qa.autoformat --filepaths "${comma_delimited_filepaths%,}"
    }
}

# Autoformat JS & TS code.
cd frontend && npx lint-staged && cd ..

for file in $staged_files; do
    git add "$file"
done
