#!/bin/bash

# TODO: Only run this check if models have been updated.
# https://modularhistory.atlassian.net/browse/MH-189
if true; then
    # https://docs.djangoproject.com/en/3.1/ref/django-admin/#makemigrations
    echo "Checking if migrations are required..."
    docker-compose run django_helper python manage.py makemigrations --check --no-input --dry-run &>/dev/null || {
        echo "Migrations are required."; exit 1
    }
fi

# TODO: Only preprocess workflow files if they have been modified.
# https://modularhistory.atlassian.net/browse/MH-189
if true; then
    # Preprocess workflow YAML files.
    echo "Preprocessing workflow files..."
    docker-compose up github_workflow_preprocessor &>/dev/null || {
        echo "Failed to pre-process workflow files."
        echo "For more output, try running the following:"
        echo "  docker-compose up github_workflow_preprocessor"
    }
    git diff --quiet .github/workflows || {
        git add .github/workflows && git commit -m 'update workflow'
    }
fi
