# Generated by Django 3.1.2 on 2020-10-21 12:13

from django.db import migrations

import modularhistory.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='computations',
            field=modularhistory.fields.json_field.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
