# Generated by Django 3.0.1 on 2019-12-28 23:41

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='text',
            field=history.fields.HTMLField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=history.fields.HTMLField(blank=True, null=True),
        ),
    ]
