# Generated by Django 3.0.4 on 2020-03-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='key',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
