# Generated by Django 3.0.1 on 2019-12-29 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20191229_0032'),
        ('topics', '0002_auto_20191228_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicQuoteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_topic_relations', to='quotes.Quote')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_quote_relations', to='topics.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='related_quotes',
            field=models.ManyToManyField(blank=True, through='topics.TopicQuoteRelation', to='quotes.Quote'),
        ),
    ]
