# Generated by Django 3.0.4 on 2020-03-25 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20200314_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='related_entities',
        ),
        migrations.DeleteModel(
            name='EntityTopicRelation',
        ),
    ]
