# Generated by Django 3.1.3 on 2020-11-11 21:39

from django.db import migrations

import modularhistory.fields
import modularhistory.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_computations'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='elaboration',
            field=modularhistory.fields.HTMLField(blank=True, null=True, processor=modularhistory.fields.html_field.process),
        ),
    ]
