# Generated by Django 3.0.5 on 2020-04-29 11:29

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('topics', '0002_auto_20200429_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='related_occurrences',
        ),
        migrations.AddField(
            model_name='topic',
            name='related',
            field=gm2m.fields.GM2MField('occurrences.Occurrence', 'quotes.Quote', blank=True, related_name='tags', through='topics.Relation', through_fields=['topic', 'content_object', 'content_type', 'object_id']),
        ),
        migrations.DeleteModel(
            name='OccurrenceTopicRelation',
        ),
    ]
