# Generated by Django 3.0.5 on 2020-04-30 00:31

from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('topics', '0003_auto_20200429_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='related',
            field=gm2m.fields.GM2MField('occurrences.Occurrence', 'quotes.Quote', blank=True, related_name='topic_relations', through='topics.Relation', through_fields=['topic', 'content_object', 'content_type', 'object_id']),
        ),
        migrations.AlterField(
            model_name='topicrelation',
            name='from_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_related_to2', to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='topicrelation',
            name='to_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_related_from2', to='topics.Topic'),
        ),
        migrations.CreateModel(
            name='TopicTopicRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_related_to', to='topics.Topic')),
                ('to_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_related_from', to='topics.Topic')),
            ],
            options={
                'unique_together': {('from_topic', 'to_topic')},
            },
        ),
        migrations.AlterField(
            model_name='topic',
            name='related_topics',
            field=models.ManyToManyField(blank=True, related_name='_topic_related_topics_+', through='topics.TopicTopicRelation', to='topics.Topic'),
        ),
    ]
