# Generated by Django 3.1.3 on 2020-11-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_fact_elaboration'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='fact',
                    name='related_entities',
                ),
                migrations.RemoveField(
                    model_name='fact',
                    name='related_occurrences',
                ),
                migrations.RemoveField(
                    model_name='fact',
                    name='related_topics',
                ),
                migrations.RemoveField(
                    model_name='fact',
                    name='supportive_facts',
                ),
                migrations.AlterUniqueTogether(
                    name='factsupport',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='factsupport',
                    name='supported_fact',
                ),
                migrations.RemoveField(
                    model_name='factsupport',
                    name='supportive_fact',
                ),
                migrations.AlterUniqueTogether(
                    name='occurrencefactrelation',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='occurrencefactrelation',
                    name='fact',
                ),
                migrations.RemoveField(
                    model_name='occurrencefactrelation',
                    name='occurrence',
                ),
                migrations.AlterUniqueTogether(
                    name='topicfactrelation',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='topicfactrelation',
                    name='fact',
                ),
                migrations.RemoveField(
                    model_name='topicfactrelation',
                    name='topic',
                ),
                migrations.DeleteModel(
                    name='EntityFactRelation',
                ),
                migrations.DeleteModel(
                    name='Fact',
                ),
                migrations.DeleteModel(
                    name='FactSupport',
                ),
                migrations.DeleteModel(
                    name='OccurrenceFactRelation',
                ),
                migrations.DeleteModel(
                    name='TopicFactRelation',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='EntityFactRelation',
                    table='facts_entityfactrelation'
                ),
                migrations.AlterModelTable(
                    name='Fact',
                    table='facts_fact'
                ),
                migrations.AlterModelTable(
                    name='FactSupport',
                    table='facts_factsupport'
                ),
                migrations.AlterModelTable(
                    name='OccurrenceFactRelation',
                    table='facts_occurrencefactrelation'
                ),
                migrations.AlterModelTable(
                    name='TopicFactRelation',
                    table='facts_topicfactrelation'
                ),
            ],
        ),
    ]