# Generated by Django 3.0.1 on 2019-12-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topic_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicrelation',
            name='relation_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
