# Generated by Django 3.0.1 on 2019-12-29 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20191229_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcefactderivation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='sourcefactderivation',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='sourcefactderivation',
            name='position',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tags',
        ),
        migrations.AlterField(
            model_name='topicrelation',
            name='from_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_related_to', to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='topicrelation',
            name='to_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_related_from', to='topics.Topic'),
        ),
        migrations.CreateModel(
            name='FactSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_fact_supports', to='topics.Fact')),
                ('supportive_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportive_fact_supports', to='topics.Fact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fact',
            name='supportive_facts',
            field=models.ManyToManyField(related_name='supported_facts', through='topics.FactSupport', to='topics.Fact'),
        ),
    ]
