# Generated by Django 3.0.4 on 2020-03-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_remove_topic_parent_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='parent_topics',
            field=models.ManyToManyField(blank=True, related_name='child_topics', through='topics.TopicParentChildRelation', to='topics.Topic'),
        ),
    ]
