# Generated by Django 3.0.5 on 2020-04-30 00:57

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('topics', '0006_topicrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='related',
            field=gm2m.fields.GM2MField('occurrences.Occurrence', 'quotes.Quote', blank=True, related_name='topic_relations', through='topics.TopicRelation', through_fields=['topic', 'content_object', 'content_type', 'object_id']),
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
