# Generated by Django 3.0.4 on 2020-03-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_topic_parent_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='related_topics',
        ),
    ]
