# Generated by Django 3.0.1 on 2019-12-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20191229_2058'),
        ('topics', '0006_auto_20191229_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='sources',
            field=models.ManyToManyField(related_name='derived_facts', through='sources.SourceFactDerivation', to='sources.Source'),
        ),
        migrations.DeleteModel(
            name='SourceFactDerivation',
        ),
    ]
