# Generated by Django 3.0.5 on 2020-05-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_auto_20200430_0057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicQuoteRelation',
        ),
    ]
