# Generated by Django 3.0.4 on 2020-03-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_auto_20200326_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='related_topics2',
        ),
        migrations.AddField(
            model_name='topic',
            name='related_topics',
            field=models.ManyToManyField(blank=True, related_name='_topic_related_topics_+', through='topics.TopicRelation', to='topics.Topic'),
        ),
    ]
