# Generated by Django 3.0.1 on 2020-01-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_auto_20191229_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicTag',
        ),
    ]
