# Generated by Django 3.0.4 on 2020-03-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_auto_20200326_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='sources',
            new_name='sources2',
        ),
    ]
