# Generated by Django 3.0.1 on 2020-01-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_delete_topictag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='related_topics',
            field=models.ManyToManyField(blank=True, related_name='_topic_related_topics_+', through='topics.TopicRelation', to='topics.Topic'),
        ),
    ]
