# Generated by Django 3.0.4 on 2020-03-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_auto_20200329_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='sources2',
        ),
    ]
