# Generated by Django 3.0.1 on 2020-01-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_auto_20200103_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='related_topics',
        ),
        migrations.RemoveField(
            model_name='topicrelation',
            name='relation_type',
        ),
    ]
