# Generated by Django 3.0.1 on 2020-01-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0011_auto_20200103_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicRelation',
        ),
    ]
