# Generated by Django 3.0.1 on 2020-01-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0012_delete_topicrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='related_topics',
            field=models.ManyToManyField(blank=True, related_name='_topic_related_topics_+', to='topics.Topic'),
        ),
        migrations.CreateModel(
            name='TopicRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_related_to', to='topics.Topic')),
                ('to_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_related_from', to='topics.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
