# Generated by Django 3.0.1 on 2020-01-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_auto_20200103_2215'),
        ('quotes', '0012_auto_20200102_2007'),
        ('topics', '0013_auto_20200103_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='related_entities',
            field=models.ManyToManyField(blank=True, related_name='related_topics', through='entities.EntityTopicRelation', to='entities.Entity'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='related_quotes',
            field=models.ManyToManyField(blank=True, related_name='related_topics', through='topics.TopicQuoteRelation', to='quotes.Quote'),
        ),
    ]
