# Generated by Django 3.0.1 on 2020-01-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0014_auto_20200103_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityfactrelation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fact',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factsupport',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurrencefactrelation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurrencetopicrelation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicfactrelation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicquoterelation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicrelation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
