# Generated by Django 3.0.1 on 2020-01-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0015_auto_20200103_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityfactrelation',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='factsupport',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='occurrencefactrelation',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='occurrencetopicrelation',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='topicfactrelation',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='topicquoterelation',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='topicrelation',
            name='verified',
        ),
    ]
