# Generated by Django 3.0.1 on 2020-01-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0017_topic_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='related_entities',
        ),
    ]
