# Generated by Django 3.0.1 on 2020-01-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_delete_entitytopicrelation'),
        ('topics', '0018_remove_topic_related_entities'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityTopicRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_topic_relations', to='entities.Entity')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_entity_relations', to='topics.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
