# Generated by Django 3.0.1 on 2020-01-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_delete_entitytopicrelation'),
        ('topics', '0019_entitytopicrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='related_entities',
            field=models.ManyToManyField(blank=True, related_name='related_topics', through='topics.EntityTopicRelation', to='entities.Entity'),
        ),
    ]
