# Generated by Django 3.0.1 on 2020-01-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0020_topic_related_entities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['key']},
        ),
    ]
