# Generated by Django 3.0.2 on 2020-02-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0022_auto_20200202_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='key',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
