# Generated by Django 3.0.2 on 2020-02-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0023_auto_20200203_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='key',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
