# Generated by Django 3.0.4 on 2020-03-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0024_auto_20200223_1720'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicrelation',
            unique_together={('from_topic', 'to_topic')},
        ),
    ]
