# Generated by Django 3.1.3 on 2020-11-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0004_fact_verified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factsupport',
            unique_together=set(),
        ),
    ]
