# Generated by Django 3.1.4 on 2020-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='query',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='query'
            ),
        ),
    ]
