# Generated by Django 3.1.12 on 2021-06-04 07:21

import django.db.models.deletion
from django.db import migrations, models

import core.fields
import core.fields.html_field
import core.fields.json_field
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    'citation_phrase',
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, '-------'),
                            ('quoted in', 'quoted in'),
                            ('cited in', 'cited in'),
                            ('partially reproduced in', 'partially reproduced in'),
                        ],
                        default=None,
                        max_length=25,
                    ),
                ),
                ('citation_html', models.TextField(blank=True)),
                ('pages', core.fields.json_field.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'notes',
                    core.fields.HTMLField(
                        blank=True,
                        null=True,
                        paragraphed=True,
                        processed=False,
                        processor=None,
                        verbose_name='note',
                    ),
                ),
                ('handle', models.CharField(max_length=40, unique=True)),
                (
                    'description',
                    core.fields.HTMLField(
                        blank=True,
                        null=True,
                        paragraphed=True,
                        processed=True,
                        processor=core.fields.html_field.process,
                        verbose_name='description',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryElement',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('key', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryInspiration',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'downstream_story',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='inspirations_in',
                        to='stories.story',
                    ),
                ),
                (
                    'upstream_story',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='inspirations_out',
                        to='stories.story',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryElementInclusion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'justification',
                    core.fields.HTMLField(
                        blank=True,
                        paragraphed=True,
                        processed=True,
                        processor=core.fields.html_field.process,
                    ),
                ),
                (
                    'story',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='stories.story'
                    ),
                ),
                (
                    'story_element',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='stories.storyelement'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='story',
            name='elements',
            field=models.ManyToManyField(
                related_name='stories',
                through='stories.StoryElementInclusion',
                to='stories.StoryElement',
                verbose_name='story elements',
            ),
        ),
        migrations.AddField(
            model_name='story',
            name='sources',
            field=models.ManyToManyField(
                blank=True,
                related_name='story_citations',
                through='stories.Citation',
                to='sources.Source',
                verbose_name='sources',
            ),
        ),
        migrations.AddField(
            model_name='story',
            name='upstream_stories',
            field=models.ManyToManyField(
                related_name='downstream_stories',
                through='stories.StoryInspiration',
                to='stories.Story',
                verbose_name='upstream stories',
            ),
        ),
        migrations.AddField(
            model_name='citation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='citations',
                to='stories.story',
                verbose_name='story',
            ),
        ),
        migrations.AddField(
            model_name='citation',
            name='source',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stories_citation_set',
                to='sources.source',
            ),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.UniqueConstraint(
                fields=('source', 'content_object', 'position'),
                name='stories_citation_unique_positions',
            ),
        ),
    ]
