# Generated by Django 3.1.11 on 2021-05-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='version',
        ),
    ]
