# Generated by Django 3.1.12 on 2021-06-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
