# Generated by Django 3.1.8 on 2021-04-21 02:55

from django.db import migrations

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='notes',
            field=core.fields.HTMLField(
                blank=True, null=True, paragraphed=True, processed=False, processor=None
            ),
        ),
    ]
