# Generated by Django 3.1.13 on 2021-08-20 21:38

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210627_2144'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='citation',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='citation',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
