# Generated by Django 3.1.11 on 2021-05-21 13:34

import django.db.models.deletion
from django.db import migrations

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('stories', '0002_remove_story_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycitation',
            name='source',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stories_storycitation_set',
                to='sources.source',
            ),
        ),
    ]
