# Generated by Django 3.1.11 on 2021-05-22 03:02

import django.db.models.deletion
from django.db import migrations, models

import core.fields.json_field
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('stories', '0003_auto_20210521_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    'citation_phrase',
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, '-------'),
                            ('quoted in', 'quoted in'),
                            ('cited in', 'cited in'),
                            ('partially reproduced in', 'partially reproduced in'),
                        ],
                        default=None,
                        max_length=25,
                        null=True,
                    ),
                ),
                ('citation_html', models.TextField(blank=True, null=True)),
                ('pages', core.fields.json_field.JSONField(default=list)),
                (
                    'content_object',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='citations',
                        to='stories.story',
                        verbose_name='story',
                    ),
                ),
                (
                    'source',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='stories_citation_set',
                        to='sources.source',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StoryCitation',
        ),
        migrations.AlterField(
            model_name='story',
            name='sources',
            field=models.ManyToManyField(
                blank=True,
                related_name='story_citations',
                through='stories.Citation',
                to='sources.Source',
                verbose_name='sources',
            ),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.UniqueConstraint(
                fields=('source', 'content_object', 'position'),
                name='stories_citation_unique_positions',
            ),
        ),
    ]
