# Generated by Django 3.1.9 on 2021-05-15 21:38

from django.db import migrations

import core.fields.sorted_m2m_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_source_new_tags'),
        ('stories', '0003_story_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='new_citations',
            field=core.fields.sorted_m2m_field.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name='story_set',
                sort_value_field_name='position',
                to='sources.Source',
                verbose_name='citations',
            ),
        ),
    ]
