# Generated by Django 3.1.13 on 2021-08-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20210820_2138'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='citation',
            managers=[],
        ),
        migrations.AddField(
            model_name='citation',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
