# Generated by Django 3.1.9 on 2021-05-16 05:43

from django.db import migrations

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_new_citations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='new_citations',
        ),
        migrations.AlterField(
            model_name='story',
            name='notes',
            field=core.fields.HTMLField(
                blank=True,
                null=True,
                paragraphed=True,
                processed=False,
                processor=None,
                verbose_name='note',
            ),
        ),
    ]
