# Generated by Django 3.1.11 on 2021-05-28 22:23

from django.db import migrations, models

import core.fields
import core.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_convert_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='citation_html',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citation',
            name='citation_phrase',
            field=models.CharField(
                blank=True,
                choices=[
                    (None, '-------'),
                    ('quoted in', 'quoted in'),
                    ('cited in', 'cited in'),
                    ('partially reproduced in', 'partially reproduced in'),
                ],
                default=None,
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name='storyelementinclusion',
            name='justification',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                paragraphed=True,
                processed=True,
                processor=core.fields.html_field.process,
            ),
            preserve_default=False,
        ),
    ]
