# Generated by Django 3.1.9 on 2021-05-17 17:53

import django.db.models.deletion
from django.db import migrations

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0013_auto_20210517_1459'),
        ('stories', '0009_auto_20210517_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycitation',
            name='source',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stories_storycitations',
                to='sources.source',
            ),
        ),
    ]
