# Generated by Django 3.1.9 on 2021-05-17 21:46

import django.db.models.deletion
from django.db import migrations

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20210517_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycitation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='storycitation_relations',
                to='stories.story',
            ),
        ),
    ]
