# Generated by Django 3.1.9 on 2021-05-19 15:11

import django.db.models.deletion
from django.db import migrations

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_auto_20210518_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycitation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='citations',
                to='stories.story',
                verbose_name='story',
            ),
        ),
    ]
