# Generated by Django 3.1.8 on 2021-04-11 03:20

import django.db.models.deletion
import gm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('entities', '0009_auto_20210204_0619'),
        ('sources', '0023_auto_20210411_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceattribution',
            old_name='polymorphic_source',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='polymorphicsource',
            name='attributees',
            field=models.ManyToManyField(
                blank=True,
                related_name='attributed_sources',
                through='sources.SourceAttribution',
                to='entities.Entity',
            ),
        ),
        migrations.AlterField(
            model_name='polymorphicsource',
            name='file',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sources',
                to='sources.sourcefile',
                verbose_name='file',
            ),
        ),
        migrations.AlterField(
            model_name='polymorphicsource',
            name='related',
            field=gm2m.fields.GM2MField(
                'quotes.Quote',
                'occurrences.Occurrence',
                blank=True,
                related_name='sources',
                through='sources.Citation',
                through_fields=[
                    'source',
                    'content_object',
                    'content_type',
                    'object_id',
                ],
            ),
        ),
    ]
