# Generated by Django 3.1.8 on 2021-04-11 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0024_auto_20210411_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='polymorphic_source',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='citations',
                to='sources.polymorphicsource',
            ),
        ),
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['position', 'source']},
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together={('source', 'content_type', 'object_id', 'position')},
        ),
    ]
