# Generated by Django 3.1.13 on 2021-08-31 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_auto_20210115_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticPage',
        ),
    ]
