# Generated by Django 3.1.8 on 2021-04-28 00:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.trees.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='key',
            field=models.CharField(
                max_length=32,
                null=True,
                unique=True,
                validators=[django.core.validators.RegexValidator(regex='\\w*')],
                verbose_name='key',
            ),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='topics.topic',
                verbose_name='parent',
            ),
        ),
        migrations.AddField(
            model_name='topic',
            name='path',
            field=apps.trees.fields.LtreeField(default=None, editable=False, null=True),
        ),
        migrations.RunSQL(
            """
-- Add an index to be used when the path is accessed directly.
CREATE INDEX topics_topic_path ON topics_topic USING btree(path);

-- Add an index to be used for descendants or ancestors.
CREATE INDEX topics_topic_path_gist ON topics_topic USING GIST(path);

-- Prevent a model instance from having itself as an ancestor (which would result in an infinite recursion).
ALTER TABLE topics_topic ADD CONSTRAINT check_no_recursion
    CHECK(index(path, key::text::ltree) = (nlevel(path) - 1));
"""
        ),
    ]
