# Generated by Django 3.1.4 on 2020-12-05 10:20

import django.db.models.deletion
from django.db import migrations, models

import modularhistory.fields.array_field


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='aliases',
            field=modularhistory.fields.array_field.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
                verbose_name='aliases',
            ),
        ),
        migrations.AlterField(
            model_name='topicrelation',
            name='topic',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='topic_relations',
                to='topics.topic',
                verbose_name='topic',
            ),
        ),
    ]
