# Generated by Django 3.1.8 on 2021-04-28 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20210428_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='key',
            field=models.CharField(
                blank=True,
                max_length=32,
                unique=True,
                validators=[django.core.validators.RegexValidator(regex='\\w*')],
                verbose_name='key',
            ),
        ),
    ]
