# Generated by Django 3.1.11 on 2021-05-28 22:23

import autoslug.fields
from django.db import migrations

import core.fields
import core.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_convert_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                paragraphed=True,
                processed=True,
                processor=core.fields.html_field.process,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                blank=True,
                default='',
                editable=True,
                populate_from='get_slug',
                unique=True,
                verbose_name='slug',
            ),
            preserve_default=False,
        ),
    ]
