# Generated by Django 3.1.4 on 2020-12-17 16:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20201205_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='get_slug', unique=True, verbose_name='slug'),
        ),
    ]
