# Generated by Django 3.1.13 on 2021-08-24 19:58

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    TopicTopicRelation = apps.get_model('topics', 'TopicTopicRelation')
    TopicRelation = apps.get_model('topics', 'TopicRelation')
    for relation in TopicTopicRelation.objects.all():
        TopicRelation.objects.get_or_create(
            topic=relation.from_topic,
            related_topic=relation.to_topic,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20210820_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                (
                    'related_topic',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='topics.topic',
                        verbose_name='related topic',
                    ),
                ),
                (
                    'topic',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='topic_relations',
                        to='topics.topic',
                        verbose_name='topic',
                    ),
                ),
            ],
            options={
                'unique_together': {('topic', 'related_topic')},
            },
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
