# Generated by Django 3.1.8 on 2021-04-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='key',
            new_name='name',
        ),
    ]
