# Generated by Django 3.1.9 on 2021-05-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_remove_topic_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='computations',
            new_name='cache',
        ),
    ]
