# Generated by Django 3.1.8 on 2021-04-27 07:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20210427_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='key',
            field=models.CharField(
                max_length=32,
                null=True,
                unique=True,
                validators=[django.core.validators.RegexValidator(regex='\\w*')],
                verbose_name='key',
            ),
        ),
        migrations.AlterField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='topics.topic',
                verbose_name='parent',
            ),
        ),
    ]
