# Generated by Django 3.1.13 on 2021-08-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_topic_new_related_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicparentchildrelation',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='topicparentchildrelation',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
