# Generated by Django 3.1.9 on 2021-05-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20210519_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicRelation',
        ),
    ]
