# Generated by Django 3.1.13 on 2021-08-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20210824_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='related_topics',
        ),
    ]
