# Generated by Django 3.1.13 on 2021-08-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_delete_topictopicrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='parent_topics',
        ),
    ]
