# Generated by Django 3.2.7 on 2021-09-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0013_auto_20210912_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicedge',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='topicedge',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
