# Generated by Django 3.1.13 on 2021-08-03 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.moderation.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratedObject',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'object_pk',
                    models.PositiveIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'state',
                    models.SmallIntegerField(
                        choices=[('ready', 'Ready for moderation'), ('draft', 'Draft')],
                        default=1,
                        editable=False,
                    ),
                ),
                (
                    'status',
                    models.SmallIntegerField(
                        choices=[
                            ('rejected', 'Rejected'),
                            ('approved', 'Approved'),
                            ('pending', 'Pending'),
                        ],
                        default=2,
                        editable=False,
                    ),
                ),
                ('on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                (
                    'changed_object',
                    apps.moderation.fields.SerializedObjectField(editable=False),
                ),
                (
                    'by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='moderated_objects',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'changed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='changed_by_set',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'content_type',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Moderated Object',
                'verbose_name_plural': 'Moderated Objects',
                'ordering': ['status', 'created'],
            },
        ),
    ]
