# Generated by Django 3.1.13 on 2021-08-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_auto_20210825_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='requires_rebase',
            field=models.BooleanField(
                default=False, editable=False, verbose_name='requires rebase'
            ),
        ),
    ]
