# Generated by Django 3.2.8 on 2021-10-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_auto_20210831_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='date',
            field=models.DateTimeField(
                auto_now_add=True, help_text='The date of the moderation'
            ),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='reason',
            field=models.TextField(
                blank=True,
                help_text='The reason for the moderation verdict (approval or rejection)',
                null=True,
            ),
        ),
    ]
