"""
Django settings for history project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w@w6*rn!6y-)rkq$e)!di21(xy(txp%&75d)j32r!-82pb3^ne'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'account.apps.AccountConfig',
    'home.apps.HomeConfig',
    'occurrences.apps.OccurrencesConfig',
    'people.apps.PeopleConfig',
    'places.apps.PlacesConfig',
    'quotes.apps.QuotesConfig',
    'sources.apps.SourcesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_mako_plus',
    'imagekit',
    'polymorphic',
    'tinymce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_mako_plus.RequestInitMiddleware',
]

ROOT_URLCONF = 'history.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    {
        'NAME': 'django_mako_plus',
        'BACKEND': 'django_mako_plus.MakoTemplates',
        'OPTIONS': {
            'CONTENT_PROVIDERS': [
                # provides JS context; this should be listed FIRST
                { 'provider': 'django_mako_plus.JsContextProvider' },

                # Sass precompiler provider
                {
                'provider': 'django_mako_plus.CompileScssProvider',
                # 'group': 'styles',
                # 'enabled': True,
                # 'sourcepath': None,
                # 'targetpath': None,
                # 'command': []
                },

                # generates links for app/styles/template.css
                {
                'provider': 'django_mako_plus.CssLinkProvider',
                # 'group': 'styles',
                },

                # generates links for app/scripts/template.js
                { 'provider': 'django_mako_plus.JsLinkProvider' },
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'loggers': {
        'django_mako_plus': {
            'handlers': ['console_handler'],
            'level': DEBUG and 'DEBUG' or 'WARNING',
            'propagate': False,
        },
        'django': {
            'handlers': ['console_handler'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'handlers': {
        'console_handler': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
}
#
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'dmp_simple': {
#             'format': '%(levelname)s::DMP %(message)s'
#         },
#     },
#     'handlers': {
#         'dmp_console':{
#             'level':'DEBUG',
#             'class':'logging.StreamHandler',
#             'formatter': 'dmp_simple'
#         },
#     },
#     'loggers': {
#         'django_mako_plus': {
#             'handlers': ['dmp_console'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#     },
# }

WSGI_APPLICATION = 'history.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'history',
        'USER': 'jacob',
        'PASSWORD': 'bocaj092',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

AUTH_USER_MODEL = 'account.User'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    # SECURITY WARNING: this next line must be commented out at deployment
    BASE_DIR,
)
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
