# Generated by Django 3.0.1 on 2019-12-22 11:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YBP', models.BigIntegerField(unique=True, verbose_name='Years Before Present')),
                ('BCE', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Before Common Era')),
                ('CE', models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Common Era')),
            ],
        ),
    ]
