# Generated by Django 3.0.4 on 2020-03-13 00:04

from django.db import migrations, models
import django.db.models.deletion
import history.fields.historic_datetime_field
import history.fields.html_field
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_is_circa', models.BooleanField(blank=True, default=False)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('hidden', models.BooleanField(blank=True, default=False, help_text="Don't let this item appear in search results.")),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', history.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True)),
                ('end_date', history.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True)),
                ('summary', history.fields.html_field.HTMLField(blank=True, null=True)),
                ('description', history.fields.html_field.HTMLField(blank=True, null=True)),
                ('postscript', history.fields.html_field.HTMLField(blank=True, help_text='Content to be displayed below all related data', null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OccurrenceChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', history.fields.html_field.HTMLField(max_length=200, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccurrenceChainInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceEntityInvolvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.PositiveSmallIntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary'), (4, 'Quaternary'), (5, 'Quinary'), (6, 'Senary'), (7, 'Septenary')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Set to 0 if the image is positioned manually.')),
            ],
            options={
                'ordering': ['position', 'image'],
            },
        ),
        migrations.CreateModel(
            name='OccurrenceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary'), (4, 'Quaternary'), (5, 'Quinary'), (6, 'Senary'), (7, 'Septenary')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceQuoteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=1)),
            ],
            options={
                'ordering': ['position', 'quote'],
            },
        ),
        migrations.CreateModel(
            name='OccurrenceSourceReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='reference position')),
                ('page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='occurrences.Occurrence')),
            ],
        ),
    ]
