# Generated by Django 3.0.1 on 2019-12-28 21:12

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', tinymce.models.HTMLField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year__years_before_present', '-datetime'],
            },
        ),
        migrations.CreateModel(
            name='OccurrenceEntityInvolvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary'), (4, 'Quaternary'), (5, 'Quinary'), (6, 'Senary'), (7, 'Septenary')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccurrenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccurrenceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary'), (4, 'Quaternary'), (5, 'Quinary'), (6, 'Senary'), (7, 'Septenary')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccurrenceQuoteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('common_era', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, unique=True)),
                ('years_before_present', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, unique=True)),
                ('approximate', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-years_before_present'],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='occurrences.Occurrence')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('occurrences.occurrence',),
        ),
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='occurrences.Occurrence')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('occurrences.occurrence',),
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='occurrences.Occurrence')),
                ('cause', models.CharField(choices=[('Murdered', 'Murdered or assassinated'), ('Illness', 'Illness'), ('Accident', 'Accident')], max_length=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('occurrences.occurrence',),
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='occurrences.Occurrence')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('occurrences.occurrence',),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='occurrences.Occurrence')),
                ('date_is_precise', models.BooleanField(default=True)),
                ('time_is_precise', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('occurrences.occurrence',),
        ),
        migrations.CreateModel(
            name='Founding',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='occurrences.Occurrence')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('occurrences.occurrence',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='occurrences.Occurrence')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('occurrences.occurrence',),
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='occurrences.Occurrence')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('occurrences.occurrence',),
        ),
        migrations.CreateModel(
            name='OccurrenceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrences.Occurrence')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences_occurrencetag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccurrenceSourceReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='reference position')),
                ('page_number', models.CharField(blank=True, max_length=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='occurrences.Occurrence')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
