# Generated by Django 3.1.2 on 2020-10-16 01:35

from django.db import migrations, models
import django.db.models.deletion
import modularhistory.fields
import modularhistory.fields.historic_datetime_field
import modularhistory.fields.json_field
import uuid


class Migration(migrations.Migration):

    replaces = [('occurrences', '0001_initial'), ('occurrences', '0002_auto_20200427_2153'), ('occurrences', '0003_remove_occurrence_related_quotes'), ('occurrences', '0004_occurrence_db_citation_html'), ('occurrences', '0005_auto_20201013_0048'), ('occurrences', '0006_auto_20201013_0135'), ('occurrences', '0007_auto_20201013_0656')]

    initial = True

    dependencies = [
        ('entities', '0007_auto_20200407_0910'),
        ('places', '0001_initial'),
        ('quotes', '0001_initial'),
        ('images', '0005_auto_20200319_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_is_circa', models.BooleanField(blank=True, default=False)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('hidden', models.BooleanField(blank=True, default=False, help_text="Don't let this item appear in search results.")),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', modularhistory.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True)),
                ('end_date', modularhistory.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True)),
                ('summary', modularhistory.fields.HTMLField(blank=True, null=True, verbose_name='Summary')),
                ('description', modularhistory.fields.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('postscript', modularhistory.fields.HTMLField(blank=True, help_text='Content to be displayed below all related data', null=True, verbose_name='Postscript')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OccurrenceChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', modularhistory.fields.HTMLField(max_length=200, null=True, unique=True)),
                ('parent_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_chains', to='occurrences.occurrencechain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccurrenceQuoteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_quote_relations', to='occurrences.occurrence')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_occurrence_relations', to='quotes.quote')),
            ],
            options={
                'ordering': ['position', 'quote'],
                'unique_together': {('occurrence', 'quote')},
            },
        ),
        migrations.CreateModel(
            name='OccurrenceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary'), (4, 'Quaternary'), (5, 'Quinary'), (6, 'Senary'), (7, 'Septenary')], default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_occurrences', to='places.place')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrences.occurrence')),
            ],
            options={
                'unique_together': {('occurrence', 'location')},
            },
        ),
        migrations.CreateModel(
            name='OccurrenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='Set to 0 if the image is positioned manually.', null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.image')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_images', to='occurrences.occurrence')),
            ],
            options={
                'ordering': ['position', 'image'],
                'unique_together': {('occurrence', 'image')},
            },
        ),
        migrations.CreateModel(
            name='OccurrenceEntityInvolvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.PositiveSmallIntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary'), (4, 'Quaternary'), (5, 'Quinary'), (6, 'Senary'), (7, 'Septenary')], default=1)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_involvements', to='entities.entity')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrences.occurrence')),
            ],
            options={
                'unique_together': {('occurrence', 'entity')},
            },
        ),
        migrations.CreateModel(
            name='OccurrenceChainInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_inclusions', to='occurrences.occurrencechain')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_inclusions', to='occurrences.occurrence')),
            ],
            options={
                'unique_together': {('chain', 'occurrence')},
            },
        ),
        migrations.AddField(
            model_name='occurrence',
            name='chains',
            field=models.ManyToManyField(related_name='occurrences', through='occurrences.OccurrenceChainInclusion', to='occurrences.OccurrenceChain'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='occurrences', through='occurrences.OccurrenceImage', to='images.Image'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='involved_entities',
            field=models.ManyToManyField(blank=True, related_name='involved_occurrences', through='occurrences.OccurrenceEntityInvolvement', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='occurrences', through='occurrences.OccurrenceLocation', to='places.Place'),
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together={('summary', 'date')},
        ),
        migrations.AddField(
            model_name='occurrence',
            name='computations',
            field=modularhistory.fields.json_field.JSONField(blank=True, default=dict, null=True),
        ),
    ]
