# Generated by Django 3.0.1 on 2019-12-28 21:12

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('occurrences', '0001_initial'),
        ('entities', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('places', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('quotes', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencesourcereference',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_from_occurrences', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='occurrencequoterelation',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_quote_relations', to='occurrences.Occurrence'),
        ),
        migrations.AddField(
            model_name='occurrencequoterelation',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_occurrence_relations', to='quotes.Quote'),
        ),
        migrations.AddField(
            model_name='occurrencelocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_occurrences', to='places.Place'),
        ),
        migrations.AddField(
            model_name='occurrencelocation',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrences.Occurrence'),
        ),
        migrations.AddField(
            model_name='occurrenceimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Image'),
        ),
        migrations.AddField(
            model_name='occurrenceimage',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='occurrences.Occurrence'),
        ),
        migrations.AddField(
            model_name='occurrenceentityinvolvement',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_involvements', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='occurrenceentityinvolvement',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrences.Occurrence'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='occurrences', through='occurrences.OccurrenceImage', to='images.Image'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='involved_entities',
            field=models.ManyToManyField(blank=True, related_name='involved_occurrences', through='occurrences.OccurrenceEntityInvolvement', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='occurrences', through='occurrences.OccurrenceLocation', to='places.Place'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_occurrences.occurrence_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='related_quotes',
            field=models.ManyToManyField(blank=True, related_name='related_occurrences', through='occurrences.OccurrenceQuoteRelation', to='quotes.Quote'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='sources',
            field=models.ManyToManyField(blank=True, through='occurrences.OccurrenceSourceReference', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='occurrences.OccurrenceTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='occurrences.Year'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='occurrences.Duration'),
        ),
        migrations.AddField(
            model_name='duration',
            name='end_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences_ended', to='occurrences.Year'),
        ),
        migrations.AddField(
            model_name='birth',
            name='entity',
            field=models.OneToOneField(blank=True, db_column='birth', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='battle',
            name='related_war',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='battles', to='occurrences.War'),
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together={('summary', 'datetime')},
        ),
    ]
