# Generated by Django 3.0.1 on 2019-12-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='YBP',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Years Before Present'),
        ),
    ]
