# Generated by Django 3.0.5 on 2020-04-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0005_auto_20200319_1119'),
        ('quotes', '0001_initial'),
        ('places', '0001_initial'),
        ('entities', '0007_auto_20200407_0910'),
        ('occurrences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencequoterelation',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_occurrence_relations', to='quotes.Quote'),
        ),
        migrations.AddField(
            model_name='occurrencelocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_occurrences', to='places.Place'),
        ),
        migrations.AddField(
            model_name='occurrencelocation',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrences.Occurrence'),
        ),
        migrations.AddField(
            model_name='occurrenceimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Image'),
        ),
        migrations.AddField(
            model_name='occurrenceimage',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_images', to='occurrences.Occurrence'),
        ),
        migrations.AddField(
            model_name='occurrenceentityinvolvement',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_involvements', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='occurrenceentityinvolvement',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrences.Occurrence'),
        ),
        migrations.AddField(
            model_name='occurrencechaininclusion',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_inclusions', to='occurrences.OccurrenceChain'),
        ),
        migrations.AddField(
            model_name='occurrencechaininclusion',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_inclusions', to='occurrences.Occurrence'),
        ),
        migrations.AddField(
            model_name='occurrencechain',
            name='parent_chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_chains', to='occurrences.OccurrenceChain'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='chains',
            field=models.ManyToManyField(related_name='occurrences', through='occurrences.OccurrenceChainInclusion', to='occurrences.OccurrenceChain'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='occurrences', through='occurrences.OccurrenceImage', to='images.Image'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='involved_entities',
            field=models.ManyToManyField(blank=True, related_name='involved_occurrences', through='occurrences.OccurrenceEntityInvolvement', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='occurrences', through='occurrences.OccurrenceLocation', to='places.Place'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='related_quotes',
            field=models.ManyToManyField(blank=True, related_name='related_occurrences', through='occurrences.OccurrenceQuoteRelation', to='quotes.Quote'),
        ),
        migrations.AlterUniqueTogether(
            name='occurrencequoterelation',
            unique_together={('occurrence', 'quote')},
        ),
        migrations.AlterUniqueTogether(
            name='occurrencelocation',
            unique_together={('occurrence', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='occurrenceimage',
            unique_together={('occurrence', 'image')},
        ),
        migrations.AlterUniqueTogether(
            name='occurrenceentityinvolvement',
            unique_together={('occurrence', 'entity')},
        ),
        migrations.AlterUniqueTogether(
            name='occurrencechaininclusion',
            unique_together={('chain', 'occurrence')},
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together={('summary', 'date')},
        ),
    ]
