# Generated by Django 3.0.1 on 2019-12-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_auto_20191228_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='approximate',
        ),
        migrations.AddField(
            model_name='year',
            name='string',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
