# Generated by Django 3.1.2 on 2020-10-30 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20201020_0704'),
        ('occurrences', '0002_auto_20201016_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrence_images', to='images.image'),
        ),
    ]
