# Generated by Django 3.0.5 on 2020-04-29 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_auto_20200427_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='related_quotes',
        ),
    ]
