# Generated by Django 3.1.2 on 2020-10-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0003_auto_20201030_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrenceimage',
            name='is_positioned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
