# Generated by Django 3.0.10 on 2020-10-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0003_remove_occurrence_related_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='db_citation_html',
            field=models.CharField(blank=True, max_length=1000, verbose_name='database string'),
        ),
    ]
