# Generated by Django 3.0.1 on 2019-12-28 23:41

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0004_auto_20191228_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='description',
            field=history.fields.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='summary',
            field=history.fields.HTMLField(blank=True, null=True),
        ),
    ]
