# Generated by Django 3.0.4 on 2020-03-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0004_occurrencesourcereference_citation_phrase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrencesourcereference',
            options={'verbose_name': 'citation'},
        ),
    ]
