# Generated by Django 3.1.2 on 2020-10-31 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20201020_0704'),
        ('occurrences', '0004_occurrenceimage_is_positioned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrence_relations', to='images.image'),
        ),
        migrations.AlterField(
            model_name='occurrenceimage',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_relations', to='occurrences.occurrence'),
        ),
    ]
