# Generated by Django 3.0.10 on 2020-10-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0005_auto_20201013_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='db_citation_html',
            field=models.CharField(blank=True, max_length=3000, verbose_name='database string'),
        ),
    ]
