# Generated by Django 3.0.1 on 2019-12-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0005_auto_20191228_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='birth',
            options={},
        ),
        migrations.AlterModelOptions(
            name='death',
            options={},
        ),
        migrations.AlterModelOptions(
            name='duration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='founding',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='war',
            options={},
        ),
    ]
