# Generated by Django 3.1.3 on 2020-11-17 21:00

from django.db import migrations

import modularhistory.fields
import modularhistory.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0005_auto_20201031_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencechain',
            name='description',
            field=modularhistory.fields.HTMLField(null=True, processor=modularhistory.fields.html_field.process, unique=True),
        ),
    ]
