# Generated by Django 3.0.10 on 2020-10-13 06:56

from django.db import migrations
import modularhistory.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0006_auto_20201013_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='db_citation_html',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='computations',
            field=modularhistory.fields.json_field.JSONField(blank=True, default=dict, null=True),
        ),
    ]
