# Generated by Django 3.0.1 on 2019-12-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0007_occurrencesourcereference_end_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencesourcereference',
            name='page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
