# Generated by Django 3.0.4 on 2020-03-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0007_auto_20200329_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='sources2',
        ),
        migrations.DeleteModel(
            name='OccurrenceSourceReference',
        ),
    ]
