# Generated by Django 3.0.5 on 2020-04-19 09:03

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0008_auto_20200329_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='description',
            field=history.fields.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='postscript',
            field=history.fields.HTMLField(blank=True, help_text='Content to be displayed below all related data', null=True, verbose_name='Postscript'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='summary',
            field=history.fields.HTMLField(blank=True, null=True, verbose_name='Summary'),
        ),
    ]
