# Generated by Django 3.0.1 on 2020-01-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0008_auto_20191231_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencesourcereference',
            name='source_type',
            field=models.CharField(blank=True, choices=[('P', 'Primary'), ('S', 'Secondary')], max_length=20, null=True),
        ),
    ]
