# Generated by Django 3.0.1 on 2020-01-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0009_occurrencesourcereference_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencesourcereference',
            name='source_type',
            field=models.CharField(blank=True, choices=[('P', 'Primary'), ('S', 'Secondary')], max_length=3, null=True),
        ),
    ]
