# Generated by Django 3.0.5 on 2020-04-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0009_auto_20200419_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceimage',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Set to 0 if the image is positioned manually.', null=True),
        ),
        migrations.AlterField(
            model_name='occurrencequoterelation',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
