# Generated by Django 3.0.1 on 2020-01-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20200102_1718'),
        ('topics', '0007_auto_20191229_2058'),
        ('occurrences', '0010_auto_20200101_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founding',
            name='occurrence_ptr',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='occurrence_ptr',
        ),
        migrations.AddField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('publication', 'Publication'), ('birth', 'Birth'), ('death', 'Death'), ('founding', 'Founding'), ('founding', 'Founding'), ('battle', 'Battle'), ('other', 'Other')], default='other', max_length=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Birth',
        ),
        migrations.DeleteModel(
            name='Founding',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
