# Generated by Django 3.0.5 on 2020-04-26 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20200319_1119'),
        ('occurrences', '0010_auto_20200419_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Image'),
        ),
    ]
