# Generated by Django 3.0.1 on 2020-01-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_auto_20191229_2058'),
        ('occurrences', '0011_auto_20200102_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Death',
        ),
    ]
