# Generated by Django 3.0.1 on 2020-01-02 22:23

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0012_delete_death'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['-year__years_before_present', '-date']},
        ),
        migrations.AddField(
            model_name='occurrence',
            name='date',
            field=history.fields.HistoricDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='datetime',
            field=history.fields.HistoricDateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together={('summary', 'date')},
        ),
    ]
