# Generated by Django 3.0.1 on 2020-01-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_delete_topictag'),
        ('occurrences', '0014_remove_occurrence_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='related_topics',
            field=models.ManyToManyField(blank=True, related_name='related_occurrences', to='topics.Topic'),
        ),
    ]
