# Generated by Django 3.0.1 on 2020-01-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0015_occurrence_related_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('publication', 'Publication'), ('birth', 'Birth'), ('death', 'Death'), ('founding', 'Founding'), ('battle', 'Battle'), ('other', 'Other')], max_length=12),
        ),
    ]
