# Generated by Django 3.0.1 on 2020-01-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0016_auto_20200103_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='related_topics',
        ),
    ]
