# Generated by Django 3.0.1 on 2020-01-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0017_remove_occurrence_related_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='tags',
        ),
        migrations.DeleteModel(
            name='OccurrenceTag',
        ),
    ]
