# Generated by Django 3.0.1 on 2020-01-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0018_auto_20200103_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('publication', 'Publication'), ('birth', 'Birth'), ('death', 'Death'), ('founding', 'Founding'), ('battle', 'Battle'), ('other', 'Other')], default='other', max_length=12),
        ),
    ]
