# Generated by Django 3.0.1 on 2020-01-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0019_auto_20200103_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurrenceentityinvolvement',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurrenceimage',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurrencelocation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurrencequoterelation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurrencesourcereference',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='year',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
