# Generated by Django 3.0.1 on 2020-01-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0021_auto_20200105_2237'),
        ('occurrences', '0022_auto_20200104_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='war',
            name='occurrence_ptr',
        ),
        migrations.DeleteModel(
            name='Battle',
        ),
        migrations.DeleteModel(
            name='War',
        ),
    ]
