# Generated by Django 3.0.1 on 2020-01-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0024_auto_20200107_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='date_is_precise',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='time_is_precise',
        ),
    ]
