# Generated by Django 3.0.1 on 2020-01-24 15:09

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0025_auto_20200124_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='datetime',
            field=history.fields.HistoricDateTimeField(blank=True, null=True),
        ),
    ]
