# Generated by Django 3.0.1 on 2020-01-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0026_occurrence_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['-year__years_before_present', '-datetime']},
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together={('summary', 'datetime')},
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='date',
        ),
    ]
