# Generated by Django 3.0.1 on 2020-01-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0027_auto_20200124_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['-year__years_before_present', '-date']},
        ),
        migrations.RenameField(
            model_name='occurrence',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together={('summary', 'date')},
        ),
    ]
