# Generated by Django 3.0.2 on 2020-01-31 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0029_remove_occurrencesourcereference_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_chains', to='occurrences.OccurrenceChain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='period',
        ),
        migrations.CreateModel(
            name='OccurrenceChainInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_inclusions', to='occurrences.OccurrenceChain')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_inclusions', to='occurrences.Occurrence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='occurrence',
            name='chains',
            field=models.ManyToManyField(related_name='occurrences', through='occurrences.OccurrenceChainInclusion', to='occurrences.OccurrenceChain'),
        ),
    ]
