# Generated by Django 3.0.2 on 2020-01-31 17:28

from django.db import migrations, models
import django.db.models.deletion
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0031_auto_20200131_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='end_date',
            field=history.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='ending_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences_ended2', to='occurrences.Year'),
        ),
    ]
