# Generated by Django 3.0.2 on 2020-01-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0021_auto_20200105_2237'),
        ('occurrences', '0032_auto_20200131_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duration',
        ),
    ]
