# Generated by Django 3.0.2 on 2020-01-31 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0033_delete_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='polymorphic_ctype',
        ),
    ]
