# Generated by Django 3.0.2 on 2020-01-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0021_auto_20200105_2237'),
        ('occurrences', '0034_remove_occurrence_polymorphic_ctype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
