# Generated by Django 3.0.2 on 2020-01-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0035_delete_episode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='ending_year',
            new_name='end_year',
        ),
    ]
