# Generated by Django 3.0.2 on 2020-02-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0036_auto_20200131_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='string',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
