# Generated by Django 3.0.2 on 2020-02-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0039_auto_20200201_0616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='end_year',
        ),
    ]
