# Generated by Django 3.0.2 on 2020-02-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0024_remove_quote_attributee_name'),
        ('images', '0018_image_description'),
        ('entities', '0031_auto_20200202_0209'),
        ('places', '0005_venue_preposition'),
        ('sources', '0092_auto_20200201_1747'),
        ('occurrences', '0040_auto_20200201_1521'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occurrencechaininclusion',
            unique_together={('chain', 'occurrence')},
        ),
        migrations.AlterUniqueTogether(
            name='occurrenceentityinvolvement',
            unique_together={('occurrence', 'entity')},
        ),
        migrations.AlterUniqueTogether(
            name='occurrenceimage',
            unique_together={('occurrence', 'image')},
        ),
        migrations.AlterUniqueTogether(
            name='occurrencelocation',
            unique_together={('occurrence', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='occurrencequoterelation',
            unique_together={('occurrence', 'quote')},
        ),
        migrations.AlterUniqueTogether(
            name='occurrencesourcereference',
            unique_together={('occurrence', 'source')},
        ),
    ]
