# Generated by Django 3.0.2 on 2020-02-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0041_auto_20200202_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='year',
        ),
    ]
