# Generated by Django 3.0.2 on 2020-02-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0127_journal_file'),
        ('occurrences', '0042_remove_occurrence_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='occurrences', through='occurrences.OccurrenceSourceReference', to='sources.Source'),
        ),
    ]
