# Generated by Django 3.0.2 on 2020-02-11 10:47

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0043_auto_20200211_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='postscript',
            field=history.fields.HTMLField(blank=True, help_text='Content to be displayed below all related data', null=True),
        ),
    ]
