# Generated by Django 3.0.2 on 2020-02-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0044_occurrence_postscript'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrencequoterelation',
            options={'ordering': ['quote']},
        ),
    ]
