# Generated by Django 3.0.2 on 2020-02-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0045_auto_20200214_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrenceimage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='occurrenceimage',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
