# Generated by Django 3.0.2 on 2020-02-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0046_auto_20200214_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceimage',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
