# Generated by Django 3.0.2 on 2020-02-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0047_auto_20200215_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrenceimage',
            options={'ordering': ['position', 'image']},
        ),
    ]
