# Generated by Django 3.0.2 on 2020-02-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0048_auto_20200215_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceimage',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_images', to='occurrences.Occurrence'),
        ),
    ]
