# Generated by Django 3.0.2 on 2020-02-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0050_auto_20200216_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='key',
        ),
    ]
