# Generated by Django 3.0.2 on 2020-02-16 10:43

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    for occurrence in apps.get_model('occurrences', 'Occurrence').objects.all():
        occurrence.key = uuid.uuid4()
        occurrence.save(update_fields=['key'])


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0052_occurrence_key'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
