# Generated by Django 3.0.2 on 2020-02-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0054_auto_20200216_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
