# Generated by Django 3.0.2 on 2020-02-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0055_delete_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='date_is_circa',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
