# Generated by Django 3.0.2 on 2020-02-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0056_occurrence_date_is_circa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrencequoterelation',
            options={'ordering': ['position', 'quote']},
        ),
        migrations.AddField(
            model_name='occurrencequoterelation',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='occurrenceentityinvolvement',
            name='importance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary'), (4, 'Quaternary'), (5, 'Quinary'), (6, 'Senary'), (7, 'Septenary')], default=1),
        ),
    ]
