# Generated by Django 3.0.2 on 2020-02-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0057_auto_20200222_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceimage',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Set to 0 if the image is positioned manually.'),
        ),
    ]
