# Generated by Django 3.0.2 on 2020-02-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0058_auto_20200223_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='hidden',
            field=models.BooleanField(default=False, help_text="Don't let this item appear in search results."),
        ),
    ]
