# Generated by Django 3.0.4 on 2020-03-06 10:36

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0061_remove_occurrencesourcereference_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencechain',
            name='description',
            field=history.fields.HTMLField(max_length=200, null=True, unique=True),
        ),
    ]
