# Generated by Django 3.0.4 on 2020-03-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0171_auto_20200308_0557'),
        ('occurrences', '0062_occurrencechain_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occurrencesourcereference',
            unique_together={('occurrence', 'source', 'page_number', 'end_page_number'), ('occurrence', 'position')},
        ),
    ]
