# Generated by Django 3.1.3 on 2020-11-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulations', '0001_initial'),
        ('topics', '0001_initial'),
        ('entities', '0001_initial'),
        ('occurrences', '0002_auto_20201127_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicfactrelation',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_fact_relations', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='postulationsupport',
            name='supported_fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_fact_supports', to='postulations.postulation'),
        ),
        migrations.AddField(
            model_name='postulationsupport',
            name='supportive_fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportive_fact_supports', to='postulations.postulation'),
        ),
        migrations.AddField(
            model_name='postulation',
            name='related_entities',
            field=models.ManyToManyField(related_name='postulations', through='postulations.EntityFactRelation', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='postulation',
            name='related_occurrences',
            field=models.ManyToManyField(related_name='postulations', through='postulations.OccurrenceFactRelation', to='occurrences.Occurrence'),
        ),
        migrations.AddField(
            model_name='postulation',
            name='related_topics',
            field=models.ManyToManyField(related_name='postulations', through='postulations.TopicFactRelation', to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='postulation',
            name='supportive_facts',
            field=models.ManyToManyField(related_name='supported_postulations', through='postulations.PostulationSupport', to='postulations.Postulation'),
        ),
        migrations.AddField(
            model_name='occurrencefactrelation',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_occurrence_relations', to='postulations.postulation'),
        ),
        migrations.AddField(
            model_name='occurrencefactrelation',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_fact_relations', to='occurrences.occurrence'),
        ),
        migrations.AddField(
            model_name='entityfactrelation',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_fact_relations', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='entityfactrelation',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_entity_relations', to='postulations.postulation'),
        ),
        migrations.AlterUniqueTogether(
            name='topicfactrelation',
            unique_together={('topic', 'fact')},
        ),
        migrations.AlterUniqueTogether(
            name='occurrencefactrelation',
            unique_together={('fact', 'occurrence')},
        ),
        migrations.AlterUniqueTogether(
            name='entityfactrelation',
            unique_together={('fact', 'entity')},
        ),
    ]
