# Generated by Django 3.1.3 on 2020-11-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='text',
            new_name='summary',
        ),
    ]
