# Generated by Django 3.1.3 on 2020-11-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0008_auto_20201118_2018'),
        ('entities', '0004_remove_entity_parent_organization'),
        ('topics', '0005_auto_20201118_2005'),
        ('postulations', '0006_auto_20201125_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulation',
            name='related_entities',
            field=models.ManyToManyField(related_name='postulations', through='postulations.EntityFactRelation', to='entities.Entity'),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='related_occurrences',
            field=models.ManyToManyField(related_name='postulations', through='postulations.OccurrenceFactRelation', to='occurrences.Occurrence'),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='related_topics',
            field=models.ManyToManyField(related_name='postulations', through='postulations.TopicFactRelation', to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='supportive_facts',
            field=models.ManyToManyField(related_name='supported_postulations', through='postulations.PostulationSupport', to='postulations.Postulation'),
        ),
    ]
