# Generated by Django 3.1.3 on 2020-11-30 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='affiliated_entity',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='entities.entity',
                verbose_name='affiliated entity',
            ),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='entity',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='affiliations',
                to='entities.entity',
                verbose_name='entity',
            ),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='roles',
            field=models.ManyToManyField(
                blank=True,
                related_name='affiliations',
                through='entities.RoleFulfillment',
                to='entities.Role',
                verbose_name='roles',
            ),
        ),
    ]
