# Generated by Django 3.1.11 on 2021-05-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20210521_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityimage',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='title',
            field=models.CharField(
                blank=True,
                help_text='The title can be used for the detail page header and title tag, SERP result card header, etc. It should be a noun phrase!',
                max_length=120,
                null=True,
                verbose_name='title',
            ),
        ),
    ]
