# Generated by Django 3.1.12 on 2021-06-10 17:50

import django.db.models.deletion
from django.db import migrations, models

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
        ('entities', '0003_auto_20210604_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionInclusion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'collection',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='collectioninclusion_relations',
                        to='collections.collection',
                    ),
                ),
                (
                    'content_object',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='collection_inclusions',
                        to='entities.entity',
                        verbose_name='entity',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='imagerelation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='image_relations',
                to='entities.entity',
                verbose_name='entity',
            ),
        ),
        migrations.DeleteModel(
            name='EntityImage',
        ),
    ]
