# Generated by Django 3.1.4 on 2020-12-03 23:16

from django.db import migrations, models

import modularhistory.fields.array_field


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20201203_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'noun'), ('adj', 'adjective'), ('any', 'noun / adjective')], default='adj', max_length=9, verbose_name='part of speech'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='aliases',
            field=modularhistory.fields.array_field.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
    ]
