# Generated by Django 3.1.11 on 2021-05-28 22:23

import autoslug.fields
from django.db import migrations, models

import core.fields
import core.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_convert_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                paragraphed=True,
                processed=True,
                processor=core.fields.html_field.process,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                blank=True,
                default='',
                editable=True,
                populate_from='get_slug',
                unique=True,
                verbose_name='slug',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='title',
            field=models.CharField(
                blank=True,
                default='',
                help_text='The title can be used for the detail page header and title tag, SERP result card header, etc. It should be a noun phrase!',
                max_length=120,
                verbose_name='title',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='unabbreviated_name',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                paragraphed=True,
                processed=True,
                processor=core.fields.html_field.process,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                paragraphed=None,
                processed=True,
                processor=core.fields.html_field.process,
            ),
            preserve_default=False,
        ),
    ]
