# Generated by Django 3.1.11 on 2021-05-30 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0019_remove_polymorphicproposition_old_locations'),
        ('entities', '0006_auto_20210528_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='birth',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='born_entity',
                to='propositions.birth',
            ),
        ),
        migrations.AddField(
            model_name='entity',
            name='death',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='dead_entity',
                to='propositions.death',
            ),
        ),
    ]
