# Generated by Django 3.1.4 on 2020-12-17 16:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20201206_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=True,
                null=True,
                populate_from='get_slug',
                unique=True,
                verbose_name='slug',
            ),
        ),
    ]
