# Generated by Django 3.1.6 on 2021-02-04 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_entity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorization',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorizations', to='entities.category', verbose_name='category'),
        ),
    ]
