# Generated by Django 3.1.8 on 2021-04-29 16:57

from django.db import migrations

import core.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20210204_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='reference_urls',
            field=core.fields.json_field.JSONField(blank=True, default=dict),
        ),
    ]
