# Generated by Django 3.1.11 on 2021-06-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_remove_entity_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='_images',
            new_name='images',
        ),
    ]
