# Generated by Django 3.1.9 on 2021-05-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_entity_reference_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='related_entities',
            field=models.ManyToManyField(
                to='entities.Entity', verbose_name='related entities'
            ),
        ),
    ]
