# Generated by Django 3.1.9 on 2021-05-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_auto_20210505_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='title',
            field=models.CharField(
                blank=True,
                help_text='The title can be used for the detail page header and title tag, SERP result card header, etc.',
                max_length=120,
                null=True,
                verbose_name='title',
            ),
        ),
    ]
