# Generated by Django 3.1.9 on 2021-05-13 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_auto_20210512_1927'),
        ('entities', '0012_entity_title'),
    ]

    operations = []
