# Generated by Django 3.1.9 on 2021-05-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0013_merge_20210513_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='related_entities',
            field=models.ManyToManyField(
                blank=True,
                related_name='entity_set',
                to='entities.Entity',
                verbose_name='related entities',
            ),
        ),
    ]
