# Generated by Django 3.1.13 on 2021-08-24 15:28

import django.db.models.deletion
from django.db import migrations, models

import apps.entities.models.model_with_related_entities
import apps.topics.models.taggable
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20210820_2138'),
        ('entities', '0013_auto_20210823_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='related_entities',
            field=apps.entities.models.model_with_related_entities.RelatedEntitiesField(
                blank=True,
                related_name='entity_set',
                through='entities.EntityRelation',
                to='entities.Entity',
                verbose_name='related entities',
            ),
        ),
        migrations.CreateModel(
            name='TopicRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                (
                    'content_object',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='topic_relations',
                        to='entities.entity',
                        verbose_name='entity',
                    ),
                ),
                (
                    'topic',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entities_topicrelation_set',
                        to='topics.topic',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='tags',
            field=apps.topics.models.taggable.TagsField(
                blank=True,
                related_name='entity_set',
                through='entities.TopicRelation',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
    ]
