# Generated by Django 3.1.9 on 2021-05-15 21:38

from django.db import migrations, models

import core.fields.sorted_m2m_field


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_auto_20210514_1815'),
        ('topics', '0003_auto_20210428_2009'),
        ('entities', '0014_auto_20210514_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='new_tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='entity_set',
                to='topics.Topic',
                verbose_name='citations',
            ),
        ),
        migrations.AddField(
            model_name='entity',
            name='related_quotes',
            field=core.fields.sorted_m2m_field.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name='entity_set',
                sort_value_field_name='position',
                to='quotes.Quote',
                verbose_name='images',
            ),
        ),
    ]
