# Generated by Django 3.1.13 on 2021-08-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_auto_20210824_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorization',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='categorization',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
