# Generated by Django 3.1.9 on 2021-05-17 01:31

from django.db import migrations, models

import core.fields.sorted_m2m_field


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20210428_2009'),
        ('quotes', '0025_quote_sources'),
        ('entities', '0015_auto_20210515_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='new_tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='entity_set',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
        migrations.AlterField(
            model_name='entity',
            name='related_quotes',
            field=core.fields.sorted_m2m_field.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name='entity_set',
                sort_value_field_name='position',
                to='quotes.Quote',
                verbose_name='related quotes',
            ),
        ),
    ]
