# Generated by Django 3.1.9 on 2021-05-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_auto_20210517_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='related_quotes',
        ),
    ]
