# Generated by Django 3.1.9 on 2021-05-17 16:54

import django.db.models.deletion
from django.db import migrations, models

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0030_auto_20210517_1654'),
        ('entities', '0017_remove_entity_related_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'content_object',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quote_relations',
                        to='entities.entity',
                    ),
                ),
                (
                    'quote',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entities_quoterelations',
                        to='quotes.quote',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
