# Generated by Django 3.1.9 on 2021-05-17 19:17

import django.db.models.deletion
from django.db import migrations

import apps.quotes.models.model_with_related_quotes
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0034_auto_20210517_1905'),
        ('entities', '0018_quoterelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='related_quotes',
            field=apps.quotes.models.model_with_related_quotes.RelatedQuotesField(
                blank=True,
                related_name='entity_set',
                through='entities.QuoteRelation',
                to='quotes.Quote',
                verbose_name='related quotes',
            ),
        ),
        migrations.AlterField(
            model_name='quoterelation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quoterelation_relations',
                to='entities.entity',
            ),
        ),
    ]
