# Generated by Django 3.1.9 on 2021-05-19 14:26

from django.db import migrations

import core.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0022_auto_20210518_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='_cached_images',
            field=core.fields.json_field.JSONField(default=list, editable=False),
        ),
    ]
