# Generated by Django 3.1.9 on 2021-05-19 15:11

import django.db.models.deletion
from django.db import migrations

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0024_auto_20210519_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterelation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quote_relations',
                to='entities.entity',
                verbose_name='entity',
            ),
        ),
    ]
