# Generated by Django 3.1.9 on 2021-05-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0026_auto_20210519_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='_cached_tags',
        ),
    ]
