# Generated by Django 3.1.9 on 2021-05-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0027_remove_entity__cached_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='_cached_images',
        ),
    ]
