# Generated by Django 3.1.13 on 2021-08-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210822_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
    ]
