# Generated by Django 3.1.13 on 2021-08-22 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20210822_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='new_tags',
            new_name='tags',
        ),
    ]
