# Generated by Django 3.1.13 on 2021-08-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_change_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='n_remaining_approvals_required',
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=3,
                editable=False,
                verbose_name='number of remaining approvals required',
            ),
        ),
        migrations.AddField(
            model_name='changeset',
            name='n_remaining_approvals_required',
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=3,
                editable=False,
                verbose_name='number of remaining approvals required',
            ),
        ),
    ]
