# Generated by Django 3.1.13 on 2021-08-31 02:58

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Change = apps.get_model('moderation', 'Change')
    ChangeSet = apps.get_model('moderation', 'ChangeSet')
    Change.objects.filter(moderation_status=3).update(moderation_status=2)
    ChangeSet.objects.filter(moderation_status=3).update(moderation_status=2)


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_change_requires_rebase'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='change',
            name='moderation_status',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Rejected'), (1, 'Pending'), (2, 'Approved')],
                default=1,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='moderation_status',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Rejected'), (1, 'Pending'), (2, 'Approved')],
                default=1,
                editable=False,
            ),
        ),
    ]
