name: 'Setup'
description: 'Greet someone'
inputs:
  fetch-depth:
    description: 'Git fetch depth'
    required: false
    default: 1
  os:
    description: 'Operating system'
    required: true
  python-version:
    description: 'Python version'
    required: true
runs:
  using: "composite"
  steps: 
    - name: Check out main branch
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Add hosts to /etc/hosts
      run: |
        sudo echo "127.0.0.1 postgres" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 redis" | sudo tee -a /etc/hosts
    - name: Install Chrome and Firefox
      run: |
        sudo apt install google-chrome-stable
        sudo apt-get install firefox
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1.1.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Cache Python virtual environment
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          .venv
          **/node_modules
        key: ${{ inputs.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'
