# When composite actions support `uses` (https://github.com/actions/runner/issues/646),
# this can be converted to a composite action. In the meantime, we are using
# https://github.com/mithro/actions-includes to allow `uses`.

name: 'Start application'
description: 'Run the application containers'
runs:
  using: "includes"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Create writable volume directories
      run: |
        writable_dirs=( ".backups" ".init" "_static" "_media" )
        for writable_dir in "${writable_dirs[@]}"; do
          mkdir -p "$writable_dir"; {
            sudo chown -R www-data:www-data "$writable_dir" && 
            sudo chmod a+w -R "$writable_dir"
          } || exit 1
        done
    - uses: actions/cache@v2
      id: data-cache
      with:
        path: .init
        key: data
    - name: Fetch data
      if: ${{ steps.data-cache.outputs.cache-hit != 'true' }}
      run: |
        test -w .init || {
          echo "Cannot write in .init directory."; exit 1
        }
        rclone --help &>/dev/null || {
          curl https://rclone.org/install.sh | sudo bash 
        } || exit 1
        poetry run invoke db.seed --remote
    - name: Start up containers
      shell: bash
      run: |
        echo "Starting containers with version $SHA ..."
        docker-compose up -d webserver; echo ""; docker-compose ps
        [[ ! "$(docker-compose ps)" =~ webserver ]] && exit 1
        healthy=false; timeout=300; interval=15; waited=0
        while [[ "$healthy" = false ]]; do
          healthy=true; [[ "$(docker-compose ps)" =~ (Exit|unhealthy|starting) ]] && healthy=false
          if [[ "$healthy" = false ]]; then
            [[ $((waited%2)) -eq 0 ]] && docker-compose logs --tail 15
            echo "" && docker-compose ps
            echo "" && echo "Waiting for containers (${waited}s) ..."
            sleep $interval; waited=$((waited + interval))
            if [[ $waited -gt $timeout ]]; then 
              echo "" && echo "Timed out."
              docker-compose logs; exit 1
            fi
          fi
        done; docker-compose ps
