# Generated by Django 3.1.2 on 2020-10-16 01:33

from django.db import migrations, models
import functools
import image_cropping.fields
import modularhistory.fields
import modularhistory.fields.file_field
import modularhistory.fields.historic_datetime_field
import modularhistory.fields.json_field
import uuid


class Migration(migrations.Migration):

    replaces = [('images', '0001_initial'), ('images', '0002_image_cropping'), ('images', '0003_auto_20200314_0731'), ('images', '0004_auto_20200314_0835'), ('images', '0005_auto_20200319_1119'), ('images', '0006_image_links'), ('images', '0007_auto_20201013_0656'), ('images', '0008_auto_20201015_2347')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_is_circa', models.BooleanField(blank=True, default=False)),
                ('date', modularhistory.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('hidden', models.BooleanField(blank=True, default=False, help_text="Don't let this item appear in search results.")),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('caption', modularhistory.fields.HTMLField(blank=True, null=True)),
                ('description', modularhistory.fields.HTMLField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(null=True, unique=True)),
                ('embed_code', models.CharField(max_length=200, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('computations', modularhistory.fields.json_field.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'unique_together': {('title', 'url')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_is_circa', models.BooleanField(blank=True, default=False)),
                ('date', modularhistory.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('hidden', models.BooleanField(blank=True, default=False, help_text="Don't let this item appear in search results.")),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('caption', modularhistory.fields.HTMLField(blank=True, null=True)),
                ('description', modularhistory.fields.HTMLField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(height_field='height', null=True, upload_to=functools.partial(modularhistory.fields.file_field._generate_upload_path, *(), **{'path': 'images/'}), width_field='width')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('image', 'Image'), ('photo', 'Photo'), ('illustration', 'Illustration'), ('painting', 'Painting'), ('portrait', 'Portrait'), ('diagram', 'Diagram'), ('reconstruction', 'Reconstruction'), ('photomontage', 'Photomontage'), ('model', 'Model')], default='image', max_length=14)),
                ('cropping', image_cropping.fields.ImageRatioField('image', '0x0', adapt_rotation=False, allow_fullsize=True, free_crop=True, help_text='Not yet fully implemented.', hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('links', models.JSONField(default=dict)),
                ('computations', modularhistory.fields.json_field.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('image', 'caption')},
            },
        ),
    ]
