# Generated by Django 3.0.1 on 2019-12-28 23:41

from django.db import migrations, models
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=history.fields.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='provider',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
