# Generated by Django 3.1.2 on 2020-10-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='type',
            new_name='image_type',
        ),
    ]
