# Generated by Django 3.0.1 on 2019-12-29 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20191228_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illustration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='polymorphic_ctype',
        ),
    ]
