# Generated by Django 3.1.2 on 2020-10-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20201018_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
