# Generated by Django 3.0.4 on 2020-03-14 08:35

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200314_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cropped_image',
        ),
        migrations.AddField(
            model_name='image',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '0x0', adapt_rotation=False, allow_fullsize=True, free_crop=True, help_text='Not yet fully implemented.', hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
