# Generated by Django 3.0.1 on 2020-01-01 19:08

from django.db import migrations, models
import django.db.models.deletion
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0008_auto_20191231_1840'),
        ('images', '0003_auto_20191229_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date',
            field=history.fields.HistoricDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='occurrences.Year'),
        ),
    ]
