# Generated by Django 3.0.1 on 2020-01-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200101_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='length',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
