# Generated by Django 3.0.4 on 2020-03-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200314_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='link',
            new_name='url',
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('title', 'url')},
        ),
    ]
