# Generated by Django 3.0.7 on 2020-08-19 04:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20200319_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
