# Generated by Django 3.0.1 on 2020-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_video_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='max_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
