# Generated by Django 3.0.10 on 2020-10-13 06:56

from django.db import migrations
import modularhistory.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='computations',
            field=modularhistory.fields.json_field.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='computations',
            field=modularhistory.fields.json_field.JSONField(blank=True, default=dict, null=True),
        ),
    ]
