# Generated by Django 3.0.1 on 2020-01-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_max_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
