# Generated by Django 3.0.1 on 2020-01-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_image_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='verified',
        ),
    ]
