# Generated by Django 3.1.2 on 2020-10-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20201013_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='links',
            field=models.JSONField(default=dict),
        ),
    ]
