# Generated by Django 3.0.1 on 2020-01-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_remove_image_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ImageTag',
        ),
    ]
