# Generated by Django 3.0.1 on 2020-01-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_auto_20200124_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='max_width',
        ),
    ]
