# Generated by Django 3.0.1 on 2020-01-26 12:25

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_remove_image_max_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='datetime',
            field=history.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True),
        ),
    ]
