# Generated by Django 3.0.1 on 2020-01-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_image_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='date',
        ),
    ]
