# Generated by Django 3.0.2 on 2020-01-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_auto_20200126_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['year', 'date']},
        ),
    ]
