# Generated by Django 3.0.2 on 2020-01-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20200131_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-year__years_before_present', '-date']},
        ),
    ]
