# Generated by Django 3.0.2 on 2020-01-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_auto_20200131_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='caption',
        ),
    ]
