# Generated by Django 3.0.2 on 2020-02-02 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_image_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image', 'caption')},
        ),
    ]
