# Generated by Django 3.0.2 on 2020-02-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_auto_20200202_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='year',
        ),
    ]
