# Generated by Django 3.0.2 on 2020-02-02 03:53

from django.db import migrations, models
import functools
import history.fields.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0020_auto_20200202_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', null=True, upload_to=functools.partial(history.fields.file_field._update_filename, *(), **{'path': 'images/'}), width_field='width'),
        ),
    ]
