# Generated by Django 3.0.2 on 2020-02-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_auto_20200202_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('photo', 'Photo'), ('illustration', 'Illustration'), ('painting', 'Painting'), ('photomontage', 'Photomontage'), ('diagram', 'Diagram'), ('model', 'Model')], default='image', max_length=12),
        ),
    ]
