# Generated by Django 3.0.2 on 2020-02-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0022_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('photo', 'Photo'), ('illustration', 'Illustration'), ('painting', 'Painting'), ('diagram', 'Diagram'), ('reconstruction', 'Reconstruction'), ('photomontage', 'Photomontage'), ('model', 'Model')], default='image', max_length=14),
        ),
    ]
