# Generated by Django 3.0.2 on 2020-02-16 10:42

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    for image in apps.get_model('images', 'Image').objects.all():
        image.key = uuid.uuid4()
        image.save(update_fields=['key'])


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0027_image_key'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
