# Generated by Django 3.0.2 on 2020-02-16 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0028_auto_20200216_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
