# Generated by Django 3.0.2 on 2020-02-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0029_auto_20200216_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('photo', 'Photo'), ('illustration', 'Illustration'), ('painting', 'Painting'), ('portrait', 'Portrait'), ('diagram', 'Diagram'), ('reconstruction', 'Reconstruction'), ('photomontage', 'Photomontage'), ('model', 'Model')], default='image', max_length=14),
        ),
    ]
