# Generated by Django 3.0.2 on 2020-02-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0030_auto_20200222_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hidden',
            field=models.BooleanField(default=False, help_text="Don't let this item appear in search results."),
        ),
    ]
