# Generated by Django 3.0.4 on 2020-03-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0061_remove_occurrencesourcereference_notes'),
        ('entities', '0045_entityidea_idea'),
        ('images', '0034_auto_20200304_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_ptr',
        ),
        migrations.DeleteModel(
            name='Illustration',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
