# Generated by Django 3.0.4 on 2020-03-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0061_remove_occurrencesourcereference_notes'),
        ('entities', '0045_entityidea_idea'),
        ('images', '0035_auto_20200306_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_is_circa',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
