# Generated by Django 3.0.4 on 2020-03-06 08:56

from django.db import migrations, models
import history.fields.historic_datetime_field
import history.fields.html_field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0036_auto_20200306_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('hidden', models.BooleanField(blank=True, default=False, help_text="Don't let this item appear in search results.")),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_is_circa', models.BooleanField(blank=True, default=False)),
                ('date', history.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True)),
                ('caption', history.fields.html_field.HTMLField(blank=True, null=True)),
                ('description', history.fields.html_field.HTMLField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('link', models.URLField(null=True)),
                ('embed_code', models.CharField(max_length=200, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
