# Generated by Django 3.0.4 on 2020-03-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0037_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('title', 'link')},
        ),
    ]
