# Generated by Django 3.1.8 on 2021-04-16 04:50

import functools
import uuid

import autoslug.fields
import django.db.models.deletion
import gm2m.fields
from django.db import migrations, models

import core.fields
import core.fields.file_field
import core.fields.historic_datetime_field
import core.fields.html_field
import core.fields.json_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0009_auto_20210204_0619'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('places', '0002_auto_20201206_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    'citation_phrase',
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, ''),
                            ('quoted in', 'quoted in'),
                            ('cited in', 'cited in'),
                            ('partially reproduced in', 'partially reproduced in'),
                        ],
                        default=None,
                        max_length=25,
                        null=True,
                    ),
                ),
                ('pages', core.fields.json_field.JSONField(default=list)),
                ('object_id', models.PositiveIntegerField()),
                (
                    'content_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'ordering': ['position', 'source'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'computations',
                    core.fields.json_field.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    'date_is_circa',
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text='whether the date is estimated/imprecise',
                        verbose_name='date is circa',
                    ),
                ),
                (
                    'verified',
                    models.BooleanField(default=False, verbose_name='verified'),
                ),
                (
                    'key',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name='key',
                    ),
                ),
                (
                    'slug',
                    autoslug.fields.AutoSlugField(
                        blank=True,
                        editable=True,
                        null=True,
                        populate_from='get_slug',
                        unique=True,
                        verbose_name='slug',
                    ),
                ),
                (
                    'hidden',
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text='Hide this item from search results.',
                    ),
                ),
                (
                    'attributee_html',
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    'attributee_string',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ('citation_html', models.TextField(blank=True)),
                (
                    'citation_string',
                    models.CharField(blank=True, max_length=500, unique=True),
                ),
                (
                    'date',
                    core.fields.historic_datetime_field.HistoricDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    'description',
                    core.fields.HTMLField(
                        blank=True,
                        null=True,
                        paragraphed=True,
                        processor=core.fields.html_field.process,
                    ),
                ),
                (
                    'publication_date',
                    core.fields.historic_datetime_field.HistoricDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name='title'
                    ),
                ),
                (
                    'url',
                    models.URLField(
                        blank=True,
                        help_text='URL where the source can be accessed online',
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('sources.journal', 'journal'),
                            ('sources.magazine', 'magazine'),
                            ('sources.newspaper', 'newspaper'),
                        ],
                        db_index=True,
                        max_length=255,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='name',
                    ),
                ),
                (
                    'aliases',
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name='aliases'
                    ),
                ),
                (
                    'description',
                    core.fields.HTMLField(
                        blank=True,
                        null=True,
                        paragraphed=True,
                        processor=core.fields.html_field.process,
                        verbose_name='description',
                    ),
                ),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    core.fields.file_field.SourceFileField(
                        blank=True,
                        null=True,
                        unique=True,
                        upload_to=functools.partial(
                            core.fields.file_field._generate_upload_path,
                            *(),
                            **{'path': 'sources/'}
                        ),
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    'page_offset',
                    models.SmallIntegerField(
                        blank=True,
                        default=0,
                        help_text='The difference between the page numbers displayed on the pages and the actual page numbers of the electronic file (a positive number if the electronic page number is greater than the textualpage number; a negative number if the textual page number is greater than the electronic page number).',
                    ),
                ),
                (
                    'first_page_number',
                    models.SmallIntegerField(
                        blank=True,
                        default=1,
                        help_text='The page number that is visibly displayed on the page on which the relevant text begins (usually 1).',
                    ),
                ),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='name',
                    ),
                ),
                (
                    'aliases',
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name='aliases'
                    ),
                ),
                (
                    'description',
                    core.fields.HTMLField(
                        blank=True,
                        null=True,
                        paragraphed=True,
                        processor=core.fields.html_field.process,
                        verbose_name='description',
                    ),
                ),
                (
                    'owner',
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name='owner'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('documentary', 'Documentary')],
                        default='documentary',
                        max_length=12,
                        verbose_name='film type',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sources.source',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                ('editors', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'original_publication_date',
                    core.fields.historic_datetime_field.HistoricDateTimeField(
                        blank=True, null=True
                    ),
                ),
                ('translator', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'edition_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'edition_year',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'printing_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'volume_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'original_edition',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='subsequent_editions',
                        to='sources.book',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sources.source', models.Model),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                (
                    'interviewers',
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name='interviewers',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sources.source',),
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('speech', 'Speech'),
                            ('address', 'Address'),
                            ('discourse', 'Discourse'),
                            ('lecture', 'Lecture'),
                            ('sermon', 'Sermon'),
                            ('statement', 'Statement'),
                        ],
                        default='speech',
                        max_length=10,
                        verbose_name='speech type',
                    ),
                ),
                ('audience', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sources.source',),
        ),
        migrations.CreateModel(
            name='SourceContainment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    'page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'end_page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'phrase',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('', '-----'),
                            ('archived', 'archived'),
                            ('cited', 'cited'),
                            ('copy', 'copy'),
                            ('quoted', 'quoted'),
                            ('recorded', 'recorded'),
                            ('reproduced', 'reproduced'),
                            ('transcribed', 'transcribed'),
                        ],
                        default='',
                        max_length=12,
                    ),
                ),
                (
                    'container',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='container_containments',
                        to='sources.source',
                    ),
                ),
                (
                    'source',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='source_containments',
                        to='sources.source',
                    ),
                ),
            ],
            options={
                'ordering': ['position', 'source'],
            },
        ),
        migrations.CreateModel(
            name='SourceAttribution',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    'attributee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='source_attributions',
                        to='entities.entity',
                    ),
                ),
                (
                    'source',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attributions',
                        to='sources.source',
                        verbose_name='source',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'computations',
                    core.fields.json_field.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        help_text='e.g., "L. Tom Perry Special Collections"',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'owner',
                    models.CharField(
                        blank=True,
                        help_text='e.g., "Harold B. Lee Library, Brigham Young University"',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'location',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='repositories',
                        to='places.place',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.AddField(
            model_name='source',
            name='attributees',
            field=models.ManyToManyField(
                blank=True,
                related_name='attributed_sources',
                through='sources.SourceAttribution',
                to='entities.Entity',
                verbose_name='attributees',
            ),
        ),
        migrations.AddField(
            model_name='source',
            name='containers',
            field=models.ManyToManyField(
                blank=True,
                related_name='contained_sources',
                through='sources.SourceContainment',
                to='sources.Source',
            ),
        ),
        migrations.AddField(
            model_name='source',
            name='file',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sources',
                to='sources.sourcefile',
                verbose_name='file',
            ),
        ),
        migrations.AddField(
            model_name='source',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='places.place',
            ),
        ),
        migrations.AddField(
            model_name='source',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_sources.source_set+',
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AddField(
            model_name='source',
            name='related',
            field=gm2m.fields.GM2MField(
                'quotes.Quote',
                'occurrences.Occurrence',
                blank=True,
                related_name='sources',
                through='sources.Citation',
                through_fields=[
                    'source',
                    'content_object',
                    'content_type',
                    'object_id',
                ],
            ),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'computations',
                    core.fields.json_field.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        help_text='e.g., "Adam S. Bennion papers"',
                        max_length=100,
                        null=True,
                    ),
                ),
                ('url', models.URLField(blank=True, null=True)),
                (
                    'repository',
                    models.ForeignKey(
                        help_text='the library or institution housing the collection',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='sources.repository',
                    ),
                ),
            ],
            options={
                'unique_together': {('name', 'repository')},
            },
        ),
        migrations.AddField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='citations',
                to='sources.source',
            ),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.publication',),
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.publication',),
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.publication',),
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                ('editors', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'original_publication_date',
                    core.fields.historic_datetime_field.HistoricDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    'original_edition',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='subsequent_editions',
                        to='sources.webpage',
                    ),
                ),
                (
                    'website',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='sources.website',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sources.source', models.Model),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('chapter', 'Chapter'), ('section', 'Section')],
                        default='chapter',
                        max_length=10,
                        verbose_name='section type',
                    ),
                ),
                (
                    'work',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='sources.book',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sources.source',),
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                ('editors', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'original_publication_date',
                    core.fields.historic_datetime_field.HistoricDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    'page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'end_page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('essay', 'Essay')],
                        default='essay',
                        max_length=10,
                        verbose_name='piece type',
                    ),
                ),
                (
                    'original_edition',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='subsequent_editions',
                        to='sources.piece',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sources.source', models.Model),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                ('editors', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'original_publication_date',
                    core.fields.historic_datetime_field.HistoricDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    'page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'end_page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'original_edition',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='subsequent_editions',
                        to='sources.entry',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'journal entries',
            },
            bases=('sources.source', models.Model),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                ('editors', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'original_publication_date',
                    core.fields.historic_datetime_field.HistoricDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    'page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'end_page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'collection_number',
                    models.PositiveSmallIntegerField(
                        blank=True, help_text='aka acquisition number', null=True
                    ),
                ),
                (
                    'location_info',
                    models.TextField(
                        blank=True,
                        help_text='Ex: John Alexander Papers, Series 1: Correspondence, 1831-1848, Folder 1',
                        null=True,
                    ),
                ),
                (
                    'descriptive_phrase',
                    models.CharField(
                        blank=True,
                        help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'information_url',
                    models.CharField(
                        blank=True,
                        help_text='URL for information regarding the document',
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    'collection',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='document',
                        to='sources.collection',
                    ),
                ),
                (
                    'original_edition',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='subsequent_editions',
                        to='sources.document',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sources.source', models.Model),
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                ('editors', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'original_publication_date',
                    core.fields.historic_datetime_field.HistoricDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    'page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'end_page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'collection_number',
                    models.PositiveSmallIntegerField(
                        blank=True, help_text='aka acquisition number', null=True
                    ),
                ),
                (
                    'location_info',
                    models.TextField(
                        blank=True,
                        help_text='Ex: John Alexander Papers, Series 1: Correspondence, 1831-1848, Folder 1',
                        null=True,
                    ),
                ),
                (
                    'descriptive_phrase',
                    models.CharField(
                        blank=True,
                        help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'information_url',
                    models.CharField(
                        blank=True,
                        help_text='URL for information regarding the document',
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('correspondence', 'correspondence'),
                            ('email', 'email'),
                            ('letter', 'letter'),
                            ('memorandum', 'memorandum'),
                        ],
                        default='correspondence',
                        max_length=14,
                        verbose_name='image type',
                    ),
                ),
                ('recipient', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'collection',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='correspondence',
                        to='sources.collection',
                    ),
                ),
                (
                    'original_edition',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='subsequent_editions',
                        to='sources.correspondence',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sources.source', models.Model),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                ('editors', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'original_publication_date',
                    core.fields.historic_datetime_field.HistoricDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    'page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'end_page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('volume', models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    'original_edition',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='subsequent_editions',
                        to='sources.article',
                    ),
                ),
                (
                    'publication',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='sources.publication',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sources.source', models.Model),
        ),
        migrations.CreateModel(
            name='Affidavit',
            fields=[
                (
                    'source_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='sources.source',
                    ),
                ),
                ('editors', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'original_publication_date',
                    core.fields.historic_datetime_field.HistoricDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    'page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'end_page_number',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'collection_number',
                    models.PositiveSmallIntegerField(
                        blank=True, help_text='aka acquisition number', null=True
                    ),
                ),
                (
                    'location_info',
                    models.TextField(
                        blank=True,
                        help_text='Ex: John Alexander Papers, Series 1: Correspondence, 1831-1848, Folder 1',
                        null=True,
                    ),
                ),
                (
                    'descriptive_phrase',
                    models.CharField(
                        blank=True,
                        help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'information_url',
                    models.CharField(
                        blank=True,
                        help_text='URL for information regarding the document',
                        max_length=200,
                        null=True,
                    ),
                ),
                ('certifier', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'collection',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='affidavit',
                        to='sources.collection',
                    ),
                ),
                (
                    'original_edition',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='subsequent_editions',
                        to='sources.affidavit',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sources.source', models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together={('source', 'content_type', 'object_id', 'position')},
        ),
    ]
