# Generated by Django 3.1.8 on 2021-04-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='citation_html',
            field=models.TextField(blank=True, verbose_name='citation HTML'),
        ),
    ]
