# Generated by Django 3.1.8 on 2021-04-19 06:06

import django.db.models.deletion
from django.db import migrations, models

import core.fields
import core.fields.html_field
from apps.dates.fields import HistoricDateTimeField


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20201206_1823'),
        ('sources', '0002_auto_20210417_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='containment_html',
            field=models.TextField(
                blank=True, null=True, verbose_name='containment HTML'
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='attributee_html',
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name='attributee HTML'
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='attributee_string',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='attributee string'
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='citation_string',
            field=models.CharField(
                blank=True, max_length=500, unique=True, verbose_name='citation string'
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='containers',
            field=models.ManyToManyField(
                blank=True,
                related_name='contained_sources',
                through='sources.SourceContainment',
                to='sources.Source',
                verbose_name='containers',
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=core.fields.HTMLField(
                blank=True,
                null=True,
                paragraphed=True,
                processor=core.fields.html_field.process,
                verbose_name='description',
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='places.place',
                verbose_name='location',
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='publication_date',
            field=HistoricDateTimeField(
                blank=True, null=True, verbose_name='publication date'
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(
                blank=True,
                help_text='URL where the source can be accessed online',
                max_length=100,
                null=True,
                verbose_name='URL',
            ),
        ),
    ]
