# Generated by Django 3.1.11 on 2021-05-22 18:44

from django.db import migrations

import apps.dates.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_source_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='date',
            field=apps.dates.fields.HistoricDateTimeField(
                blank=True, null=True, verbose_name='date'
            ),
        ),
    ]
