# Generated by Django 3.1.8 on 2021-04-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20210419_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='href',
            field=models.URLField(
                blank=True,
                help_text='URL to use as the href when presenting a link to the source. This could be the URL of the source file (if one exists) or of a webpage.',
                null=True,
                verbose_name='href',
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(
                blank=True,
                help_text='URL where the source can be accessed online (outside ModularHistory)',
                max_length=100,
                null=True,
                verbose_name='URL',
            ),
        ),
    ]
