# Generated by Django 3.1.8 on 2021-05-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20210421_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='key',
        ),
    ]
