# Generated by Django 3.1.11 on 2021-05-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20210522_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='website_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
