# Generated by Django 3.1.9 on 2021-05-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_entity_related_entities'),
        ('sources', '0005_remove_source_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='related_entities',
            field=models.ManyToManyField(
                to='entities.Entity', verbose_name='related entities'
            ),
        ),
    ]
