# Generated by Django 3.1.13 on 2021-08-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_auto_20210627_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='attributee_html',
            field=models.CharField(
                blank=True,
                help_text='If not set manually, this value is set automatically based on the `attributees` relationship.',
                max_length=300,
                verbose_name='attributee HTML',
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='attributee_string',
            field=models.CharField(
                blank=True, editable=False, max_length=100, verbose_name='attributee string'
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='containment_html',
            field=models.TextField(
                blank=True,
                help_text='This value is set automatically but can be overridden.',
                verbose_name='containment HTML',
            ),
        ),
    ]
