# Generated by Django 3.1.11 on 2021-05-28 22:23

import autoslug.fields
from django.db import migrations

import core.fields
import core.fields.html_field


def convert_nulls(apps, schema_editor):
    app = 'sources'
    models = (
        'Source',
        'Affidavit',
        'Document',
        'Article',
        'Book',
        'Collection',
        'Correspondence',
        'Document',
        'Entry',
        'Piece',
        'Publication',
        'Interview',
        'Repository',
        'SourceFile',
        'Webpage',
        'Website',
    )
    fields = (
        'certifier',
        'title',
        'slug',
        'descriptive_phrase',
        'location_info',
        'editors',
        'information_url',
        'publisher',
        'translator',
        'name',
        'recipient',
        'interviewers',
        'aliases',
        'description',
        'attributee_html',
        'attributee_string',
        'content',
        'owner',
        'containment_html',
    )
    for model in models:
        Model = apps.get_model(app, model)
        for field in fields:
            if hasattr(Model, field):
                filter_param = {f'{field}__isnull': True}
                update_param = {field: ''}
                Model.objects.filter(**filter_param).update(**update_param)


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_webpage_website_name'),
    ]

    operations = [
        migrations.RunPython(convert_nulls, migrations.RunPython.noop),
    ]
