# Generated by Django 3.1.9 on 2021-05-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_auto_20210512_1927'),
        ('sources', '0006_source_related_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='related_entities',
            field=models.ManyToManyField(
                blank=True, to='entities.Entity', verbose_name='related entities'
            ),
        ),
    ]
