# Generated by Django 3.1.11 on 2021-05-28 22:23

import autoslug.fields
from django.db import migrations, models

import core.fields
import core.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_convert_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affidavit',
            name='certifier',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affidavit',
            name='descriptive_phrase',
            field=models.CharField(
                blank=True,
                default='',
                help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"',
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affidavit',
            name='editors',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affidavit',
            name='information_url',
            field=models.URLField(
                blank=True,
                help_text='URL for information regarding the document',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='affidavit',
            name='location_info',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Ex: John Alexander Papers, Series 1: Correspondence, 1831-1848, Folder 1',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='editors',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='editors',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(
                blank=True,
                default='',
                help_text='e.g., "Adam S. Bennion papers"',
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='descriptive_phrase',
            field=models.CharField(
                blank=True,
                default='',
                help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"',
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='editors',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='information_url',
            field=models.URLField(
                blank=True,
                help_text='URL for information regarding the document',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='location_info',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Ex: John Alexander Papers, Series 1: Correspondence, 1831-1848, Folder 1',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='recipient',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='descriptive_phrase',
            field=models.CharField(
                blank=True,
                default='',
                help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"',
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='editors',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='information_url',
            field=models.URLField(
                blank=True,
                help_text='URL for information regarding the document',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='location_info',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Ex: John Alexander Papers, Series 1: Correspondence, 1831-1848, Folder 1',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='editors',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewers',
            field=models.CharField(
                blank=True, default='', max_length=200, verbose_name='interviewers'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='editors',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='aliases',
            field=models.CharField(
                blank=True, default='', max_length=100, verbose_name='aliases'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                paragraphed=True,
                processed=True,
                processor=core.fields.html_field.process,
                verbose_name='description',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(
                blank=True, default='', max_length=100, unique=True, verbose_name='name'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(
                blank=True,
                default='',
                help_text='e.g., "L. Tom Perry Special Collections"',
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.CharField(
                blank=True,
                default='',
                help_text='e.g., "Harold B. Lee Library, Brigham Young University"',
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='attributee_html',
            field=models.CharField(
                blank=True, default='', max_length=300, verbose_name='attributee HTML'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='attributee_string',
            field=models.CharField(
                blank=True, default='', max_length=100, verbose_name='attributee string'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='containment_html',
            field=models.TextField(
                blank=True, default='', verbose_name='containment HTML'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='content',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                help_text='Enter the content of the source (with ellipses as needed).',
                paragraphed=None,
                processed=True,
                processor=core.fields.html_field.process,
                verbose_name='content',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                paragraphed=True,
                processed=True,
                processor=core.fields.html_field.process,
                verbose_name='description',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                blank=True,
                default='',
                editable=True,
                populate_from='get_slug',
                unique=True,
                verbose_name='slug',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(
                blank=True, default='', max_length=250, verbose_name='title'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speech',
            name='audience',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webpage',
            name='editors',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='aliases',
            field=models.CharField(
                blank=True, default='', max_length=100, verbose_name='aliases'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='description',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                paragraphed=True,
                processed=True,
                processor=core.fields.html_field.process,
                verbose_name='description',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(
                blank=True, default='', max_length=100, unique=True, verbose_name='name'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='owner',
            field=models.CharField(
                blank=True, default='', max_length=80, verbose_name='owner'
            ),
            preserve_default=False,
        ),
    ]
