# Generated by Django 3.1.11 on 2021-05-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_source_date_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='website_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
