# Generated by Django 3.1.9 on 2021-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20210428_2009'),
        ('sources', '0008_auto_20210514_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='new_tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='source_set',
                to='topics.Topic',
                verbose_name='citations',
            ),
        ),
    ]
