# Generated by Django 3.1.4 on 2020-12-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_auto_20201205_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='computations',
        ),
        migrations.AlterField(
            model_name='citation',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sourceattribution',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sourcecontainment',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
