# Generated by Django 3.1.11 on 2021-06-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_auto_20210531_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='owner',
            field=models.CharField(blank=True, max_length=100, verbose_name='owner'),
        ),
    ]
