# Generated by Django 3.1.13 on 2021-08-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_auto_20210821_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicrelation',
            name='position',
        ),
    ]
