# Generated by Django 3.1.11 on 2021-06-02 17:55

import django.db.models.deletion
from django.db import migrations, models

import apps.sources.models.sources.speech


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0024_auto_20210602_1755'),
        ('sources', '0010_auto_20210601_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='original',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='versions',
                to='sources.source',
                verbose_name='original',
            ),
        ),
        migrations.AddField(
            model_name='speech',
            name='utterance',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='speech',
                to='propositions.polymorphicproposition',
                validators=[apps.sources.models.sources.speech.SpeechTypeValidator],
            ),
        ),
    ]
