# Generated by Django 3.1.13 on 2021-08-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_remove_topicrelation_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='tags',
        ),
    ]
