# Generated by Django 3.1.11 on 2021-06-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_auto_20210602_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='variant_type',
            field=models.PositiveSmallIntegerField(
                db_index=True, default=0, verbose_name='variant type'
            ),
        ),
    ]
