# Generated by Django 3.1.9 on 2021-05-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_citation_citation_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='citation_phrase',
            field=models.CharField(
                blank=True,
                choices=[
                    (None, '-------'),
                    ('quoted in', 'quoted in'),
                    ('cited in', 'cited in'),
                    ('partially reproduced in', 'partially reproduced in'),
                ],
                default=None,
                max_length=25,
                null=True,
            ),
        ),
    ]
