# Generated by Django 3.1.11 on 2021-06-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_source_variant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='variant_type',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Original'), (1, 'Translation'), (2, 'Transcription')],
                db_index=True,
                default=0,
                verbose_name='variant type',
            ),
        ),
        migrations.AlterField(
            model_name='sourcecontainment',
            name='phrase',
            field=models.CharField(
                blank=True,
                choices=[
                    (None, '-------'),
                    ('archived', 'archived in'),
                    ('cited', 'cited in'),
                    ('copy', 'copy in'),
                    ('included', 'as included in'),
                    ('quoted', 'quoted in'),
                    ('recorded', 'recorded in'),
                    ('reproduced', 'reproduced in'),
                    ('transcribed', 'transcribed in'),
                ],
                default='',
                max_length=12,
            ),
        ),
    ]
