# Generated by Django 3.1.11 on 2021-06-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0013_auto_20210603_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='date_string',
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=100,
                null=True,
                verbose_name='date string',
            ),
        ),
    ]
