# Generated by Django 3.1.7 on 2021-03-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0014_auto_20210130_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerange',
            name='citation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sources.citation', verbose_name='citation'),
        ),
    ]
