# Generated by Django 3.1.7 on 2021-04-06 02:06

from django.db import migrations

import core.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0015_auto_20210308_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='pages2',
            field=core.fields.json_field.JSONField(default=dict),
        ),
    ]
