# Generated by Django 3.1.9 on 2021-05-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0016_auto_20210518_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='related',
        ),
    ]
