# Generated by Django 3.1.7 on 2021-04-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0016_citation_pages2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageRange',
        ),
    ]
