# Generated by Django 3.1.7 on 2021-04-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_delete_pagerange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='pages2',
            new_name='pages',
        ),
    ]
