# Generated by Django 3.1.9 on 2021-05-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_remove_source_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='new_tags',
            new_name='tags',
        ),
    ]
