# Generated by Django 3.2.7 on 2021-10-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_auto_20211006_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
