# Generated by Django 3.1.9 on 2021-05-19 19:17

from django.db import migrations

import apps.dates.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0019_auto_20210519_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='end_date',
            field=apps.dates.fields.HistoricDateTimeField(
                blank=True, null=True, verbose_name='end date'
            ),
        ),
    ]
