# Generated by Django 3.1.8 on 2021-04-10 07:23

from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0019_auto_20210410_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Affidavit',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Correspondence',
        ),
        migrations.DeleteModel(
            name='Discourse',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentSource',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Essay',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
        migrations.DeleteModel(
            name='Memorandum',
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionSource',
        ),
        migrations.DeleteModel(
            name='Sermon',
        ),
        migrations.DeleteModel(
            name='SourceWithPageNumbers',
        ),
        migrations.DeleteModel(
            name='Speech',
        ),
        migrations.DeleteModel(
            name='SpokenSource',
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
        migrations.DeleteModel(
            name='TextualSource',
        ),
        migrations.DeleteModel(
            name='WebPage',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.AlterModelOptions(
            name='polymorphicsource',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='source',
            name='original_edition',
        ),
        migrations.RemoveField(
            model_name='source',
            name='original_publication_date',
        ),
        migrations.RemoveField(
            model_name='source',
            name='related',
        ),
        migrations.AddField(
            model_name='polymorphicsource',
            name='related',
            field=gm2m.fields.GM2MField('quotes.Quote', 'occurrences.Occurrence', blank=True, related_name='sources', through='sources.Citation', through_fields=['polymorphic_source', 'content_object', 'content_type', 'object_id']),
        ),
        migrations.AlterField(
            model_name='collection',
            name='repository',
            field=models.ForeignKey(help_text='the library or institution housing the collection', on_delete=django.db.models.deletion.CASCADE, to='sources.repository'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('sources.journal', 'journal'), ('sources.magazine', 'magazine'), ('sources.newspaper', 'newspaper')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('sources.videosource', 'video source'), ('sources.documentary', 'documentary')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='website2',
            name='owner',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='owner'),
        ),
    ]
