# Generated by Django 3.1.8 on 2021-04-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0019_auto_20210410_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='polymorphicsource',
            name='attributee_html',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
