# Generated by Django 3.1.8 on 2021-04-13 22:15

import gm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0020_polymorphicsource_attributee_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['position', 'old_source']},
        ),
        migrations.RenameField(
            model_name='citation',
            old_name='source',
            new_name='old_source',
        ),
        migrations.AlterField(
            model_name='source',
            name='related',
            field=gm2m.fields.GM2MField(
                'quotes.Quote',
                'occurrences.Occurrence',
                blank=True,
                related_name='sources',
                through='sources.Citation',
                through_fields=[
                    'old_source',
                    'content_object',
                    'content_type',
                    'object_id',
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together={('old_source', 'content_type', 'object_id', 'position')},
        ),
    ]
