# Generated by Django 3.1.9 on 2021-05-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0020_source_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='_cached_tags',
        ),
    ]
