# Generated by Django 3.1.8 on 2021-04-10 07:23

import django.db.models.deletion
import gm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0019_auto_20210410_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Affidavit',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Correspondence',
        ),
        migrations.DeleteModel(
            name='Discourse',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentSource',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Essay',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
        migrations.DeleteModel(
            name='Memorandum',
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionSource',
        ),
        migrations.DeleteModel(
            name='Sermon',
        ),
        migrations.DeleteModel(
            name='SourceWithPageNumbers',
        ),
        migrations.DeleteModel(
            name='Speech',
        ),
        migrations.DeleteModel(
            name='SpokenSource',
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
        migrations.DeleteModel(
            name='TextualSource',
        ),
        migrations.DeleteModel(
            name='WebPage',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.AlterModelOptions(
            name='polymorphicsource',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='polymorphicsource',
            name='related',
            field=gm2m.fields.GM2MField(
                'quotes.Quote',
                'occurrences.Occurrence',
                blank=True,
                related_name='sources',
                through='sources.Citation',
                through_fields=[
                    'polymorphic_source',
                    'content_object',
                    'content_type',
                    'object_id',
                ],
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='repository',
            field=models.ForeignKey(
                help_text='the library or institution housing the collection',
                on_delete=django.db.models.deletion.CASCADE,
                to='sources.repository',
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(
                choices=[
                    ('sources.journal', 'journal'),
                    ('sources.magazine', 'magazine'),
                    ('sources.newspaper', 'newspaper'),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='website2',
            name='owner',
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name='owner'
            ),
        ),
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['position', 'polymorphic_source']},
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together={
                ('polymorphic_source', 'content_type', 'object_id', 'position')
            },
        ),
        migrations.RemoveField(
            model_name='citation',
            name='source',
        ),
        migrations.DeleteModel(
            name='Documentary',
        ),
        migrations.DeleteModel(
            name='VideoSource',
        ),
        migrations.AlterModelOptions(
            name='sourcecontainment',
            options={'ordering': ['position', 'polymorphic_source']},
        ),
        migrations.RemoveField(
            model_name='sourceattribution',
            name='source',
        ),
        migrations.RemoveField(
            model_name='sourcecontainment',
            name='container',
        ),
        migrations.RemoveField(
            model_name='sourcecontainment',
            name='source',
        ),
        migrations.AddField(
            model_name='polymorphicsource',
            name='containers',
            field=models.ManyToManyField(
                blank=True,
                related_name='contained_sources',
                through='sources.SourceContainment',
                to='sources.PolymorphicSource',
            ),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AlterModelOptions(
            name='sourcecontainment',
            options={'ordering': ['position', 'source']},
        ),
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='polymorphic_container',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='polymorphic_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='sourceattribution',
            old_name='polymorphic_source',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='polymorphicsource',
            name='attributees',
            field=models.ManyToManyField(
                blank=True,
                related_name='attributed_sources',
                through='sources.SourceAttribution',
                to='entities.Entity',
            ),
        ),
        migrations.AlterField(
            model_name='polymorphicsource',
            name='file',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sources',
                to='sources.sourcefile',
                verbose_name='file',
            ),
        ),
        migrations.AlterField(
            model_name='polymorphicsource',
            name='related',
            field=gm2m.fields.GM2MField(
                'quotes.Quote',
                'occurrences.Occurrence',
                blank=True,
                related_name='sources',
                through='sources.Citation',
                through_fields=[
                    'source',
                    'content_object',
                    'content_type',
                    'object_id',
                ],
            ),
        ),
        migrations.RenameField(
            model_name='citation',
            old_name='polymorphic_source',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='citations',
                to='sources.polymorphicsource',
            ),
        ),
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['position', 'source']},
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together={('source', 'content_type', 'object_id', 'position')},
        ),
        migrations.RenameModel('PolymorphicAffidavit', 'Affidavit'),
        migrations.RenameModel('PolymorphicArticle', 'Article'),
        migrations.RenameModel('PolymorphicCorrespondence', 'Correspondence'),
        migrations.RenameModel('PolymorphicDocument', 'Document'),
        migrations.RenameModel('PolymorphicFilm', 'Film'),
        migrations.RenameModel('PolymorphicInterview', 'Interview'),
        migrations.RenameModel('PolymorphicJournalEntry', 'JournalEntry'),
        migrations.RenameModel('PolymorphicPiece', 'Piece'),
        migrations.RenameModel('PolymorphicSection', 'Section'),
        migrations.RenameModel('PolymorphicSpeech', 'Speech'),
        migrations.RenameModel('PolymorphicWebPage', 'WebPage'),
        migrations.AlterField(
            model_name='affidavit',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='affidavit',
                to='sources.collection',
            ),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='correspondence',
                to='sources.collection',
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='document',
                to='sources.collection',
            ),
        ),
        migrations.RenameModel(
            old_name='Website2',
            new_name='Website',
        ),
        migrations.RenameField(model_name='section', old_name='book', new_name='work'),
        migrations.RenameModel('PolymorphicBook', 'Book'),
    ]
