# Generated by Django 3.1.8 on 2021-04-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0020_auto_20210410_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['position', 'polymorphic_source']},
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together={
                ('polymorphic_source', 'content_type', 'object_id', 'position')
            },
        ),
        migrations.RemoveField(
            model_name='citation',
            name='source',
        ),
    ]
