# Generated by Django 3.1.8 on 2021-04-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0021_auto_20210410_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='attributees',
        ),
        migrations.RemoveField(
            model_name='source',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='source',
            name='containers',
        ),
        migrations.RemoveField(
            model_name='source',
            name='db_file',
        ),
        migrations.RemoveField(
            model_name='source',
            name='location',
        ),
        migrations.RemoveField(
            model_name='source',
            name='publication',
        ),
        migrations.DeleteModel(
            name='Documentary',
        ),
        migrations.DeleteModel(
            name='VideoSource',
        ),
        migrations.AlterModelOptions(
            name='sourcecontainment',
            options={'ordering': ['position', 'polymorphic_source']},
        ),
        migrations.RemoveField(
            model_name='polymorphicsource',
            name='attributee_string',
        ),
        migrations.RemoveField(
            model_name='sourceattribution',
            name='source',
        ),
        migrations.RemoveField(
            model_name='sourcecontainment',
            name='container',
        ),
        migrations.RemoveField(
            model_name='sourcecontainment',
            name='source',
        ),
        migrations.AddField(
            model_name='polymorphicsource',
            name='containers',
            field=models.ManyToManyField(
                blank=True,
                related_name='contained_sources',
                through='sources.SourceContainment',
                to='sources.PolymorphicSource',
            ),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
