# Generated by Django 3.1.9 on 2021-05-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0021_remove_source__cached_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citation',
        ),
    ]
