# Generated by Django 3.1.8 on 2021-04-14 04:02

import gm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0022_auto_20210413_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='related',
            field=gm2m.fields.GM2MField(
                'quotes.Quote',
                'occurrences.Occurrence',
                blank=True,
                related_name='old_sources',
                through='sources.Citation',
                through_fields=[
                    'old_source',
                    'content_object',
                    'content_type',
                    'object_id',
                ],
            ),
        ),
    ]
