# Generated by Django 3.1.8 on 2021-04-11 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0022_auto_20210410_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcecontainment',
            options={'ordering': ['position', 'source']},
        ),
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='polymorphic_container',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='polymorphic_source',
            new_name='source',
        ),
    ]
