# Generated by Django 3.1.8 on 2021-04-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0022_auto_20210413_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Affidavit',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Correspondence',
        ),
        migrations.DeleteModel(
            name='Discourse',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentSource',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Essay',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
        migrations.DeleteModel(
            name='Memorandum',
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionSource',
        ),
        migrations.DeleteModel(
            name='Sermon',
        ),
        migrations.DeleteModel(
            name='SourceWithPageNumbers',
        ),
        migrations.DeleteModel(
            name='Speech',
        ),
        migrations.DeleteModel(
            name='SpokenSource',
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
        migrations.DeleteModel(
            name='TextualSource',
        ),
        migrations.DeleteModel(
            name='WebPage',
        ),
        migrations.DeleteModel(
            name='Documentary',
        ),
        migrations.DeleteModel(
            name='VideoSource',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(
                choices=[
                    ('sources.journal', 'journal'),
                    ('sources.magazine', 'magazine'),
                    ('sources.newspaper', 'newspaper'),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='website2',
            name='owner',
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name='owner'
            ),
        ),
        migrations.RenameModel(
            old_name='Website2',
            new_name='Website',
        ),
        migrations.RenameModel('PolymorphicAffidavit', 'Affidavit'),
        migrations.RenameModel('PolymorphicArticle', 'Article'),
        migrations.RenameModel('PolymorphicCorrespondence', 'Correspondence'),
        migrations.RenameModel('PolymorphicDocument', 'Document'),
        migrations.RenameModel('PolymorphicFilm', 'Film'),
        migrations.RenameModel('PolymorphicInterview', 'Interview'),
        migrations.RenameModel('PolymorphicJournalEntry', 'JournalEntry'),
        migrations.RenameModel('PolymorphicPiece', 'Piece'),
        migrations.RenameModel('PolymorphicSection', 'Section'),
        migrations.RenameModel('PolymorphicSpeech', 'Speech'),
        migrations.RenameModel('PolymorphicWebPage', 'WebPage'),
        migrations.RenameField(model_name='section', old_name='book', new_name='work'),
        migrations.RenameModel('PolymorphicBook', 'Book'),
    ]
