# Generated by Django 3.1.8 on 2021-04-14 01:11

import django.db.models.deletion
import gm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20210204_0619'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0023_auto_20210414_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polymorphicsource',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='sourceattribution',
            old_name='polymorphic_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='polymorphic_container',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='polymorphic_source',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='citation',
            name='old_source',
        ),
        migrations.RemoveField(
            model_name='sourceattribution',
            name='old_source',
        ),
        migrations.RemoveField(
            model_name='sourcecontainment',
            name='old_container',
        ),
        migrations.RemoveField(
            model_name='sourcecontainment',
            name='old_source',
        ),
        migrations.AddField(
            model_name='polymorphicsource',
            name='containers',
            field=models.ManyToManyField(
                blank=True,
                related_name='contained_sources',
                through='sources.SourceContainment',
                to='sources.PolymorphicSource',
            ),
        ),
        migrations.AddField(
            model_name='polymorphicsource',
            name='related',
            field=gm2m.fields.GM2MField(
                'quotes.Quote',
                'occurrences.Occurrence',
                blank=True,
                related_name='sources',
                through='sources.Citation',
                through_fields=[
                    'source',
                    'content_object',
                    'content_type',
                    'object_id',
                ],
            ),
        ),
        migrations.AlterField(
            model_name='affidavit',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='affidavit',
                to='sources.collection',
            ),
        ),
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='citations',
                to='sources.polymorphicsource',
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='repository',
            field=models.ForeignKey(
                help_text='the library or institution housing the collection',
                on_delete=django.db.models.deletion.CASCADE,
                to='sources.repository',
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='correspondence',
                to='sources.collection',
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='document',
                to='sources.collection',
            ),
        ),
        migrations.AlterField(
            model_name='polymorphicsource',
            name='attributees',
            field=models.ManyToManyField(
                related_name='attributed_sources',
                through='sources.SourceAttribution',
                to='entities.Entity',
            ),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
