# Generated by Django 3.1.8 on 2021-04-14 04:07

import gm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0023_auto_20210414_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='polymorphicsource',
            name='related',
            field=gm2m.fields.GM2MField(
                'quotes.Quote',
                'occurrences.Occurrence',
                blank=True,
                related_name='sources',
                through='sources.Citation',
                through_fields=[
                    'source',
                    'content_object',
                    'content_type',
                    'object_id',
                ],
            ),
        ),
    ]
