# Generated by Django 3.1.8 on 2021-04-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0024_auto_20210414_0111'),
    ]

    operations = []
