# Generated by Django 3.1.8 on 2021-04-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0024_polymorphicsource_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='polymorphicsource',
            name='containers',
            field=models.ManyToManyField(
                blank=True,
                related_name='polymorphic_contained_sources',
                through='sources.SourceContainment',
                to='sources.PolymorphicSource',
            ),
        ),
    ]
