# Generated by Django 3.1.8 on 2021-04-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0024_auto_20210411_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='sources.polymorphicsource'),
        ),
    ]
