# Generated by Django 3.1.8 on 2021-04-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0025_polymorphicsource_containers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcecontainment',
            options={'ordering': ['position', 'polymorphic_source']},
        ),
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='container',
            new_name='old_container',
        ),
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='source',
            new_name='old_source',
        ),
    ]
