# Generated by Django 3.1.8 on 2021-04-11 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0025_auto_20210411_0331'),
    ]

    operations = [
        migrations.RenameModel('PolymorphicAffidavit', 'Affidavit'),
        migrations.RenameModel('PolymorphicArticle', 'Article'),
        migrations.RenameModel('PolymorphicCorrespondence', 'Correspondence'),
        migrations.RenameModel('PolymorphicDocument', 'Document'),
        migrations.RenameModel('PolymorphicFilm', 'Film'),
        migrations.RenameModel('PolymorphicInterview', 'Interview'),
        migrations.RenameModel('PolymorphicJournalEntry', 'JournalEntry'),
        migrations.RenameModel('PolymorphicPiece', 'Piece'),
        migrations.RenameModel('PolymorphicSection', 'Section'),
        migrations.RenameModel('PolymorphicSpeech', 'Speech'),
        migrations.RenameModel('PolymorphicWebPage', 'WebPage'),
        migrations.AlterField(
            model_name='affidavit',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='affidavit',
                to='sources.collection',
            ),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='correspondence',
                to='sources.collection',
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='document',
                to='sources.collection',
            ),
        ),
    ]
