# Generated by Django 3.1.8 on 2021-04-11 04:15

import django.db.models.deletion
from django.db import migrations, models

import modularhistory.fields.historic_datetime_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0026_auto_20210411_0335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website2',
            new_name='Website',
        ),
        migrations.RenameField(model_name='section', old_name='book', new_name='work'),
        migrations.RenameModel('PolymorphicBook', 'Book'),
    ]
