# Generated by Django 3.1.8 on 2021-04-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0027_auto_20210414_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceattribution',
            old_name='polymorphic_source',
            new_name='source',
        ),
    ]
