# Generated by Django 3.1.8 on 2021-04-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0028_auto_20210414_0422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcecontainment',
            options={'ordering': ['position', 'source']},
        ),
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='polymorphic_container',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='polymorphic_source',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='source',
            name='containers',
            field=models.ManyToManyField(
                blank=True,
                related_name='old_contained_sources',
                through='sources.SourceContainment',
                to='sources.Source',
            ),
        ),
    ]
