# Generated by Django 3.1.8 on 2021-04-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20210204_0619'),
        ('places', '0002_auto_20201206_1823'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0029_auto_20210414_0433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolymorphicFilm',
            new_name='Film',
        ),
    ]
