# Generated by Django 3.1.8 on 2021-04-14 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0030_auto_20210414_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='old_source',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='citations',
                to='sources.source',
            ),
        ),
        migrations.AlterField(
            model_name='sourceattribution',
            name='old_source',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attributions',
                to='sources.source',
                verbose_name='source',
            ),
        ),
        migrations.AlterField(
            model_name='sourcecontainment',
            name='old_container',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='container_containments',
                to='sources.source',
            ),
        ),
        migrations.AlterField(
            model_name='sourcecontainment',
            name='old_source',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='source_containments',
                to='sources.source',
            ),
        ),
    ]
