# Generated by Django 3.1.8 on 2021-04-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20210204_0619'),
        ('sources', '0032_auto_20210414_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polymorphicsource',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='polymorphicsource',
            name='attributees',
            field=models.ManyToManyField(
                related_name='attributed_sources',
                through='sources.SourceAttribution',
                to='entities.Entity',
            ),
        ),
        migrations.AlterField(
            model_name='polymorphicsource',
            name='containers',
            field=models.ManyToManyField(
                blank=True,
                related_name='contained_sources',
                through='sources.SourceContainment',
                to='sources.PolymorphicSource',
            ),
        ),
    ]
