# Generated by Django 3.1.8 on 2021-04-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0033_auto_20210414_0545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(
                choices=[
                    ('sources.journal', 'journal'),
                    ('sources.magazine', 'magazine'),
                    ('sources.newspaper', 'newspaper'),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
