# Generated by Django 3.1.8 on 2021-04-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0034_auto_20210414_0549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website2',
            new_name='Website',
        ),
    ]
