# Generated by Django 3.1.8 on 2021-04-14 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0035_auto_20210414_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='old_source',
        ),
        migrations.RemoveField(
            model_name='source',
            name='related',
        ),
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='citations',
                to='sources.polymorphicsource',
            ),
        ),
    ]
