# Generated by Django 3.1.8 on 2021-04-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0036_auto_20210414_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='containers',
        ),
        migrations.RemoveField(
            model_name='sourcecontainment',
            name='old_container',
        ),
        migrations.RemoveField(
            model_name='sourcecontainment',
            name='old_source',
        ),
    ]
