# Generated by Django 3.1.8 on 2021-04-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0037_auto_20210414_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='attributees',
        ),
        migrations.RemoveField(
            model_name='sourceattribution',
            name='old_source',
        ),
    ]
