# Generated by Django 3.1.8 on 2021-04-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0039_auto_20210414_0710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentSource',
        ),
        migrations.DeleteModel(
            name='SourceWithPageNumbers',
        ),
        migrations.DeleteModel(
            name='TextualSource',
        ),
        migrations.RemoveField(
            model_name='source',
            name='original_edition',
        ),
        migrations.RemoveField(
            model_name='source',
            name='original_publication_date',
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[], db_index=True, max_length=255),
        ),
    ]
