# Generated by Django 3.1.8 on 2021-04-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0040_auto_20210414_0719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
    ]
