# Generated by Django 3.1.8 on 2021-04-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0041_delete_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polymorphicsection',
            old_name='book',
            new_name='work',
        ),
        migrations.AlterField(
            model_name='collection',
            name='repository',
            field=models.ForeignKey(
                help_text='the library or institution housing the collection',
                on_delete=django.db.models.deletion.CASCADE,
                to='sources.repository',
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polymorphicaffidavit',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='polymorphicaffidavit',
                to='sources.collection',
            ),
        ),
        migrations.AlterField(
            model_name='polymorphiccorrespondence',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='polymorphiccorrespondence',
                to='sources.collection',
            ),
        ),
        migrations.AlterField(
            model_name='polymorphicdocument',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='polymorphicdocument',
                to='sources.collection',
            ),
        ),
        migrations.AlterField(
            model_name='sourceattribution',
            name='source',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attributions',
                to='sources.polymorphicsource',
                verbose_name='source',
            ),
        ),
        migrations.AlterField(
            model_name='sourcecontainment',
            name='container',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='container_containments',
                to='sources.polymorphicsource',
            ),
        ),
        migrations.AlterField(
            model_name='sourcecontainment',
            name='source',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='source_containments',
                to='sources.polymorphicsource',
            ),
        ),
        migrations.AlterField(
            model_name='website',
            name='owner',
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name='owner'
            ),
        ),
    ]
