# Generated by Django 3.1.8 on 2021-04-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0042_auto_20210414_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymorphicinterview',
            name='interviewers',
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name='interviewers'
            ),
        ),
    ]
