# Generated by Django 3.1.8 on 2021-04-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20210204_0619'),
        ('sources', '0043_auto_20210414_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymorphicsource',
            name='attributees',
            field=models.ManyToManyField(
                blank=True,
                related_name='attributed_sources',
                through='sources.SourceAttribution',
                to='entities.Entity',
                verbose_name='attributees',
            ),
        ),
    ]
