# Generated by Django 3.1.12 on 2021-06-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0004_auto_20210604_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
