# Generated by Django 3.1.12 on 2021-06-10 18:12

import django.db.models.deletion
from django.db import migrations, models

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
        ('propositions', '0007_auto_20210610_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionInclusion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'collection',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='propositions_collectioninclusion_set',
                        to='collections.collection',
                    ),
                ),
                (
                    'content_object',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='collection_inclusions',
                        to='propositions.proposition',
                        verbose_name='proposition',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
