# Generated by Django 3.1.12 on 2021-06-25 00:21

import django.db.models.deletion
from django.db import migrations, models

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0009_auto_20210610_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'conflicting_proposition',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='outward_conflicts',
                        to='propositions.proposition',
                        verbose_name='proposition',
                    ),
                ),
                (
                    'proposition',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='inward_conflicts',
                        to='propositions.proposition',
                        verbose_name='proposition',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='proposition',
            name='conflicting_propositions',
            field=models.ManyToManyField(
                related_name='_proposition_conflicting_propositions_+',
                through='propositions.Conflict',
                to='propositions.Proposition',
                verbose_name='conflicting propositions',
            ),
        ),
    ]
