# Generated by Django 3.1.13 on 2021-08-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0026_auto_20210823_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conflict',
            old_name='proposition',
            new_name='content_object',
        ),
    ]
