# Generated by Django 3.1.4 on 2020-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attribute_name',
            field=models.CharField(
                help_text='The name of the attribute that maps to the interacted content',
                max_length=20,
                verbose_name='attribute name',
            ),
        ),
        migrations.AlterField(
            model_name='edit',
            name='attribute_name',
            field=models.CharField(
                help_text='The name of the attribute that maps to the interacted content',
                max_length=20,
                verbose_name='attribute name',
            ),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='attribute_name',
            field=models.CharField(
                help_text='The name of the attribute that maps to the interacted content',
                max_length=20,
                verbose_name='attribute name',
            ),
        ),
    ]
