# Generated by Django 3.1.12 on 2021-06-04 07:21

import django.db.models.deletion
from django.db import migrations, models

import core.fields.json_field


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('places.venue', 'venue'),
                            ('places.city', 'city'),
                            ('places.county', 'county'),
                            ('places.state', 'state'),
                            ('places.region', 'region'),
                            ('places.country', 'country'),
                            ('places.continent', 'continent'),
                        ],
                        db_index=True,
                        max_length=255,
                    ),
                ),
                (
                    'cache',
                    core.fields.json_field.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True, max_length=40, unique=True, verbose_name='name'
                    ),
                ),
                (
                    'preposition',
                    models.CharField(
                        choices=[('in', 'in'), ('at', 'at')], default='in', max_length=2
                    ),
                ),
                (
                    'location',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='places',
                        to='places.place',
                    ),
                ),
            ],
            options={
                'unique_together': {('name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[],
            options={
                'verbose_name_plural': 'Cities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[],
            options={
                'verbose_name_plural': 'Continents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[],
            options={
                'verbose_name_plural': 'Countries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='County',
            fields=[],
            options={
                'verbose_name_plural': 'Counties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[],
            options={
                'verbose_name_plural': 'Regions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[],
            options={
                'verbose_name_plural': 'States',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[],
            options={
                'proxy': True,
                'constraints': [
                    models.CheckConstraint(
                        check=models.Q(
                            location__type__in=[
                                'places.continent',
                                'places.region',
                                'places.country',
                                'places.state',
                                'places.county',
                                'places.city',
                            ]
                        ),
                        name='location_is_allowable',
                    )
                ],
                'indexes': [],
            },
            bases=('places.place',),
        ),
    ]
