# Generated by Django 3.1.4 on 2020-12-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='name'),
        ),
    ]
