# Generated by Django 3.1.13 on 2021-08-23 05:52

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=True,
                populate_from='get_slug',
                verbose_name='slug',
            ),
        ),
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.CharField(
                blank=True,
                help_text='This value can be used as a page header and/or title attribute.',
                max_length=120,
                verbose_name='title',
            ),
        ),
        migrations.AddField(
            model_name='place',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
