# Generated by Django 3.1.13 on 2021-08-23 06:03

import autoslug.fields
from django.db import migrations

from apps.places.models import Place


def forwards_func(apps, schema_editor):
    for p in Place.objects.all():
        p.slug = p.get_slug()
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210823_0552'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=True,
                populate_from='get_slug',
                unique=True,
                verbose_name='slug',
            ),
        ),
    ]
