# Generated by Django 3.1.9 on 2021-05-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20201206_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='computations',
            new_name='cache',
        ),
    ]
