# Generated by Django 3.2.7 on 2021-10-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210823_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
    ]
