# Generated by Django 3.1.11 on 2021-05-28 22:23

from django.db import migrations


def convert_nulls(apps, schema_editor):
    app = 'places'
    models = ('Place',)
    fields = ('name',)
    for model in models:
        Model = apps.get_model(app, model)
        for field in fields:
            if hasattr(Model, field):
                filter_param = {f'{field}__isnull': True}
                update_param = {field: ''}
                Model.objects.filter(**filter_param).update(**update_param)


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210519_1729'),
    ]

    operations = [
        migrations.RunPython(convert_nulls, migrations.RunPython.noop),
    ]
