# Generated by Django 3.2.8 on 2021-10-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDivision',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('places.place',),
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(
                choices=[
                    ('places.venue', 'venue'),
                    ('places.city', 'city'),
                    ('places.county', 'county'),
                    ('places.state', 'state'),
                    ('places.administrativedivision', 'administrative division'),
                    ('places.country', 'country'),
                    ('places.region', 'region'),
                    ('places.continent', 'continent'),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
