# Generated by Django 3.1.12 on 2021-06-04 07:21

import autoslug.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

import apps.dates.fields
import core.fields
import core.fields.array_field
import core.fields.html_field
import core.fields.json_field
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'start_date',
                    apps.dates.fields.HistoricDateTimeField(blank=True, null=True),
                ),
                ('end_date', apps.dates.fields.HistoricDateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorization',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'date',
                    apps.dates.fields.HistoricDateTimeField(
                        blank=True, null=True, verbose_name='date'
                    ),
                ),
                (
                    'end_date',
                    apps.dates.fields.HistoricDateTimeField(
                        blank=True, null=True, verbose_name='end date'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                (
                    'part_of_speech',
                    models.CharField(
                        choices=[
                            ('noun', 'noun'),
                            ('adj', 'adjective'),
                            ('any', 'noun / adjective'),
                        ],
                        default='adj',
                        max_length=9,
                        verbose_name='part of speech',
                    ),
                ),
                (
                    'aliases',
                    core.fields.array_field.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name='aliases',
                    ),
                ),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=1)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('entities.person', 'person'),
                            ('entities.deity', 'deity'),
                            ('entities.group', 'group'),
                            ('entities.organization', 'organization'),
                        ],
                        db_index=True,
                        max_length=255,
                    ),
                ),
                (
                    'cache',
                    core.fields.json_field.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    'slug',
                    autoslug.fields.AutoSlugField(
                        blank=True,
                        editable=True,
                        populate_from='get_slug',
                        unique=True,
                        verbose_name='slug',
                    ),
                ),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                (
                    'title',
                    models.CharField(
                        blank=True,
                        help_text='The title can be used for the detail page header and title tag, SERP result card header, etc. It should be a noun phrase!',
                        max_length=120,
                        verbose_name='title',
                    ),
                ),
                (
                    'hidden',
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text='Hide this item from search results.',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                (
                    'unabbreviated_name',
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    'aliases',
                    core.fields.array_field.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name='aliases',
                    ),
                ),
                (
                    'birth_date',
                    apps.dates.fields.HistoricDateTimeField(blank=True, null=True),
                ),
                (
                    'death_date',
                    apps.dates.fields.HistoricDateTimeField(blank=True, null=True),
                ),
                (
                    'description',
                    core.fields.HTMLField(
                        blank=True,
                        paragraphed=True,
                        processed=True,
                        processor=core.fields.html_field.process,
                    ),
                ),
                (
                    'reference_urls',
                    core.fields.json_field.JSONField(blank=True, default=dict),
                ),
            ],
            options={
                'verbose_name_plural': 'Entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntityIdea',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'verbose_name': 'entity idea',
            },
        ),
        migrations.CreateModel(
            name='EntityImage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                (
                    'description',
                    core.fields.HTMLField(
                        blank=True,
                        paragraphed=True,
                        processed=True,
                        processor=core.fields.html_field.process,
                    ),
                ),
            ],
            options={
                'verbose_name': 'idea',
            },
        ),
        migrations.CreateModel(
            name='ImageRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                (
                    'description',
                    core.fields.HTMLField(
                        blank=True,
                        paragraphed=None,
                        processed=True,
                        processor=core.fields.html_field.process,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='roles',
                        to='entities.entity',
                        verbose_name='organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'role',
            },
        ),
        migrations.CreateModel(
            name='RoleFulfillment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'start_date',
                    apps.dates.fields.HistoricDateTimeField(blank=True, null=True),
                ),
                ('end_date', apps.dates.fields.HistoricDateTimeField(blank=True, null=True)),
                (
                    'affiliation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='role_fulfillments',
                        to='entities.affiliation',
                        verbose_name='affiliation',
                    ),
                ),
                (
                    'role',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fulfillments',
                        to='entities.role',
                        verbose_name='role',
                    ),
                ),
            ],
            options={
                'verbose_name': 'role fulfillment',
            },
        ),
        migrations.CreateModel(
            name='QuoteRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    'content_object',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quote_relations',
                        to='entities.entity',
                        verbose_name='entity',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
