# Generated by Django 3.1.13 on 2021-08-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_auto_20210825_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
