# Generated by Django 3.1.3 on 2020-11-27 23:23

import uuid

import django.db.models.deletion
from django.db import migrations, models

import core.fields
import core.fields.html_field
import core.fields.json_field
from apps.dates.fields import HistoricDateTimeField


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'computations',
                    core.fields.json_field.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                ('date_is_circa', models.BooleanField(blank=True, default=False)),
                (
                    'verified',
                    models.BooleanField(default=False, verbose_name='verified'),
                ),
                (
                    'key',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    'hidden',
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Don't let this item appear in search results.",
                    ),
                ),
                (
                    'date',
                    HistoricDateTimeField(blank=True, null=True),
                ),
                (
                    'end_date',
                    HistoricDateTimeField(blank=True, null=True),
                ),
                (
                    'summary',
                    core.fields.HTMLField(
                        blank=True,
                        null=True,
                        paragraphed=False,
                        processor=core.fields.html_field.process,
                        verbose_name='Summary',
                    ),
                ),
                (
                    'description',
                    core.fields.HTMLField(
                        blank=True,
                        null=True,
                        paragraphed=True,
                        processor=core.fields.html_field.process,
                        verbose_name='Description',
                    ),
                ),
                (
                    'postscript',
                    core.fields.HTMLField(
                        blank=True,
                        help_text='Content to be displayed below all related data',
                        null=True,
                        paragraphed=True,
                        processor=core.fields.html_field.process,
                        verbose_name='Postscript',
                    ),
                ),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OccurrenceChain',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'description',
                    core.fields.HTMLField(
                        null=True,
                        paragraphed=True,
                        processor=core.fields.html_field.process,
                        unique=True,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccurrenceChainInclusion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceEntityInvolvement',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'importance',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'Primary'),
                            (2, 'Secondary'),
                            (3, 'Tertiary'),
                            (4, 'Quaternary'),
                            (5, 'Quinary'),
                            (6, 'Senary'),
                            (7, 'Septenary'),
                        ],
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceImage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_positioned', models.BooleanField(blank=True, default=False)),
                (
                    'position',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text='Set to 0 if the image is positioned manually.',
                        null=True,
                    ),
                ),
            ],
            options={
                'ordering': ['position', 'image'],
            },
        ),
        migrations.CreateModel(
            name='OccurrenceLocation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'importance',
                    models.IntegerField(
                        choices=[
                            (1, 'Primary'),
                            (2, 'Secondary'),
                            (3, 'Tertiary'),
                            (4, 'Quaternary'),
                            (5, 'Quinary'),
                            (6, 'Senary'),
                            (7, 'Septenary'),
                        ],
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceQuoteRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    'occurrence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='occurrence_quote_relations',
                        to='occurrences.occurrence',
                    ),
                ),
            ],
            options={
                'ordering': ['position', 'quote'],
            },
        ),
    ]
