# Generated by Django 3.1.9 on 2021-05-20 20:08

import django.db.models.deletion
from django.db import migrations, models

import core.fields
import core.fields.html_field


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='OccurrenceChain',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'description',
                    core.fields.HTMLField(
                        null=True,
                        paragraphed=True,
                        processed=True,
                        processor=core.fields.html_field.process,
                        unique=True,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccurrenceChainInclusion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'chain',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='occurrence_inclusions',
                        to='occurrences.occurrencechain',
                    ),
                ),
            ],
        ),
    ]
