# Generated by Django 3.1.9 on 2021-05-20 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occurrences', '0001_initial'),
        ('propositions', '0003_auto_20210520_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencechaininclusion',
            name='occurrence',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='chain_inclusions',
                to='propositions.occurrence',
            ),
        ),
        migrations.AddField(
            model_name='occurrencechain',
            name='parent_chain',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sub_chains',
                to='occurrences.occurrencechain',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='occurrencechaininclusion',
            unique_together={('chain', 'occurrence')},
        ),
    ]
