# Generated by Django 3.1.11 on 2021-05-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_auto_20210520_2048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occurrencechaininclusion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='occurrencechaininclusion',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='occurrencechaininclusion',
            name='occurrence',
        ),
        migrations.DeleteModel(
            name='OccurrenceChain',
        ),
        migrations.DeleteModel(
            name='OccurrenceChainInclusion',
        ),
    ]
