# Generated by Django 3.1.3 on 2020-11-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_auto_20201127_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='date_is_circa',
            field=models.BooleanField(blank=True, default=False, verbose_name='date is circa'),
        ),
    ]
