# Generated by Django 3.1.3 on 2020-12-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0009_auto_20201129_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='date_is_circa',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='whether the date is estimated/imprecise',
                verbose_name='date is circa',
            ),
        ),
    ]
