# Generated by Django 3.1.4 on 2020-12-06 20:36

import django.db.models.deletion
from django.db import migrations, models

import modularhistory.fields
import modularhistory.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_auto_20201206_0224'),
        ('places', '0002_auto_20201206_1823'),
        ('entities', '0007_auto_20201206_0224'),
        ('images', '0010_auto_20201203_2316'),
        ('occurrences', '0013_auto_20201206_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='occurrences', through='occurrences.OccurrenceImage', to='images.Image', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='involved_entities',
            field=models.ManyToManyField(blank=True, related_name='involved_occurrences', through='occurrences.OccurrenceEntityInvolvement', to='entities.Entity', verbose_name='involved entities'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='occurrences', through='occurrences.OccurrenceLocation', to='places.Place', verbose_name='locations'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='postscript',
            field=modularhistory.fields.HTMLField(blank=True, help_text='Content to be displayed below all related data', null=True, paragraphed=True, processor=modularhistory.fields.html_field.process, verbose_name='postscript'),
        ),
        migrations.AlterField(
            model_name='occurrenceimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrence_relations', to='images.image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='occurrenceimage',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_relations', to='occurrences.occurrence', verbose_name='occurrence'),
        ),
        migrations.AlterField(
            model_name='occurrencequoterelation',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_quote_relations', to='occurrences.occurrence', verbose_name='occurrence'),
        ),
        migrations.AlterField(
            model_name='occurrencequoterelation',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_occurrence_relations', to='quotes.quote', verbose_name='quote'),
        ),
    ]
