# Generated by Django 3.1.4 on 2020-12-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0014_auto_20201206_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='chains',
            field=models.ManyToManyField(
                related_name='occurrences',
                through='occurrences.OccurrenceChainInclusion',
                to='occurrences.OccurrenceChain',
                verbose_name='chains',
            ),
        ),
    ]
