# Generated by Django 3.1.4 on 2020-12-08 16:28

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0015_auto_20201208_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
