# Generated by Django 3.1.5 on 2021-01-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0016_occurrence_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['date']},
        ),
    ]
