# Generated by Django 3.1.8 on 2021-04-21 02:55

from django.db import migrations

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0018_occurrence_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='notes',
            field=core.fields.HTMLField(
                blank=True, null=True, paragraphed=True, processed=False, processor=None
            ),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='summary',
            field=core.fields.HTMLField(
                paragraphed=False,
                processed=False,
                processor=None,
                verbose_name='summary',
            ),
        ),
    ]
