# Generated by Django 3.1.8 on 2021-05-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0020_occurrence_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='key',
        ),
    ]
