# Generated by Django 3.1.9 on 2021-05-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0004_auto_20210508_2330'),
        ('occurrences', '0021_remove_occurrence_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='postulations',
            field=models.ManyToManyField(
                blank=True,
                related_name='occurrence_set',
                to='postulations.Postulation',
                verbose_name='postulations',
            ),
        ),
    ]
