# Generated by Django 3.1.9 on 2021-05-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0022_occurrence_postulations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('occurrences.occurrence',),
        ),
        migrations.CreateModel(
            name='Death',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('occurrences.occurrence',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('occurrences.occurrence',),
        ),
        migrations.CreateModel(
            name='Verbalization',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('occurrences.occurrence',),
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='postulations',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Occurrence (default)'),
                    (1, 'Birth'),
                    (2, 'Death'),
                    (3, 'Publication'),
                    (4, 'Verbalization'),
                ],
                default=0,
            ),
        ),
    ]
