# Generated by Django 3.1.9 on 2021-05-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0023_auto_20210514_0725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Birth',
        ),
        migrations.DeleteModel(
            name='Death',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Verbalization',
        ),
    ]
