# Generated by Django 3.1.9 on 2021-05-14 18:15

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models

import apps.dates.fields
import core.fields
import core.fields.html_field
import core.fields.json_field
import core.fields.sorted_m2m_field


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0002_auto_20210514_1815'),
        ('images', '0014_auto_20210505_2259'),
        ('entities', '0014_auto_20210514_1815'),
        ('places', '0002_auto_20201206_1823'),
        ('occurrences', '0023_auto_20210514_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOccurrence',
            fields=[
                (
                    'polymorphicproposition_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='propositions.polymorphicproposition',
                    ),
                ),
                (
                    'computations',
                    core.fields.json_field.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    'slug',
                    autoslug.fields.AutoSlugField(
                        blank=True,
                        editable=True,
                        null=True,
                        populate_from='get_slug',
                        unique=True,
                        verbose_name='slug',
                    ),
                ),
                (
                    'date_is_circa',
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text='whether the date is estimated/imprecise',
                        verbose_name='date is circa',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        blank=True,
                        help_text='The title can be used for the detail page header and title tag, SERP result card header, etc.',
                        max_length=120,
                        null=True,
                        verbose_name='title',
                    ),
                ),
                (
                    'hidden',
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text='Hide this item from search results.',
                    ),
                ),
                (
                    'type',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'Occurrence (default)'),
                            (1, 'Birth'),
                            (2, 'Death'),
                            (3, 'Publication'),
                            (4, 'Verbalization'),
                        ],
                        default=0,
                    ),
                ),
                (
                    'date',
                    apps.dates.fields.HistoricDateTimeField(
                        blank=True, null=True, verbose_name='date'
                    ),
                ),
                (
                    'end_date',
                    apps.dates.fields.HistoricDateTimeField(
                        blank=True, null=True, verbose_name='end date'
                    ),
                ),
                (
                    'postscript',
                    core.fields.HTMLField(
                        blank=True,
                        help_text='Content to be displayed below all related data',
                        null=True,
                        paragraphed=True,
                        processed=True,
                        processor=core.fields.html_field.process,
                        verbose_name='postscript',
                    ),
                ),
                (
                    'images',
                    core.fields.sorted_m2m_field.SortedManyToManyField(
                        blank=True,
                        help_text=None,
                        related_name='newoccurrence_set',
                        sort_value_field_name='position',
                        to='images.Image',
                        verbose_name='images',
                    ),
                ),
                (
                    'locations',
                    core.fields.sorted_m2m_field.SortedManyToManyField(
                        blank=True,
                        help_text=None,
                        related_name='newoccurrence_set',
                        sort_value_field_name='position',
                        to='places.Place',
                        verbose_name='locations',
                    ),
                ),
                (
                    'related_entities',
                    models.ManyToManyField(
                        blank=True,
                        related_name='newoccurrence_set',
                        to='entities.Entity',
                        verbose_name='related entities',
                    ),
                ),
            ],
            options={
                'ordering': ['date'],
            },
            bases=('propositions.polymorphicproposition', models.Model),
        ),
    ]
