# Generated by Django 3.1.9 on 2021-05-14 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0024_newoccurrence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Birth',
        ),
        migrations.DeleteModel(
            name='Death',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Verbalization',
        ),
    ]
