# Generated by Django 3.1.9 on 2021-05-16 05:43

from django.db import migrations, models

import apps.dates.fields
import core.fields
import core.fields.html_field
import core.fields.sorted_m2m_field


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0022_auto_20210515_2138'),
        ('images', '0015_auto_20210515_2138'),
        ('places', '0002_auto_20201206_1823'),
        ('sources', '0009_source_new_tags'),
        ('occurrences', '0025_auto_20210515_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='new_citations',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='sources',
            field=models.ManyToManyField(
                blank=True,
                related_name='occurrence_citations',
                to='sources.Source',
                verbose_name='sources',
            ),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='notes',
            field=core.fields.HTMLField(
                blank=True,
                null=True,
                paragraphed=True,
                processed=False,
                processor=None,
                verbose_name='note',
            ),
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_locations '
            'DROP CONSTRAINT IF EXISTS occurrences_newoccur_place_id_11b00607_fk_places_pl;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_locations '
            'DROP CONSTRAINT IF EXISTS occurrences_newoccur_newoccurrence_id_d6e29b13_fk_occurrenc;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_images '
            'DROP CONSTRAINT IF EXISTS occurrences_newoccur_newoccurrence_id_9b62488d_fk_occurrenc;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_related_entities '
            'DROP CONSTRAINT IF EXISTS occurrences_newoccur_newoccurrence_id_2725ae20_fk_occurrenc;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_images '
            'DROP CONSTRAINT IF EXISTS occurrences_newoccur_image_id_985bcef8_fk_images_im;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_related_entities '
            'DROP CONSTRAINT IF EXISTS occurrences_newoccur_newoccurrence_id_2725ae20_fk_occurrenc;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_related_entities '
            'DROP CONSTRAINT IF EXISTS occurrences_newoccur_entity_id_dc935a5a_fk_entities_;'
        ),
        migrations.RunSQL(
            'DROP INDEX IF EXISTS public.occurrences_newoccurrence_slug_226635e3_like;'
        ),
        migrations.RunSQL(
            'DROP INDEX IF EXISTS public.occurrences_newoccurrence_related_entities_entity_id_dc935a5a;'
        ),
        migrations.RunSQL(
            'DROP INDEX IF EXISTS public.occurrences_newoccurrence_locations_place_id_11b00607;'
        ),
        migrations.RunSQL(
            'DROP INDEX IF EXISTS public.occurrences_newoccurrence_locations_newoccurrence_id_d6e29b13;'
        ),
        migrations.RunSQL(
            'DROP INDEX IF EXISTS public.occurrences_newoccurrence_images_newoccurrence_id_9b62488d;'
        ),
        migrations.RunSQL(
            'DROP INDEX IF EXISTS public.occurrences_newoccurrence_images_image_id_985bcef8;'
        ),
        migrations.RunSQL(
            'DROP INDEX IF EXISTS public.occurrences_newoccurrence__newoccurrence_id_2725ae20;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence DROP CONSTRAINT IF EXISTS occurrences_newoccurrence_slug_key;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_related_entities DROP CONSTRAINT IF EXISTS occurrences_newoccurrence_related_entities_pkey;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence DROP CONSTRAINT IF EXISTS occurrences_newoccurrence_pkey;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_locations DROP CONSTRAINT IF EXISTS occurrences_newoccurrence_locations_pkey;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_images DROP CONSTRAINT IF EXISTS occurrences_newoccurrence_images_pkey;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_locations DROP CONSTRAINT IF EXISTS occurrences_newoccurrenc_newoccurrence_id_place_i_75c9a915_uniq;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_images DROP CONSTRAINT IF EXISTS occurrences_newoccurrenc_newoccurrence_id_image_i_438fb982_uniq;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.occurrences_newoccurrence_related_entities DROP CONSTRAINT IF EXISTS occurrences_newoccurrenc_newoccurrence_id_entity__977269dc_uniq;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS public.occurrences_newoccurrence_related_entities ALTER COLUMN id DROP DEFAULT;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS public.occurrences_newoccurrence_locations ALTER COLUMN id DROP DEFAULT;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS public.occurrences_newoccurrence_images ALTER COLUMN id DROP DEFAULT;'
        ),
        migrations.RunSQL(
            'DROP SEQUENCE IF EXISTS public.occurrences_newoccurrence_related_entities_id_seq;'
        ),
        migrations.RunSQL(
            'DROP TABLE IF EXISTS public.occurrences_newoccurrence_related_entities;'
        ),
        migrations.RunSQL(
            'DROP SEQUENCE IF EXISTS public.occurrences_newoccurrence_locations_id_seq;'
        ),
        migrations.RunSQL(
            'DROP TABLE IF EXISTS public.occurrences_newoccurrence_locations;'
        ),
        migrations.RunSQL(
            'DROP SEQUENCE IF EXISTS public.occurrences_newoccurrence_images_id_seq;'
        ),
        migrations.RunSQL(
            'DROP TABLE IF EXISTS public.occurrences_newoccurrence_images;'
        ),
        migrations.RunSQL('DROP TABLE IF EXISTS public.occurrences_newoccurrence;'),
        migrations.CreateModel(
            name='NewOccurrence',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'date_is_circa',
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text='whether the date is estimated/imprecise',
                        verbose_name='date is circa',
                    ),
                ),
                (
                    'type',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'Occurrence (default)'),
                            (1, 'Birth'),
                            (2, 'Death'),
                            (3, 'Publication'),
                            (4, 'Verbalization'),
                        ],
                        default=0,
                    ),
                ),
                (
                    'date',
                    apps.dates.fields.HistoricDateTimeField(
                        blank=True, null=True, verbose_name='date'
                    ),
                ),
                (
                    'end_date',
                    apps.dates.fields.HistoricDateTimeField(
                        blank=True, null=True, verbose_name='end date'
                    ),
                ),
                (
                    'postscript',
                    core.fields.HTMLField(
                        blank=True,
                        help_text='Content to be displayed below all related data',
                        null=True,
                        paragraphed=True,
                        processed=True,
                        processor=core.fields.html_field.process,
                        verbose_name='postscript',
                    ),
                ),
                (
                    'images',
                    core.fields.sorted_m2m_field.SortedManyToManyField(
                        blank=True,
                        help_text=None,
                        related_name='newoccurrence_set',
                        sort_value_field_name='position',
                        to='images.Image',
                        verbose_name='images',
                    ),
                ),
                (
                    'locations',
                    core.fields.sorted_m2m_field.SortedManyToManyField(
                        blank=True,
                        help_text=None,
                        related_name='newoccurrence_set',
                        sort_value_field_name='position',
                        to='places.Place',
                        verbose_name='locations',
                    ),
                ),
                (
                    'related_quotes',
                    core.fields.sorted_m2m_field.SortedManyToManyField(
                        blank=True,
                        help_text=None,
                        related_name='newoccurrence_set',
                        sort_value_field_name='position',
                        to='quotes.Quote',
                        verbose_name='images',
                    ),
                ),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
