# Generated by Django 3.1.9 on 2021-05-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0025_auto_20210514_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewOccurrence',
        ),
    ]
