# Generated by Django 3.1.9 on 2021-05-14 23:43

import django.db.models.deletion
from django.db import migrations, models

import apps.dates.fields
import core.fields
import core.fields.html_field
import core.fields.sorted_m2m_field


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_auto_20210505_2259'),
        ('propositions', '0004_auto_20210514_2329'),
        ('places', '0002_auto_20201206_1823'),
        ('occurrences', '0026_delete_newoccurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOccurrence',
            fields=[
                (
                    'proposition_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='propositions.proposition',
                    ),
                ),
                (
                    'date_is_circa',
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text='whether the date is estimated/imprecise',
                        verbose_name='date is circa',
                    ),
                ),
                (
                    'type',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'Occurrence (default)'),
                            (1, 'Birth'),
                            (2, 'Death'),
                            (3, 'Publication'),
                            (4, 'Verbalization'),
                        ],
                        default=0,
                    ),
                ),
                (
                    'date',
                    apps.dates.fields.HistoricDateTimeField(
                        blank=True, null=True, verbose_name='date'
                    ),
                ),
                (
                    'end_date',
                    apps.dates.fields.HistoricDateTimeField(
                        blank=True, null=True, verbose_name='end date'
                    ),
                ),
                (
                    'postscript',
                    core.fields.HTMLField(
                        blank=True,
                        help_text='Content to be displayed below all related data',
                        null=True,
                        paragraphed=True,
                        processed=True,
                        processor=core.fields.html_field.process,
                        verbose_name='postscript',
                    ),
                ),
                (
                    'images',
                    core.fields.sorted_m2m_field.SortedManyToManyField(
                        blank=True,
                        help_text=None,
                        related_name='newoccurrence_set',
                        sort_value_field_name='position',
                        to='images.Image',
                        verbose_name='images',
                    ),
                ),
                (
                    'locations',
                    core.fields.sorted_m2m_field.SortedManyToManyField(
                        blank=True,
                        help_text=None,
                        related_name='newoccurrence_set',
                        sort_value_field_name='position',
                        to='places.Place',
                        verbose_name='locations',
                    ),
                ),
            ],
            options={
                'ordering': ['date'],
            },
            bases=('propositions.proposition', models.Model),
        ),
        migrations.CreateModel(
            name='Birth',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('occurrences.newoccurrence',),
        ),
        migrations.CreateModel(
            name='Death',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('occurrences.newoccurrence',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('occurrences.newoccurrence',),
        ),
        migrations.CreateModel(
            name='Verbalization',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('occurrences.newoccurrence',),
        ),
    ]
