# Generated by Django 3.1.9 on 2021-05-18 16:24

from django.db import migrations

import core.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0029_auto_20210517_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='cached_tags',
            field=core.fields.json_field.JSONField(default=list, editable=False),
        ),
    ]
