# Generated by Django 3.1.9 on 2021-05-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0031_occurrence__cached_citations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='cached_tags',
            new_name='_cached_tags',
        ),
    ]
