# Generated by Django 3.1.9 on 2021-05-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0034_newoccurrence__cached_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newoccurrence',
            name='_cached_images',
        ),
    ]
