# Generated by Django 3.1.9 on 2021-05-20 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0031_remove_typedproposition__cached_images'),
        ('occurrences', '0035_remove_newoccurrence__cached_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newoccurrence',
            name='images',
        ),
        migrations.RemoveField(
            model_name='newoccurrence',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='newoccurrence',
            name='proposition_ptr',
        ),
        migrations.AlterField(
            model_name='occurrencechaininclusion',
            name='occurrence',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='chain_inclusions',
                to='propositions.occurrence',
            ),
        ),
    ]
