# Generated by Django 3.1.9 on 2021-05-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0036_auto_20210520_1807'),
        ('propositions', '0032_auto_20210520_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewOccurrence',
        ),
    ]
