# Generated by Django 3.1.12 on 2021-06-04 07:21

import django.db.models.deletion
from django.db import migrations, models

import apps.sources.models.model_with_sources
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('topics', '0001_initial'),
        ('quotes', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='sources',
            field=apps.sources.models.model_with_sources.SourcesField(
                blank=True,
                related_name='quotes',
                through='quotes.Citation',
                to='sources.Source',
                verbose_name='sources',
            ),
        ),
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(
                blank=True, related_name='quote_set', to='topics.Topic', verbose_name='tags'
            ),
        ),
        migrations.AddField(
            model_name='imagerelation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_image_relations',
                to='quotes.quote',
                verbose_name='quote',
            ),
        ),
        migrations.AddField(
            model_name='imagerelation',
            name='image',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_quotes_imagerelation_set',
                to='images.image',
            ),
        ),
        migrations.AddField(
            model_name='citation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='citations',
                to='quotes.quote',
                verbose_name='quote',
            ),
        ),
        migrations.AddField(
            model_name='citation',
            name='source',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quotes_citation_set',
                to='sources.source',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='quoteattribution',
            unique_together={('quote', 'attributee')},
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('date', 'bite')},
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.UniqueConstraint(
                fields=('source', 'content_object', 'position'),
                name='quotes_citation_unique_positions',
            ),
        ),
    ]
