# Generated by Django 3.1.9 on 2021-05-20 20:08

import django.db.models.deletion
from django.db import migrations, models

import apps.sources.models.model_with_sources
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('topics', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='sources',
            field=apps.sources.models.model_with_sources.SourcesField(
                blank=True,
                related_name='quotes',
                through='quotes.Citation',
                to='sources.Source',
                verbose_name='sources',
            ),
        ),
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='quote_set',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
        migrations.AddField(
            model_name='citation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='citations',
                to='quotes.quote',
                verbose_name='quote',
            ),
        ),
        migrations.AddField(
            model_name='citation',
            name='source',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quotes_citations',
                to='sources.source',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='quoteattribution',
            unique_together={('quote', 'attributee')},
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('date', 'bite')},
        ),
    ]
