# Generated by Django 3.1.11 on 2021-05-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20210520_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='version',
        ),
    ]
