# Generated by Django 3.1.12 on 2021-06-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20210610_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='imagerelation',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='quoteattribution',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='quoterelation',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
