# Generated by Django 3.1.13 on 2021-08-20 21:38

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20210627_2144'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='citation',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='imagerelation',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='quoteattribution',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='quoterelation',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='hidden',
        ),
        migrations.AddField(
            model_name='citation',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='imagerelation',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='quoteattribution',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='quoterelation',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(
                blank=True,
                help_text='This value can be used as a page header and/or title attribute.',
                max_length=120,
                verbose_name='title',
            ),
        ),
        migrations.DeleteModel(
            name='QuoteBite',
        ),
    ]
