# Generated by Django 3.1.4 on 2020-12-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20201205_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteattribution',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quoteimage',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quoterelation',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
