# Generated by Django 3.1.4 on 2020-12-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20201206_0224'),
        ('quotes', '0009_auto_20201206_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteattribution',
            name='attributee',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quote_attributions',
                to='entities.entity',
                verbose_name='attributee',
            ),
        ),
        migrations.AlterField(
            model_name='quoteattribution',
            name='quote',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attributions',
                to='quotes.quote',
                verbose_name='quote',
            ),
        ),
    ]
