# Generated by Django 3.1.11 on 2021-06-03 01:19

import django.db.models.deletion
from django.db import migrations, models

import apps.images.models.model_with_images
import core.fields.m2m_foreign_key


def convert_data(apps, schema_editor):
    Model = apps.get_model('quotes', 'Quote')
    for instance in Model.objects.all():
        for i in instance.images.all():
            instance._images.add(i)


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20210531_2013'),
        ('quotes', '0009_quote_date_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    'content_object',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='_image_relations',
                        to='quotes.quote',
                        verbose_name='quote',
                    ),
                ),
                (
                    'image',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='_quotes_imagerelation_set',
                        to='images.image',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='_images',
            field=apps.images.models.model_with_images.ImagesField(
                blank=True,
                related_name='quote_set',
                through='quotes.ImageRelation',
                to='images.Image',
                verbose_name='images',
            ),
        ),
        migrations.RunPython(convert_data, migrations.RunPython.noop),
    ]
