# Generated by Django 3.1.7 on 2021-04-05 02:28

from django.db import migrations

import modularhistory.fields
import modularhistory.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_auto_20210130_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=modularhistory.fields.HTMLField(
                blank=True,
                null=True,
                paragraphed=True,
                processor=modularhistory.fields.html_field.process,
            ),
        ),
    ]
