# Generated by Django 3.1.11 on 2021-06-03 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_remove_quote_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='_images',
            new_name='images',
        ),
    ]
