# Generated by Django 3.1.8 on 2021-04-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_entity_reference_urls'),
        ('quotes', '0014_quote_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='attributee_html',
            field=models.TextField(
                blank=True, editable=False, null=True, verbose_name='attributee HTML'
            ),
        ),
        migrations.AlterField(
            model_name='quote',
            name='attributees',
            field=models.ManyToManyField(
                blank=True,
                related_name='quotes',
                through='quotes.QuoteAttribution',
                to='entities.Entity',
                verbose_name='attributees',
            ),
        ),
    ]
