# Generated by Django 3.2.7 on 2021-10-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_auto_20210824_1528'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together=set(),
        ),
    ]
