# Generated by Django 3.1.8 on 2021-05-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_auto_20210430_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='key',
        ),
    ]
