# Generated by Django 3.2.8 on 2021-10-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_alter_quote_unique_together'),
        ('quotes', '0015_collectioninclusion'),
    ]

    operations = []
