# Generated by Django 3.1.9 on 2021-05-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_auto_20210514_1815'),
        ('quotes', '0020_quote_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='related_entities',
            field=models.ManyToManyField(
                blank=True,
                related_name='quote_set',
                to='entities.Entity',
                verbose_name='related entities',
            ),
        ),
    ]
