# Generated by Django 3.1.9 on 2021-05-15 21:38

import gm2m.fields
from django.db import migrations, models

import core.fields.sorted_m2m_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_auto_20210514_1815'),
        ('topics', '0003_auto_20210428_2009'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('quotes', '0021_auto_20210514_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='new_citations',
            field=core.fields.sorted_m2m_field.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name='quote_set',
                sort_value_field_name='position',
                to='sources.Source',
                verbose_name='citations',
            ),
        ),
        migrations.AddField(
            model_name='quote',
            name='new_tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='quote_set',
                to='topics.Topic',
                verbose_name='citations',
            ),
        ),
        migrations.AddField(
            model_name='quote',
            name='related_quotes',
            field=core.fields.sorted_m2m_field.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name='quote_set',
                sort_value_field_name='position',
                to='quotes.Quote',
                verbose_name='images',
            ),
        ),
        migrations.AddField(
            model_name='quotebite',
            name='new_tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='quotebite_set',
                to='topics.Topic',
                verbose_name='citations',
            ),
        ),
        migrations.AlterField(
            model_name='quote',
            name='related',
            field=gm2m.fields.GM2MField(
                'occurrences.Occurrence',
                'entities.Entity',
                'quotes.Quote',
                blank=True,
                related_name='_related_quotes',
                through='quotes.QuoteRelation',
                through_fields=['quote', 'content_object', 'content_type', 'object_id'],
            ),
        ),
    ]
