# Generated by Django 3.1.9 on 2021-05-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_auto_20210516_0543'),
        ('quotes', '0024_auto_20210516_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='sources',
            field=models.ManyToManyField(
                blank=True,
                related_name='quote_citations',
                through='quotes.QuoteCitation',
                to='sources.Source',
                verbose_name='sources',
            ),
        ),
    ]
