# Generated by Django 3.1.9 on 2021-05-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0026_auto_20210517_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotecitation',
            old_name='quote',
            new_name='content_object',
        ),
    ]
