# Generated by Django 3.1.9 on 2021-05-17 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0028_quotecitation_citation_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='related_quotes',
        ),
        migrations.AlterField(
            model_name='quotecitation',
            name='citation_phrase',
            field=models.CharField(
                blank=True,
                choices=[
                    (None, '-------'),
                    ('quoted in', 'quoted in'),
                    ('cited in', 'cited in'),
                    ('partially reproduced in', 'partially reproduced in'),
                ],
                default=None,
                max_length=25,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='AbstractQuoteRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'quote',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='abstractquoterelation_relations',
                        to='quotes.quote',
                    ),
                ),
            ],
        ),
    ]
