# Generated by Django 3.1.9 on 2021-05-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0029_auto_20210517_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='sources',
        ),
        migrations.DeleteModel(
            name='AbstractQuoteRelation',
        ),
    ]
