# Generated by Django 3.1.9 on 2021-05-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quotes', '0032_auto_20210517_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuoteRelation',
            new_name='GenericQuoteRelation',
        ),
    ]
