# Generated by Django 3.1.9 on 2021-05-17 19:05

import django.db.models.deletion
from django.db import migrations, models

import apps.quotes.models.model_with_related_quotes
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0033_auto_20210517_1852'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.quotes_genericquoterelation '
            'RENAME CONSTRAINT quotes_quoterelation_quote_id_9501ca1c_fk_quotes_quote_id '
            'to quotes_g_quoterelation_quote_id_9501ca1c_fk_quotes_quote_id;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.quotes_genericquoterelation '
            'RENAME CONSTRAINT quotes_quoterelation_content_type_id_ac741c8f_fk_django_co '
            'to quotes_g_quoterelation_content_type_id_ac741c8f_fk_django_co;'
        ),
        migrations.RunSQL(
            'ALTER INDEX IF EXISTS quotes_quoterelation_quote_id_9501ca1c '
            'RENAME TO quotes_g_quoterelation_quote_id_9501ca1c;'
        ),
        migrations.RunSQL(
            'ALTER INDEX IF EXISTS quotes_quoterelation_content_type_id_ac741c8f '
            'RENAME TO quotes_g_quoterelation_content_type_id_ac741c8f;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.quotes_genericquoterelation '
            'RENAME CONSTRAINT quotes_quoterelation_quote_id_content_type_id_e70ee52d_uniq '
            'to quotes_g_quoterelation_quote_id_content_type_id_e70ee52d_uniq;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.quotes_genericquoterelation '
            'RENAME CONSTRAINT quotes_quoterelation_pkey '
            'to quotes_g_quoterelation_pkey;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.quotes_genericquoterelation '
            'RENAME CONSTRAINT quotes_quoterelation_object_id_check '
            'to quotes_g_quoterelation_object_id_check;'
        ),
        migrations.RunSQL(
            'ALTER TABLE IF EXISTS ONLY public.quotes_genericquoterelation '
            'RENAME CONSTRAINT quotes_quoterelation_position_check '
            'to quotes_g_quoterelation_position_check;'
        ),
        migrations.CreateModel(
            name='QuoteRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'content_object',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quote_relations',
                        to='quotes.quote',
                    ),
                ),
                (
                    'quote',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quotes_quoterelations',
                        to='quotes.quote',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='related_quotes',
            field=apps.quotes.models.model_with_related_quotes.RelatedQuotesField(
                blank=True,
                related_name='quote_set',
                through='quotes.QuoteRelation',
                to='quotes.Quote',
                verbose_name='related quotes',
            ),
        ),
    ]
