# Generated by Django 3.1.9 on 2021-05-17 21:46

import django.db.models.deletion
from django.db import migrations

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0034_auto_20210517_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='citation_relations',
                to='quotes.quote',
            ),
        ),
        migrations.AlterField(
            model_name='quoterelation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quoterelation_relations',
                to='quotes.quote',
            ),
        ),
    ]
