# Generated by Django 3.1.9 on 2021-05-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0035_auto_20210517_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterelation',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
