# Generated by Django 3.1.9 on 2021-05-18 16:24

from django.db import migrations

import core.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0036_quoterelation_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='cached_tags',
            field=core.fields.json_field.JSONField(default=list, editable=False),
        ),
        migrations.AddField(
            model_name='quotebite',
            name='cached_tags',
            field=core.fields.json_field.JSONField(default=list, editable=False),
        ),
    ]
