# Generated by Django 3.1.9 on 2021-05-18 17:19

import django.db.models.deletion
from django.db import migrations

import core.fields.json_field
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0037_auto_20210518_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='_cached_citations',
            field=core.fields.json_field.JSONField(default=list, editable=False),
        ),
        migrations.AlterField(
            model_name='citation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='citations',
                to='quotes.quote',
            ),
        ),
    ]
