# Generated by Django 3.1.9 on 2021-05-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0038_auto_20210518_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='cached_tags',
            new_name='_cached_tags',
        ),
        migrations.RenameField(
            model_name='quotebite',
            old_name='cached_tags',
            new_name='_cached_tags',
        ),
    ]
