# Generated by Django 3.1.9 on 2021-05-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0039_auto_20210518_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='related',
        ),
    ]
