# Generated by Django 3.1.9 on 2021-05-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0041_quote__cached_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='new_tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='quotebite',
            old_name='new_tags',
            new_name='tags',
        ),
    ]
