# Generated by Django 3.1.9 on 2021-05-20 01:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0045_quote_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='_cached_tags',
        ),
        migrations.RemoveField(
            model_name='quotebite',
            name='_cached_tags',
        ),
        migrations.AddField(
            model_name='quotebite',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=True,
                null=True,
                populate_from='get_slug',
                unique=True,
                verbose_name='slug',
            ),
        ),
    ]
