# Generated by Django 3.1.9 on 2021-05-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0046_auto_20210520_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='_cached_citations',
        ),
    ]
