# Generated by Django 3.1.9 on 2021-05-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0047_remove_quote__cached_citations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='_cached_images',
        ),
    ]
