# Generated by Django 3.2.8 on 2021-10-31 00:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='thread',
            name='initial_post',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.post'
            ),
        ),
    ]
