# Generated by Django 3.0.4 on 2020-03-25 01:03

from django.db import migrations
import history.fields.historic_datetime_field


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='date',
            field=history.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='end_date',
            field=history.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True),
        ),
    ]
