# Generated by Django 3.0.1 on 2019-12-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('entities', '0001_initial'),
        ('topics', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('occurrences', '0002_auto_20191228_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytopicrelation',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_entity_relations', to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='entityimage',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='entityimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Image'),
        ),
        migrations.AddField(
            model_name='entity',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='entities', through='entities.EntityImage', to='images.Image'),
        ),
        migrations.AddField(
            model_name='entity',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_entities.entity_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='person',
            name='death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deceased_persons', to='occurrences.Death'),
        ),
        migrations.AddField(
            model_name='organization',
            name='founding',
            field=models.OneToOneField(blank=True, db_column='birth', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrences.Founding'),
        ),
    ]
