# Generated by Django 3.0.4 on 2020-03-25 01:10

from django.db import migrations
import modularhistory.fields.historic_datetime_field


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20200325_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='end_date',
        ),
        migrations.AddField(
            model_name='entityclassification',
            name='date',
            field=modularhistory.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityclassification',
            name='end_date',
            field=modularhistory.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True),
        ),
    ]
