# Generated by Django 3.0.1 on 2019-12-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('entities', '0002_auto_20191228_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityimage',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_images', to='entities.Entity'),
        ),
        migrations.AlterField(
            model_name='entityimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_entities', to='images.Image'),
        ),
    ]
