# Generated by Django 3.1.3 on 2020-11-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20201118_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='parent_organization',
        ),
    ]
