# Generated by Django 3.0.4 on 2020-03-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20200325_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
