# Generated by Django 3.0.4 on 2020-03-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_classification_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
