# Generated by Django 3.0.1 on 2019-12-30 01:00

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20191229_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='birth_date',
            field=history.fields.HistoricDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='death_date',
            field=history.fields.HistoricDateTimeField(blank=True, null=True),
        ),
    ]
