# Generated by Django 3.0.4 on 2020-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_entity_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'noun'), ('adjective', 'adjective')], default='adjective', max_length=9),
        ),
    ]
