# Generated by Django 3.0.1 on 2019-12-30 02:03

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20191230_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=history.fields.HTMLField(blank=True, null=True),
        ),
    ]
