# Generated by Django 3.0.4 on 2020-04-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_classification_part_of_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'noun'), ('adj', 'adjective'), ('any', 'noun / adjective')], default='adj', max_length=9),
        ),
    ]
