# Generated by Django 3.0.7 on 2020-09-02 03:57

from django.db import migrations, models
import django.db.models.deletion
import history.fields.array_field


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20200407_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityclassification',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_classifications', to='entities.Classification'),
        ),
        migrations.CreateModel(
            name='EntityClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('part_of_speech', models.CharField(choices=[('noun', 'noun'), ('adj', 'adjective'), ('any', 'noun / adjective')], default='adj', max_length=9)),
                ('aliases', history.fields.array_field.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='entities.EntityClass')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='entities', through='entities.EntityClassification', to='entities.EntityClass'),
        ),
        migrations.AddField(
            model_name='entityclassification',
            name='entity_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_classifications', to='entities.EntityClass'),
        ),
    ]
