# Generated by Django 3.0.7 on 2020-09-02 06:26

from django.db import migrations, models
import django.db.models.deletion
import modularhistory.fields.array_field
import modularhistory.fields.historic_datetime_field


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_auto_20200902_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', modularhistory.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True)),
                ('end_date', modularhistory.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('part_of_speech', models.CharField(choices=[('noun', 'noun'), ('adj', 'adjective'), ('any', 'noun / adjective')], default='adj', max_length=9)),
                ('aliases', modularhistory.fields.array_field.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='entities.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='entity',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='entityclassification',
            name='entity_class',
        ),
        migrations.DeleteModel(
            name='EntityClass',
        ),
        migrations.AddField(
            model_name='categorization',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorizations', to='entities.Category'),
        ),
        migrations.AddField(
            model_name='categorization',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorizations', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='entities', through='entities.Categorization', to='entities.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='categorization',
            unique_together={('entity', 'category')},
        ),
    ]
