# Generated by Django 3.0.7 on 2020-09-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20200902_0626'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entityclassification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='entityclassification',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='entityclassification',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='classifications',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.DeleteModel(
            name='EntityClassification',
        ),
    ]
