# Generated by Django 3.0.1 on 2020-01-02 20:07

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20200102_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='birth_date',
            field=history.fields.HistoricDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='death_date',
            field=history.fields.HistoricDateField(blank=True, null=True),
        ),
    ]
