# Generated by Django 3.0.1 on 2020-01-03 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_auto_20200102_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name', 'birth_date'], 'verbose_name_plural': 'Entities'},
        ),
    ]
