# Generated by Django 3.0.7 on 2020-09-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_auto_20200902_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Groups'},
        ),
    ]
