# Generated by Django 3.0.7 on 2020-09-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_auto_20200908_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='verbose_name',
            new_name='unabbreviated_name',
        ),
    ]
