# Generated by Django 3.0.10 on 2020-10-12 22:50

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_auto_20200909_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name_plural': 'categories'},
        ),
    ]
