# Generated by Django 3.0.1 on 2020-01-04 03:00

from django.db import migrations, models
import django.db.models.deletion
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_remove_image_verified'),
        ('entities', '0013_auto_20200103_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', history.fields.HTMLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='affiliations',
            field=models.ManyToManyField(blank=True, related_name='members', to='entities.Organization'),
        ),
        migrations.AlterField(
            model_name='entityimage',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_images', to='entities.Entity'),
        ),
        migrations.AlterField(
            model_name='entityimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_entities', to='images.Image'),
        ),
        migrations.CreateModel(
            name='OccupationEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', history.fields.HistoricDateField(blank=True, null=True)),
                ('end_date', history.fields.HistoricDateField(blank=True, null=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_engagements', to='entities.Occupation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_engagements', to='entities.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', history.fields.HistoricDateField(blank=True, null=True)),
                ('end_date', history.fields.HistoricDateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_affiliations', to='entities.Organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_affiliations', to='entities.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='occupations',
            field=models.ManyToManyField(blank=True, related_name='participants', to='entities.Occupation'),
        ),
    ]
