# Generated by Django 3.0.1 on 2020-01-04 03:45

from django.db import migrations, models
import django.db.models.deletion
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_auto_20200104_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', history.fields.HTMLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', history.fields.HTMLField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='entities.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='occupation',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='RoleFulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', history.fields.HistoricDateField(blank=True, null=True)),
                ('end_date', history.fields.HistoricDateField(blank=True, null=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_fulfillments', to='entities.Affiliation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='entities.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='affiliation',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='affiliations', through='entities.RoleFulfillment', to='entities.Role'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupations', to='entities.OccupationClassification'),
        ),
    ]
