# Generated by Django 3.0.1 on 2020-01-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_auto_20200104_0345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntityTopicRelation',
        ),
    ]
