# Generated by Django 3.0.1 on 2020-01-05 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_delete_entitytopicrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='affiliations',
        ),
    ]
