# Generated by Django 3.0.1 on 2020-01-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0017_remove_person_affiliations'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='affiliations',
            field=models.ManyToManyField(blank=True, related_name='members', through='entities.Affiliation', to='entities.Organization'),
        ),
    ]
