# Generated by Django 3.0.1 on 2020-01-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0019_auto_20200124_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name', 'birth_datetime'], 'verbose_name_plural': 'Entities'},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='death_date',
        ),
    ]
