# Generated by Django 3.0.1 on 2020-01-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0020_auto_20200124_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name', 'birth_date'], 'verbose_name_plural': 'Entities'},
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='birth_datetime',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='death_datetime',
            new_name='death_date',
        ),
    ]
