# Generated by Django 3.0.2 on 2020-02-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0021_auto_20200124_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
