# Generated by Django 3.0.2 on 2020-02-02 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0025_auto_20200202_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterUniqueTogether(
            name='entityimage',
            unique_together=set(),
        ),
    ]
