# Generated by Django 3.0.2 on 2020-02-02 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0027_auto_20200202_0159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entityimage',
            unique_together=set(),
        ),
    ]
