# Generated by Django 3.0.2 on 2020-02-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0031_auto_20200202_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together={('person', 'organization', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='occupationengagement',
            unique_together={('person', 'occupation', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='rolefulfillment',
            unique_together={('affiliation', 'role', 'start_date')},
        ),
    ]
