# Generated by Django 3.0.2 on 2020-02-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0032_auto_20200202_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='is_living',
        ),
    ]
