# Generated by Django 3.0.2 on 2020-02-14 03:38

from django.db import migrations, models
import django.db.models.deletion
import history.fields.array_field


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0033_remove_entity_is_living'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('aliases', history.fields.array_field.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_classifications', to='entities.Classification')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_classifications', to='entities.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='classifications',
            field=models.ManyToManyField(blank=True, related_name='entities', through='entities.EntityClassification', to='entities.Classification'),
        ),
    ]
