# Generated by Django 3.0.2 on 2020-02-14 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0034_auto_20200214_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='entities.Classification'),
        ),
    ]
