# Generated by Django 3.0.2 on 2020-02-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0036_auto_20200214_0707'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occupationengagement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='occupationengagement',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='occupationengagement',
            name='person',
        ),
        migrations.RemoveField(
            model_name='role',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='rolefulfillment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolefulfillment',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='rolefulfillment',
            name='role',
        ),
        migrations.RemoveField(
            model_name='person',
            name='affiliations',
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='OccupationEngagement',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RoleFulfillment',
        ),
    ]
