# Generated by Django 3.0.2 on 2020-02-17 12:10

from django.db import migrations, models
import django.db.models.deletion
import history.fields.historic_datetime_field
import history.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0037_auto_20200217_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', history.fields.historic_datetime_field.HistoricDateField(blank=True, null=True)),
                ('end_date', history.fields.historic_datetime_field.HistoricDateField(blank=True, null=True)),
                ('affiliated_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Entity')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='entities.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', history.fields.html_field.HTMLField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='entities.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleFulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', history.fields.historic_datetime_field.HistoricDateField(blank=True, null=True)),
                ('end_date', history.fields.historic_datetime_field.HistoricDateField(blank=True, null=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_fulfillments', to='entities.Affiliation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='entities.Role')),
            ],
            options={
                'unique_together': {('affiliation', 'role', 'start_date')},
            },
        ),
        migrations.AddField(
            model_name='affiliation',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='affiliations', through='entities.RoleFulfillment', to='entities.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together={('entity', 'affiliated_entity', 'start_date')},
        ),
    ]
