# Generated by Django 3.0.2 on 2020-02-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0038_auto_20200217_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='occupations',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='OccupationClassification',
        ),
    ]
