# Generated by Django 3.0.2 on 2020-02-17 12:27

from django.db import migrations, models
import history.fields
import history.fields
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0039_auto_20200217_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entities.person2', 'person2'), ('entities.organization2', 'organization2')], db_index=True, max_length=255)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('aliases', history.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('description', history.fields.HTMLField(blank=True, null=True)),
                ('birth_date', history.fields.HistoricDateTimeField(blank=True, null=True)),
                ('death_date', history.fields.HistoricDateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('entities.entity2',),
        ),
        migrations.CreateModel(
            name='Person2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('entities.entity2',),
        ),
    ]
