# Generated by Django 3.0.2 on 2020-02-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0023_auto_20200203_1435'),
        ('sources', '0144_book_translator'),
        ('quotes', '0036_auto_20200216_1043'),
        ('occurrences', '0054_auto_20200216_1043'),
        ('entities', '0040_entity2_organization2_person2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entity2',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='parent_organization',
        ),
        migrations.RemoveField(
            model_name='person',
            name='entity_ptr',
        ),
        migrations.DeleteModel(
            name='Organization2',
        ),
        migrations.DeleteModel(
            name='Person2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='entity',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='child_organizations', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('entities.person', 'person'), ('entities.organization', 'organization')],
                                   db_index=True, default='entities.person', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('entities.entity',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'verbose_name_plural': 'People',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('entities.entity',),
        ),
    ]
