# Generated by Django 3.0.2 on 2020-02-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0041_auto_20200217_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='affiliated_entities',
            field=models.ManyToManyField(blank=True, related_name='_entity_affiliated_entities_+', through='entities.Affiliation', to='entities.Entity'),
        ),
    ]
