# Generated by Django 3.0.2 on 2020-02-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0042_entity_affiliated_entities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deity',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Deities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('entities.entity',),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('entities.person', 'person'), ('entities.deity', 'deity'), ('entities.organization', 'organization')], db_index=True, max_length=255),
        ),
    ]
