# Generated by Django 3.0.2 on 2020-03-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0043_auto_20200227_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('entities.entity',),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('entities.person', 'person'), ('entities.deity', 'deity'), ('entities.group', 'group'), ('entities.organization', 'organization')], db_index=True, max_length=255),
        ),
    ]
