# Generated by Django 3.0.4 on 2020-03-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0045_entityidea_idea'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entityclassification',
            unique_together={('entity', 'classification')},
        ),
        migrations.AlterUniqueTogether(
            name='entityidea',
            unique_together={('entity', 'idea')},
        ),
    ]
