# Generated by Django 3.1.13 on 2021-08-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_auto_20210824_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicTopicRelation',
        ),
    ]
