# Generated by Django 3.2.7 on 2021-09-12 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_remove_topic_parent_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicEdge',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tree_children',
                to='topics.topic',
                verbose_name='parent',
            ),
        ),
        migrations.DeleteModel(
            name='TopicParentChildRelation',
        ),
        migrations.AddField(
            model_name='topicedge',
            name='child',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='Topic_parent',
                to='topics.topic',
            ),
        ),
        migrations.AddField(
            model_name='topicedge',
            name='parent',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='Topic_child',
                to='topics.topic',
            ),
        ),
        migrations.AddField(
            model_name='topic',
            name='children',
            field=models.ManyToManyField(
                blank=True,
                related_name='parents',
                through='topics.TopicEdge',
                to='topics.Topic',
            ),
        ),
    ]
