# Generated by Django 3.2.7 on 2021-09-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0012_auto_20210912_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='key',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='path',
        ),
    ]
