# Generated by Django 3.1.13 on 2021-08-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_auto_20210820_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='tags',
        ),
    ]
