# Generated by Django 3.0.1 on 2019-12-28 23:41

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='description',
            field=history.fields.html_field.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='text',
            field=history.fields.html_field.HTMLField(blank=True, null=True, unique=True),
        ),
    ]
