# Generated by Django 3.1.2 on 2020-10-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, help_text='URL where the source can be accessed online', max_length=100, null=True),
        ),
    ]
