# Generated by Django 3.0.4 on 2020-03-13 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('topics', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('places', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefactderivation',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_derivations', to='topics.Fact'),
        ),
        migrations.AddField(
            model_name='sourcefactderivation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_derivations', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='sourcecontainment',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_containments', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='sourcecontainment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_containments', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='sourceattribution',
            name='attributee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_attributions', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='sourceattribution',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Source'),
        ),
        migrations.AddField(
            model_name='source',
            name='attributees',
            field=models.ManyToManyField(related_name='attributed_sources', through='sources.SourceAttribution', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='source',
            name='containers',
            field=models.ManyToManyField(blank=True, related_name='contained_sources', through='sources.SourceContainment', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='source',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='sources.SourceFile'),
        ),
        migrations.AddField(
            model_name='source',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='places.Place'),
        ),
        migrations.AddField(
            model_name='source',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_sources.source_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='collection',
            name='repository',
            field=models.ForeignKey(help_text='the collecting institution', on_delete=django.db.models.deletion.CASCADE, to='sources.Repository'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcefactderivation',
            unique_together={('source', 'page_number', 'end_page_number', 'position')},
        ),
        migrations.AddField(
            model_name='letter',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='sources.Collection'),
        ),
        migrations.AddField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='sources.Collection'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'repository')},
        ),
        migrations.AddField(
            model_name='book',
            name='original_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_editions', to='sources.Book'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.Publication'),
        ),
        migrations.AddField(
            model_name='affidavit',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affidavit', to='sources.Collection'),
        ),
    ]
