# Generated by Django 3.1.2 on 2020-10-20 14:32

from django.db import migrations
import modularhistory.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20201020_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='computations',
            field=modularhistory.fields.json_field.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='computations',
            field=modularhistory.fields.json_field.JSONField(blank=True, default=dict, null=True),
        ),
    ]
