# Generated by Django 3.0.4 on 2020-03-14 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('sources', '0002_auto_20200313_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='location',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='repository',
            name='blah_blah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='places.Place'),
        ),
    ]
