# Generated by Django 3.0.5 on 2020-05-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_pagerange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagerange',
            options={'ordering': ['page_number']},
        ),
    ]
