# Generated by Django 3.0.1 on 2019-12-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20191228_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={},
        ),
    ]
