# Generated by Django 3.0.1 on 2019-12-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20191229_2053'),
        ('sources', '0003_auto_20191229_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='tags',
        ),
        migrations.CreateModel(
            name='SourceFactDerivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='reference position')),
                ('page_number', models.CharField(blank=True, max_length=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_derivations', to='topics.Fact')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_derivations', to='sources.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
