# Generated by Django 3.0.5 on 2020-05-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20200503_0704'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagerange',
            unique_together={('citation', 'page_number')},
        ),
    ]
