# Generated by Django 3.0.4 on 2020-03-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20200314_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='blah_blah',
            new_name='location',
        ),
    ]
