# Generated by Django 3.1.2 on 2020-10-21 06:49

import django.db.models.deletion
from django.db import migrations, models

import modularhistory.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20201020_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='computations',
            field=modularhistory.fields.json_field.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='db_file',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sources',
                to='sources.sourcefile',
                verbose_name='file',
            ),
        ),
    ]
