# Generated by Django 3.0.1 on 2019-12-30 00:53

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20191229_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='date',
            field=history.fields.historic_datetime_field.HistoricDateField(blank=True, null=True),
        ),
    ]
