# Generated by Django 3.0.5 on 2020-05-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20200503_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='citation_phrase',
            field=models.CharField(blank=True, choices=[(None, ''), ('quoted in', 'quoted in'), ('cited in', 'cited in'), ('partially reproduced in', 'partially reproduced in')], default=None, max_length=25, null=True),
        ),
    ]
