# Generated by Django 3.0.4 on 2020-03-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20200314_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcefactderivation',
            options={'verbose_name': 'citation'},
        ),
    ]
