# Generated by Django 3.1.2 on 2020-10-22 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20201021_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='db_string',
            new_name='full_string',
        ),
    ]
