# Generated by Django 3.1.2 on 2020-10-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_auto_20201022_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='containers',
            field=models.ManyToManyField(blank=True, related_name='contained_sources', through='sources.SourceContainment', to='sources.Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='full_string',
            field=models.CharField(blank=True, max_length=500, unique=True, verbose_name='searchable string'),
        ),
    ]
