# Generated by Django 3.0.5 on 2020-05-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0005_auto_20200503_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['position', 'source']},
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together={('source', 'content_type', 'object_id', 'position')},
        ),
        migrations.RemoveField(
            model_name='citation',
            name='end_page_number',
        ),
        migrations.RemoveField(
            model_name='citation',
            name='page_number',
        ),
    ]
