# Generated by Django 3.0.1 on 2019-12-30 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_auto_20191230_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sources.Source')),
            ],
            options={
                'abstract': False,
            },
            bases=('sources.source',),
        ),
        migrations.AddField(
            model_name='source',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources_contained', to='sources.Source'),
        ),
    ]
