# Generated by Django 3.0.5 on 2020-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_auto_20200503_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerange',
            name='page_number',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
