# Generated by Django 3.0.1 on 2019-12-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20191230_0203'),
        ('quotes', '0007_auto_20191230_0100'),
        ('topics', '0007_auto_20191229_2058'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('occurrences', '0006_auto_20191229_1449'),
        ('places', '0002_auto_20191229_1449'),
        ('sources', '0006_auto_20191230_0518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Essay',
            new_name='Piece',
        ),
        migrations.AddField(
            model_name='book',
            name='volume_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
