# Generated by Django 3.0.4 on 2020-03-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_citation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcefactderivation',
            options={'ordering': ['position', 'source', 'page_number'], 'verbose_name': 'citation'},
        ),
    ]
