# Generated by Django 3.0.7 on 2020-09-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_auto_20200503_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='link',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='documentary',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='speech',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
