# Generated by Django 3.0.1 on 2019-12-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_auto_20191230_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('title', 'date')},
        ),
        migrations.RemoveField(
            model_name='source',
            name='text',
        ),
    ]
