# Generated by Django 3.0.1 on 2019-12-31 04:45

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_auto_20191230_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='publication_date',
            field=history.fields.historic_datetime_field.HistoricDateField(blank=True, null=True),
        ),
    ]
