# Generated by Django 3.0.7 on 2020-09-16 06:07

from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields
import history.fields
import history.fields.historic_datetime_field


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200909_0442'),
        ('entities', '0012_auto_20200909_0442'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0008_auto_20200915_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='sources.Source'),
        ),
        migrations.AlterField(
            model_name='sourceattribution',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='sources.Source'),
        ),
        migrations.AlterField(
            model_name='sourcecontainment',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_containments', to='sources.Source'),
        ),
        migrations.AlterField(
            model_name='sourcecontainment',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_containments', to='sources.Source'),
        ),
        migrations.CreateModel(
            name='TypedSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[], db_index=True, max_length=255)),
                ('db_string', models.CharField(blank=True, max_length=500, unique=True, verbose_name='database string')),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('description', history.fields.HTMLField(blank=True, null=True)),
                ('date', history.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True)),
                ('publication_date', history.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True)),
                ('creators', models.CharField(blank=True, max_length=100, null=True)),
                ('attributees', models.ManyToManyField(blank=True, through='sources.SourceAttribution', to='entities.Entity')),
                ('containers', models.ManyToManyField(blank=True, through='sources.SourceContainment', to='sources.TypedSource')),
                ('db_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.SourceFile', verbose_name='file')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Place')),
                ('old_source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_source', to='sources.Source')),
                ('related', gm2m.fields.GM2MField('quotes.Quote', 'occurrences.Occurrence', blank=True, through='sources.Citation', through_fields=['typed_source', 'content_object', 'content_type', 'object_id'])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='citation',
            name='typed_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='sources.TypedSource'),
        ),
        migrations.AddField(
            model_name='sourceattribution',
            name='typed_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='sources.TypedSource'),
        ),
        migrations.AddField(
            model_name='sourcecontainment',
            name='typed_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typed_container_containments', to='sources.TypedSource'),
        ),
        migrations.AddField(
            model_name='sourcecontainment',
            name='typed_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typed_source_containments', to='sources.TypedSource'),
        ),
    ]
