# Generated by Django 3.0.4 on 2020-03-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_auto_20200319_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='url2',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
