# Generated by Django 3.1.3 on 2020-11-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_auto_20201118_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
