# Generated by Django 3.0.1 on 2019-12-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_source_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefactderivation',
            name='end_page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
