# Generated by Django 3.0.4 on 2020-03-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_source_url2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='link',
        ),
    ]
