# Generated by Django 3.0.7 on 2020-09-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_auto_20200916_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextualSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.typedsource',),
        ),
        migrations.AlterModelOptions(
            name='typedsource',
            options={'ordering': ['creators', '-date']},
        ),
        migrations.AddField(
            model_name='typedsource',
            name='editors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='typedsource',
            name='type',
            field=models.CharField(choices=[('sources.textualsource', 'textual source')], db_index=True, max_length=255),
        ),
    ]
