# Generated by Django 3.0.4 on 2020-03-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_remove_source_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='url2',
            new_name='url',
        ),
    ]
