# Generated by Django 3.0.1 on 2020-01-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('places', '0002_auto_20191229_1449'),
        ('entities', '0007_auto_20191230_0203'),
        ('occurrences', '0008_auto_20191231_1840'),
        ('topics', '0007_auto_20191229_2058'),
        ('quotes', '0009_auto_20191231_1840'),
        ('sources', '0011_auto_20191231_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='JournalArticle',
        ),
    ]
