# Generated by Django 3.0.4 on 2020-03-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_auto_20200319_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='affidavit',
            name='information_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='information_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='information_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
