# Generated by Django 3.0.1 on 2020-01-01 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_auto_20200101_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewspaperArticle',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sources.Source')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('newspaper', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('sources.source',),
        ),
    ]
