# Generated by Django 3.0.7 on 2020-09-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_auto_20200917_0511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractPiece',
        ),
        migrations.CreateModel(
            name='SourceWithPageNumbers',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.textualsource',),
        ),
        migrations.AlterField(
            model_name='typedsource',
            name='type',
            field=models.CharField(
                choices=[
                    ('sources.textualsource', 'textual source'),
                    ('sources.sourcewithpagenumbers', 'source with page numbers')
                ],
                db_index=True,
                max_length=255
            ),
        ),
    ]
