# Generated by Django 3.0.4 on 2020-03-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_auto_20200319_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affidavit',
            name='information_url',
            field=models.URLField(blank=True, help_text='URL for information regarding the document', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='information_url',
            field=models.URLField(blank=True, help_text='URL for information regarding the document', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='information_url',
            field=models.URLField(blank=True, help_text='URL for information regarding the document', max_length=100, null=True),
        ),
    ]
