# Generated by Django 3.0.4 on 2020-03-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0013_auto_20200319_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceattribution',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='sources.Source'),
        ),
    ]
