# Generated by Django 3.0.1 on 2020-01-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0014_auto_20200101_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='citations',
            field=models.ManyToManyField(blank=True, related_name='_source_citations_+', to='sources.Source'),
        ),
    ]
