# Generated by Django 3.0.7 on 2020-09-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0014_auto_20200917_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitledSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.typedsource',),
        ),
        migrations.AddField(
            model_name='typedsource',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='typedsource',
            name='type',
            field=models.CharField(choices=[('sources.titledsource', 'titled source'), ('sources.textualsource', 'textual source'), ('sources.sourcewithpagenumbers', 'source with page numbers')], db_index=True, max_length=255),
        ),
    ]
