# Generated by Django 3.0.4 on 2020-03-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_entity_verbose_name'),
        ('sources', '0014_auto_20200328_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='attributees',
            field=models.ManyToManyField(blank=True, related_name='attributed_sources', through='sources.SourceAttribution', to='entities.Entity'),
        ),
    ]
