# Generated by Django 3.0.1 on 2020-01-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_auto_20200101_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-year', '-date', 'creators']},
        ),
    ]
