# Generated by Django 3.0.4 on 2020-03-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_auto_20200329_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Determines the order of references.'),
        ),
    ]
