# Generated by Django 3.0.1 on 2020-01-01 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0018_auto_20200101_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sources.Source')),
            ],
            options={
                'abstract': False,
            },
            bases=('sources.source',),
        ),
    ]
