# Generated by Django 3.0.1 on 2020-01-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0019_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalarticle',
            old_name='journal',
            new_name='journal_name',
        ),
        migrations.RenameField(
            model_name='newspaperarticle',
            old_name='newspaper',
            new_name='newspaper_name',
        ),
        migrations.AddField(
            model_name='document',
            name='collection_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='aka acquisition number', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='location_info',
            field=models.CharField(blank=True, help_text='Ex: John H. Alexander Papers, Series 1: Correspondence, 1831-1848, Folder 1', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='repository_name',
            field=models.CharField(blank=True, help_text='the name of the collecting institution', max_length=100, null=True),
        ),
    ]
