# Generated by Django 3.0.4 on 2020-03-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_remove_fact_sources2'),
        ('sources', '0019_auto_20200329_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['position', 'source', 'page_number'], 'verbose_name': 'citation'},
        ),
        migrations.DeleteModel(
            name='SourceFactDerivation',
        ),
    ]
