# Generated by Django 3.0.1 on 2020-01-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0020_auto_20200101_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalarticle',
            old_name='journal_fk',
            new_name='journal',
        ),
        migrations.RenameField(
            model_name='newspaperarticle',
            old_name='newspaper_fk',
            new_name='newspaper',
        ),
    ]
