# Generated by Django 3.0.7 on 2020-09-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0020_auto_20200921_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='OldBook',
        ),
    ]
