# Generated by Django 3.0.4 on 2020-03-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0020_auto_20200329_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='first_page_number',
            field=models.SmallIntegerField(blank=True, default=1, help_text='The page number that is visibly displayed on the page on which the relevant text begins (usually 1).'),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='page_offset',
            field=models.SmallIntegerField(blank=True, default=0, help_text='The difference between the page numbers displayed on the pages and the actual page numbers of the electronic file (a positive number if the electronic page number is greater than the textualpage number; a negative number if the textual page number is greater than the electronic page number).'),
        ),
    ]
