# Generated by Django 3.0.4 on 2020-03-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0021_auto_20200330_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='file',
            new_name='db_file',
        ),
    ]
