# Generated by Django 3.0.1 on 2020-01-02 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0022_magazine_magazinearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaperarticle',
            name='newspaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newspaper_articles', to='sources.Newspaper'),
        ),
    ]
