# Generated by Django 3.0.7 on 2020-09-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('places', '0002_auto_20200909_0442'),
        ('entities', '0012_auto_20200909_0442'),
        ('sources', '0022_auto_20200921_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speech',
            new_name='OldSpeech',
        ),
    ]
