# Generated by Django 3.0.4 on 2020-03-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0022_auto_20200330_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='db_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='sources.SourceFile', verbose_name='file'),
        ),
    ]
