# Generated by Django 3.0.4 on 2020-04-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0023_auto_20200330_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='affidavit',
            name='descriptive_phrase',
            field=models.CharField(blank=True, help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='descriptive_phrase',
            field=models.CharField(blank=True, help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='descriptive_phrase',
            field=models.CharField(blank=True, help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"', max_length=30, null=True),
        ),
    ]
