# Generated by Django 3.0.1 on 2020-01-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0023_auto_20200102_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magazine',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='source',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourceattribution',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcefactderivation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
