# Generated by Django 3.0.4 on 2020-04-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0024_auto_20200402_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affidavit',
            name='descriptive_phrase',
            field=models.CharField(blank=True, help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='descriptive_phrase',
            field=models.CharField(blank=True, help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='descriptive_phrase',
            field=models.CharField(blank=True, help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"', max_length=50, null=True),
        ),
    ]
