# Generated by Django 3.0.7 on 2020-09-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0024_auto_20200923_0450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Letter',
            new_name='OldLetter',
        ),
    ]
