# Generated by Django 3.0.1 on 2020-01-03 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0024_auto_20200103_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sources.Source')),
                ('repository_name', models.CharField(blank=True, help_text='the name of the collecting institution', max_length=100, null=True)),
                ('collection_number', models.PositiveSmallIntegerField(blank=True, help_text='aka acquisition number', null=True)),
                ('location_info', models.CharField(blank=True, help_text='Ex: John H. Alexander Papers, Series 1: Correspondence, 1831-1848, Folder 1', max_length=400, null=True)),
                ('recipient', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('sources.source',),
        ),
    ]
