# Generated by Django 3.0.1 on 2020-01-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0025_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='newspaper',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='source',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='sourceattribution',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='sourcefactderivation',
            name='verified',
        ),
    ]
