# Generated by Django 3.0.7 on 2020-09-23 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0025_auto_20200923_0503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='OldDocument',
        ),
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.sourcewithpagenumbers',),
        ),
        migrations.AddField(
            model_name='typedsource',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typedsource', to='sources.Collection'),
        ),
        migrations.AddField(
            model_name='typedsource',
            name='collection_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='aka acquisition number', null=True),
        ),
        migrations.AddField(
            model_name='typedsource',
            name='location_info',
            field=models.CharField(blank=True, help_text='Ex: John H. Alexander Papers, Series 1: Correspondence, 1831-1848, Folder 1', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='oldletter',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oldletter', to='sources.Collection'),
        ),
        migrations.AlterField(
            model_name='typedsource',
            name='type',
            field=models.CharField(choices=[('sources.textualsource', 'textual source'), ('sources.sourcewithpagenumbers', 'source with page numbers'), ('sources.article', 'article'), ('sources.book', 'book'), ('sources.chapter', 'chapter'), ('sources.documentsource', 'document source'), ('sources.correspondence', 'correspondence'), ('sources.email', 'email'), ('sources.letter', 'letter'), ('sources.memorandum', 'memorandum'), ('sources.spokensource', 'spoken source'), ('sources.speech', 'speech'), ('sources.address', 'address'), ('sources.discourse', 'discourse'), ('sources.lecture', 'lecture'), ('sources.sermon', 'sermon'), ('sources.statement', 'statement')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='typedsource',
            name='type2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.documentsource',),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.correspondence',),
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.correspondence',),
        ),
        migrations.CreateModel(
            name='Memorandum',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.correspondence',),
        ),
    ]
