# Generated by Django 3.0.7 on 2020-09-23 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0026_auto_20200923_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olddocument',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olddocument', to='sources.Collection'),
        ),
        migrations.AlterField(
            model_name='typedsource',
            name='type2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
