# Generated by Django 3.0.7 on 2020-09-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0027_auto_20200923_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typedsource',
            name='collection_number',
        ),
        migrations.RemoveField(
            model_name='typedsource',
            name='location_info',
        ),
    ]
