# Generated by Django 3.0.1 on 2020-01-04 03:56

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0027_auto_20200104_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='description',
            field=history.fields.html_field.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='description',
            field=history.fields.html_field.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='description',
            field=history.fields.html_field.HTMLField(blank=True, null=True),
        ),
    ]
