# Generated by Django 3.0.4 on 2020-04-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0027_book_edition_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affidavit',
            name='descriptive_phrase',
            field=models.CharField(blank=True, help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='descriptive_phrase',
            field=models.CharField(blank=True, help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='descriptive_phrase',
            field=models.CharField(blank=True, help_text='e.g., "on such-and-such letterhead" or "signed by so-and-so"', max_length=100, null=True),
        ),
    ]
