# Generated by Django 3.0.1 on 2020-01-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0028_auto_20200104_0356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['creators', '-year', '-date']},
        ),
    ]
