# Generated by Django 3.0.7 on 2020-09-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200909_0442'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('entities', '0012_auto_20200909_0442'),
        ('sources', '0028_auto_20200923_0535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interview',
            new_name='OldInterview',
        ),
    ]
