# Generated by Django 3.0.4 on 2020-04-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_auto_20200329_1523'),
        ('occurrences', '0008_auto_20200329_1523'),
        ('sources', '0028_auto_20200405_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['position', 'source', 'page_number']},
        ),
        migrations.CreateModel(
            name='QSR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_phrase', models.CharField(blank=True, choices=[(None, ''), ('quoted in', 'quoted in'), ('cited in', 'cited in')], default=None, max_length=10, null=True)),
                ('page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Determines the order of references.')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qsrs', to='quotes.Quote')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qsrs', to='sources.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OSR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_phrase', models.CharField(blank=True, choices=[(None, ''), ('quoted in', 'quoted in'), ('cited in', 'cited in')], default=None, max_length=10, null=True)),
                ('page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Determines the order of references.')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osrs', to='occurrences.Occurrence')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osrs', to='sources.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
