# Generated by Django 3.0.1 on 2020-01-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0029_auto_20200104_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sources.Source')),
                ('venue', models.CharField(blank=True, max_length=40, null=True)),
                ('interviewers', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('sources.source', models.Model),
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sources.Source')),
                ('venue', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('sources.source', models.Model),
        ),
        migrations.RemoveField(
            model_name='source',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='publication_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='magazinearticle',
            name='publication_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newspaperarticle',
            name='publication_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
