# Generated by Django 3.0.5 on 2020-04-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0030_auto_20200406_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Determines the order of references.', null=True),
        ),
        migrations.AlterField(
            model_name='sourceattribution',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcecontainment',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
