# Generated by Django 3.0.1 on 2020-01-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0030_auto_20200104_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalarticle',
            name='journal_name',
        ),
        migrations.RemoveField(
            model_name='newspaperarticle',
            name='newspaper_name',
        ),
    ]
