# Generated by Django 3.0.1 on 2020-01-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0031_auto_20200104_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazinearticle',
            name='magazine_name',
        ),
    ]
