# Generated by Django 3.0.7 on 2020-09-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0031_auto_20200923_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedsource',
            name='type',
            field=models.CharField(choices=[
                ('sources.textualsource', 'textual source'),
                ('sources.sourcewithpagenumbers', 'source with page numbers'),
                ('sources.piece', 'piece'),
                ('sources.essay', 'essay'),
                ('sources.documentsource', 'document source'),
                ('sources.document', 'document'),
                ('sources.article', 'article'),
                ('sources.book', 'book'),
                ('sources.chapter', 'chapter'),
                ('sources.correspondence', 'correspondence'),
                ('sources.email', 'email'),
                ('sources.letter', 'letter'),
                ('sources.memorandum', 'memorandum'),
                ('sources.spokensource', 'spoken source'),
                ('sources.speech', 'speech'),
                ('sources.address', 'address'),
                ('sources.discourse', 'discourse'),
                ('sources.lecture', 'lecture'),
                ('sources.sermon', 'sermon'),
                ('sources.statement', 'statement'),
                ('sources.interview', 'interview')
            ], db_index=True, max_length=255),
        ),
    ]
