# Generated by Django 3.0.1 on 2020-01-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0032_remove_magazinearticle_magazine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinearticle',
            name='volume_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
