# Generated by Django 3.0.7 on 2020-09-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0032_auto_20200923_0553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Affidavit',
            new_name='OldAffidavit',
        ),
    ]
