# Generated by Django 3.0.1 on 2020-01-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0033_magazinearticle_volume_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalarticle',
            name='end_page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magazinearticle',
            name='end_page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magazinearticle',
            name='page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newspaperarticle',
            name='end_page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newspaperarticle',
            name='page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
