# Generated by Django 3.0.1 on 2020-01-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0034_auto_20200105_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speech',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
