# Generated by Django 3.0.1 on 2020-01-06 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0035_auto_20200106_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_editions', to='sources.Book'),
        ),
    ]
