# Generated by Django 3.0.1 on 2020-01-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0036_book_original_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
