# Generated by Django 3.0.7 on 2020-09-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200909_0442'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('entities', '0012_auto_20200909_0442'),
        ('sources', '0037_auto_20200923_0609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentary',
            new_name='OldDocumentary',
        ),
    ]
