# Generated by Django 3.0.1 on 2020-01-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0037_book_edition_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='audience',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
