# Generated by Django 3.0.1 on 2020-01-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0038_speech_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='audience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
