# Generated by Django 3.0.1 on 2020-01-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0039_auto_20200108_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='type',
            field=models.CharField(choices=[('speech', 'speech'), ('address', 'address'), ('statement', 'statement')], default='speech', max_length=10),
        ),
    ]
