# Generated by Django 3.0.7 on 2020-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0039_auto_20200923_0615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.CreateModel(
            name='SectionSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sources.textualsource',),
        ),
        migrations.AlterField(
            model_name='typedsource',
            name='type',
            field=models.CharField(choices=[('sources.textualsource', 'textual source'), ('sources.sourcewithpagenumbers', 'source with page numbers'), ('sources.piece', 'piece'), ('sources.essay', 'essay'), ('sources.documentsource', 'document source'), ('sources.document', 'document'), ('sources.affidavit', 'affidavit'), ('sources.article', 'article'), ('sources.book', 'book'), ('sources.sectionsource', 'section source'), ('sources.correspondence', 'correspondence'), ('sources.email', 'email'), ('sources.letter', 'letter'), ('sources.memorandum', 'memorandum'), ('sources.spokensource', 'spoken source'), ('sources.speech', 'speech'), ('sources.address', 'address'), ('sources.discourse', 'discourse'), ('sources.lecture', 'lecture'), ('sources.sermon', 'sermon'), ('sources.statement', 'statement'), ('sources.interview', 'interview'), ('sources.journalentry', 'journal entry'), ('sources.videosource', 'video source'), ('sources.documentary', 'documentary'), ('sources.webpage', 'web page')], db_index=True, max_length=255),
        ),
    ]
