# Generated by Django 3.0.1 on 2020-01-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0041_documentary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='publication_date',
            new_name='origin_date',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
