# Generated by Django 3.0.1 on 2020-01-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0042_auto_20200109_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='origin_date',
            new_name='publication_date',
        ),
    ]
