# Generated by Django 3.0.1 on 2020-01-09 06:38

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0043_auto_20200109_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_publication_date',
            field=history.fields.HistoricDateField(blank=True, null=True),
        ),
    ]
