# Generated by Django 3.0.1 on 2020-01-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0044_book_original_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='file_page_offset',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
