# Generated by Django 3.0.1 on 2020-01-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0045_source_file_page_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='file_page_offset',
        ),
        migrations.AddField(
            model_name='book',
            name='file_page_offset',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_page_offset',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='file_page_offset',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='file_page_offset',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='magazinearticle',
            name='file_page_offset',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='newspaperarticle',
            name='file_page_offset',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='file_page_offset',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
