# Generated by Django 3.0.7 on 2020-09-26 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0045_remove_typedsource_old_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='new_source',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_source', to='sources.TypedSource'),
        ),
    ]
