# Generated by Django 3.0.1 on 2020-01-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0046_auto_20200109_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='temp',
        ),
        migrations.AddField(
            model_name='piece',
            name='end_page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
