# Generated by Django 3.0.1 on 2020-01-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0018_person_affiliations'),
        ('places', '0004_remove_place_verified'),
        ('quotes', '0016_auto_20200104_0452'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('topics', '0021_auto_20200105_2237'),
        ('occurrences', '0024_auto_20200107_1640'),
        ('sources', '0047_auto_20200112_0119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Piece',
            new_name='Essay',
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='magazine',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ['name']},
        ),
    ]
