# Generated by Django 3.1.1 on 2020-09-26 10:52

from django.db import migrations
import modularhistory.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0047_auto_20200926_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedsource',
            name='extra',
            field=modularhistory.fields.json_field.JSONField(blank=True, null=True),
        ),
    ]
