# Generated by Django 3.0.10 on 2020-09-26 11:51

from django.db import migrations
import history.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0048_auto_20200926_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedsource',
            name='extra',
            field=history.fields.json_field.JSONField(blank=True, default=dict, null=True),
        ),
    ]
