# Generated by Django 3.0.1 on 2020-01-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0048_auto_20200113_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentary',
            options={'verbose_name_plural': 'Documentaries'},
        ),
        migrations.AlterField(
            model_name='book',
            name='file_page_offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_page_offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='file_page_offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='file_page_offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='file_page_offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='magazinearticle',
            name='file_page_offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='newspaperarticle',
            name='file_page_offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
