# Generated by Django 3.0.10 on 2020-09-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0049_auto_20200926_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typedsource',
            name='type2',
        ),
        migrations.AlterField(
            model_name='citation',
            name='typed_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='sources.TypedSource'),
        ),
    ]
