# Generated by Django 3.0.10 on 2020-09-28 13:32

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0050_auto_20200927_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['position', 'old_source']},
        ),
        migrations.RenameField(
            model_name='citation',
            old_name='source',
            new_name='old_source',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='type2',
        ),
        migrations.AlterField(
            model_name='source',
            name='related',
            field=gm2m.fields.GM2MField('quotes.Quote', 'occurrences.Occurrence', blank=True, related_name='sources', through='sources.Citation', through_fields=['old_source', 'content_object', 'content_type', 'object_id']),
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together={('old_source', 'content_type', 'object_id', 'position')},
        ),
    ]
