# Generated by Django 3.0.1 on 2020-01-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0050_auto_20200116_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
