# Generated by Django 3.0.10 on 2020-09-28 23:12

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0051_auto_20200928_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='typed_source',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='typedsource',
            name='related',
            field=gm2m.fields.GM2MField('quotes.Quote', 'occurrences.Occurrence', blank=True, through='sources.Citation', through_fields=['source', 'content_object', 'content_type', 'object_id']),
        ),
    ]
