# Generated by Django 3.0.10 on 2020-09-29 01:08

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0052_auto_20200928_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['position', 'source']},
        ),
        migrations.RemoveField(
            model_name='source',
            name='attributees',
        ),
        migrations.RemoveField(
            model_name='source',
            name='description',
        ),
        migrations.RemoveField(
            model_name='source',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='source',
            name='related',
        ),
        migrations.RemoveField(
            model_name='source',
            name='url',
        ),
        migrations.AlterField(
            model_name='typedsource',
            name='related',
            field=gm2m.fields.GM2MField('quotes.Quote', 'occurrences.Occurrence', blank=True, related_name='sources', through='sources.Citation', through_fields=['source', 'content_object', 'content_type', 'object_id']),
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together={('source', 'content_type', 'object_id', 'position')},
        ),
        migrations.RemoveField(
            model_name='citation',
            name='old_source',
        ),
    ]
