# Generated by Django 3.0.1 on 2020-01-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0052_auto_20200117_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
