# Generated by Django 3.0.1 on 2020-01-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0053_auto_20200117_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaperarticle',
            name='volume_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
