# Generated by Django 3.0.10 on 2020-09-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0054_auto_20200929_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='polymorphic_ctype',
        ),
    ]
