# Generated by Django 3.0.1 on 2020-01-24 15:25

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0054_newspaperarticle_volume_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='datetime',
            field=history.fields.HistoricDateTimeField(blank=True, null=True),
        ),
    ]
