# Generated by Django 3.0.1 on 2020-01-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0055_source_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['creators', '-year', '-datetime']},
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('title', 'datetime')},
        ),
        migrations.RemoveField(
            model_name='source',
            name='date',
        ),
    ]
