# Generated by Django 3.0.10 on 2020-09-29 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0055_remove_source_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcecontainment',
            options={'ordering': ['position', 'typed_source']},
        ),
        migrations.RemoveField(
            model_name='sourcecontainment',
            name='container',
        ),
        migrations.RemoveField(
            model_name='sourcecontainment',
            name='source',
        ),
    ]
