# Generated by Django 3.0.10 on 2020-09-29 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0056_auto_20200929_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceattribution',
            name='source',
        ),
        migrations.RenameModel(
            'Source', 'OldSource'
        ),
    ]
