# Generated by Django 3.0.1 on 2020-01-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0056_auto_20200124_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['creators', '-year', '-date']},
        ),
        migrations.RenameField(
            model_name='source',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('title', 'date')},
        ),
    ]
