# Generated by Django 3.0.1 on 2020-01-26 04:44

from django.db import migrations, models
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0057_auto_20200124_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('journal', 'Journal'), ('newspaper', 'Newspaper'), ('magazine', 'Magazine')], max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('aliases', models.CharField(blank=True, max_length=100, null=True)),
                ('description', history.fields.html_field.HTMLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
