# Generated by Django 3.0.10 on 2020-09-29 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0058_auto_20200929_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='source',
                to='sources.Collection'
            ),
        ),
        migrations.DeleteModel(
            name='OldSource',
        ),
    ]
