# Generated by Django 3.0.1 on 2020-01-26 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0058_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalarticle',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.Publication'),
        ),
        migrations.AddField(
            model_name='magazinearticle',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.Publication'),
        ),
        migrations.AddField(
            model_name='newspaperarticle',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.Publication'),
        ),
    ]
