# Generated by Django 3.0.1 on 2020-01-26 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0059_auto_20200126_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sources.Source')),
                ('file_page_offset', models.IntegerField(blank=True, default=0, null=True)),
                ('page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('publication_name', models.CharField(blank=True, max_length=100, null=True)),
                ('volume_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.Publication')),
            ],
            options={
                'abstract': False,
            },
            bases=('sources.source',),
        ),
    ]
