# Generated by Django 3.0.10 on 2020-09-29 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0059_auto_20200929_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sources.Collection'),
        ),
    ]
