# Generated by Django 3.0.1 on 2020-01-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0060_article'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set(),
        ),
    ]
