# Generated by Django 3.0.10 on 2020-09-29 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0060_auto_20200929_0416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcecontainment',
            options={'ordering': ['position', 'source']},
        ),
        migrations.RenameField(
            model_name='sourceattribution',
            old_name='typed_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='typed_container',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='typed_source',
            new_name='source',
        )
    ]
