# Generated by Django 3.0.1 on 2020-01-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0028_auto_20200124_1514'),
        ('quotes', '0020_auto_20200124_1523'),
        ('topics', '0021_auto_20200105_2237'),
        ('sources', '0061_auto_20200126_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazinearticle',
            name='magazine',
        ),
        migrations.RemoveField(
            model_name='magazinearticle',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='magazinearticle',
            name='source_ptr',
        ),
        migrations.DeleteModel(
            name='Magazine',
        ),
        migrations.DeleteModel(
            name='MagazineArticle',
        ),
    ]
