# Generated by Django 3.0.1 on 2020-01-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0020_auto_20200124_1523'),
        ('occurrences', '0028_auto_20200124_1514'),
        ('topics', '0021_auto_20200105_2237'),
        ('sources', '0062_auto_20200126_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaperarticle',
            name='newspaper',
        ),
        migrations.RemoveField(
            model_name='newspaperarticle',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='newspaperarticle',
            name='source_ptr',
        ),
        migrations.DeleteModel(
            name='Newspaper',
        ),
        migrations.DeleteModel(
            name='NewspaperArticle',
        ),
    ]
