# Generated by Django 3.0.10 on 2020-10-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_auto_20200909_0442'),
        ('sources', '0062_auto_20200929_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='attributees',
            field=models.ManyToManyField(blank=True, related_name='attributed_sources', through='sources.SourceAttribution', to='entities.Entity'),
        ),
    ]
