# Generated by Django 3.0.10 on 2020-10-13 06:56

from django.db import migrations
import modularhistory.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0063_auto_20201001_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='computations',
            field=modularhistory.fields.json_field.JSONField(blank=True, default=dict, null=True),
        ),
    ]
