# Generated by Django 3.0.1 on 2020-01-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0020_auto_20200124_1523'),
        ('occurrences', '0028_auto_20200124_1514'),
        ('topics', '0021_auto_20200105_2237'),
        ('sources', '0063_auto_20200126_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalarticle',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='journalarticle',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='journalarticle',
            name='source_ptr',
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='JournalArticle',
        ),
    ]
