# Generated by Django 3.0.1 on 2020-01-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0064_auto_20200126_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'verbose_name_plural': 'Speeches'},
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('title', 'date')},
        ),
    ]
