# Generated by Django 3.0.1 on 2020-01-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0065_auto_20200126_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='containers',
            field=models.ManyToManyField(blank=True, related_name='_source_containers_+', to='sources.Source'),
        ),
    ]
