# Generated by Django 3.0.1 on 2020-01-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0066_source_containers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='containers',
        ),
    ]
