# Generated by Django 3.0.1 on 2020-01-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0068_auto_20200127_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='containers',
        ),
        migrations.DeleteModel(
            name='SourceContainment',
        ),
    ]
