# Generated by Django 3.0.1 on 2020-01-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0069_auto_20200127_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceContainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_containments', to='sources.Source')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_containments', to='sources.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='source',
            name='containers',
            field=models.ManyToManyField(blank=True, related_name='contained_sources', through='sources.SourceContainment', to='sources.Source'),
        ),
    ]
