# Generated by Django 3.0.1 on 2020-01-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0070_auto_20200127_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecontainment',
            name='end_page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcecontainment',
            name='page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
