# Generated by Django 3.0.1 on 2020-01-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0071_auto_20200127_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='container',
        ),
    ]
