# Generated by Django 3.0.1 on 2020-01-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0021_auto_20200124_1507'),
        ('sources', '0072_remove_source_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceattribution',
            name='attributee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_attributions', to='entities.Entity'),
        ),
        migrations.AlterField(
            model_name='sourceattribution',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Source'),
        ),
    ]
