# Generated by Django 3.0.1 on 2020-01-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0073_auto_20200128_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcefactderivation',
            name='source_type',
        ),
        migrations.AlterField(
            model_name='speech',
            name='type',
            field=models.CharField(choices=[('speech', 'speech'), ('address', 'address'), ('discourse', 'discourse'), ('statement', 'statement')], default='speech', max_length=10),
        ),
    ]
