# Generated by Django 3.0.1 on 2020-01-29 16:36

from django.db import migrations
import functools
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0075_auto_20200129_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_file',
            field=history.fields.file_field.SourceFileField(blank=True, null=True, upload_to=functools.partial(history.fields.file_field._update_filename, *(), **{'path': 'sources/'})),
        ),
    ]
