# Generated by Django 3.0.1 on 2020-01-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0076_source_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='sources.Collection'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='sources.Collection'),
        ),
    ]
