# Generated by Django 3.0.1 on 2020-01-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0077_auto_20200129_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='source_file',
        ),
    ]
