# Generated by Django 3.0.1 on 2020-01-29 20:19

from django.db import migrations
import functools
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0078_remove_source_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_file',
            field=history.fields.file_field.SourceFileField(
                blank=True, null=True,
                upload_to=functools.partial(history.fields.file_field._update_filename, *(), **{'path': 'sources/'})
            ),
        ),
    ]
