# Generated by Django 3.0.1 on 2020-01-29 20:21

from django.db import migrations
import functools
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0081_auto_20200129_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='source_file',
        ),
        migrations.AlterField(
            model_name='source',
            name='file',
            field=history.fields.SourceFileField(blank=True, null=True, upload_to=functools.partial(history.fields._update_filename, *(), **{'path': 'sources/'})),
        ),
    ]
