# Generated by Django 3.0.1 on 2020-01-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0083_auto_20200129_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='number',
        ),
        migrations.RemoveField(
            model_name='article',
            name='volume_number',
        ),
    ]
