# Generated by Django 3.0.1 on 2020-01-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0084_auto_20200130_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publication_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='publication_volume',
            new_name='volume',
        ),
    ]
