# Generated by Django 3.0.1 on 2020-01-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0085_auto_20200130_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publication_name',
        ),
    ]
