# Generated by Django 3.0.1 on 2020-01-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0086_remove_article_publication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='db_string',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
