# Generated by Django 3.0.1 on 2020-01-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0087_source_db_string'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationnumber',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='publicationvolume',
            options={'ordering': ['number']},
        ),
    ]
