# Generated by Django 3.0.1 on 2020-01-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0088_auto_20200130_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationnumber',
            options={'ordering': ['volume', 'number']},
        ),
        migrations.AlterModelOptions(
            name='publicationvolume',
            options={'ordering': ['publication', 'number']},
        ),
    ]
