# Generated by Django 3.0.1 on 2020-01-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0089_auto_20200130_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationnumber',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Publication'),
        ),
    ]
