# Generated by Django 3.0.2 on 2020-01-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_venue_preposition'),
        ('sources', '0090_auto_20200130_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='places.Place'),
        ),
    ]
