# Generated by Django 3.0.2 on 2020-02-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0091_auto_20200131_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='type',
            field=models.CharField(choices=[('speech', 'speech'), ('address', 'address'), ('discourse', 'discourse'), ('lecture', 'lecture'), ('statement', 'statement')], default='speech', max_length=10),
        ),
    ]
