# Generated by Django 3.0.2 on 2020-02-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0092_auto_20200201_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='db_string',
            field=models.CharField(blank=True, max_length=500, unique=True, verbose_name='database string'),
        ),
    ]
