# Generated by Django 3.0.2 on 2020-02-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0093_auto_20200202_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['creators', '-date']},
        ),
        migrations.RemoveField(
            model_name='source',
            name='year',
        ),
    ]
