# Generated by Django 3.0.2 on 2020-02-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0033_remove_entity_is_living'),
        ('sources', '0094_auto_20200202_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='attributees',
            field=models.ManyToManyField(related_name='attributed_sources', through='sources.SourceAttribution', to='entities.Entity'),
        ),
    ]
