# Generated by Django 3.0.2 on 2020-02-09 06:58

from django.db import migrations, models
import django.db.models.deletion
import functools
import history.fields.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_venue_preposition'),
        ('sources', '0095_auto_20200205_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', history.fields.file_field.SourceFileField(blank=True, null=True, upload_to=functools.partial(history.fields.file_field._update_filename, *(), **{'path': 'sources/'}))),
                ('page_offset', models.SmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='source',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='places.Place'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.SourceFile'),
        ),
    ]
