# Generated by Django 3.0.2 on 2020-02-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0096_auto_20200209_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='file',
        ),
    ]
