# Generated by Django 3.0.2 on 2020-02-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0097_remove_source_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='source_file',
            new_name='file',
        ),
    ]
