# Generated by Django 3.0.2 on 2020-02-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0098_auto_20200209_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='sources.SourceFile'),
        ),
    ]
