# Generated by Django 3.0.2 on 2020-02-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0029_auto_20200207_1527'),
        ('entities', '0033_remove_entity_is_living'),
        ('places', '0005_venue_preposition'),
        ('occurrences', '0042_remove_occurrence_year'),
        ('topics', '0023_auto_20200203_1435'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0099_auto_20200209_0735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Essay',
            new_name='Piece',
        ),
    ]
