# Generated by Django 3.0.2 on 2020-02-09 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0102_auto_20200209_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='sources.Collection'),
        ),
        migrations.AddField(
            model_name='journal',
            name='collection_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='aka acquisition number', null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='location_info',
            field=models.CharField(blank=True, help_text='Ex: John H. Alexander Papers, Series 1: Correspondence, 1831-1848, Folder 1', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='repository_name',
            field=models.CharField(blank=True, help_text='the name of the collecting institution', max_length=100, null=True),
        ),
    ]
