# Generated by Django 3.0.2 on 2020-02-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0103_auto_20200209_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(blank=True, help_text='e.g., "Adam S. Bennion papers"', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'repository')},
        ),
    ]
