# Generated by Django 3.0.2 on 2020-02-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0105_auto_20200209_1346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='source',
            name='title',
        ),
    ]
