# Generated by Django 3.0.2 on 2020-02-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0106_auto_20200209_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title2',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title2',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='title2',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='documentary',
            old_name='title2',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='title2',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='title2',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='speech',
            old_name='title2',
            new_name='title',
        ),
    ]
