# Generated by Django 3.0.2 on 2020-02-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0108_auto_20200210_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecontainment',
            name='verb_phrase',
            field=models.CharField(choices=[('', ''), ('cited', ''), ('quoted', ''), ('reproduced', '')], default='', max_length=10),
        ),
    ]
