# Generated by Django 3.0.2 on 2020-02-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0109_sourcecontainment_verb_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecontainment',
            name='verb_phrase',
            field=models.CharField(choices=[('', '-----'), ('cited', 'cited'), ('quoted', 'quoted'), ('reproduced', 'reproduced')], default='', max_length=10),
        ),
    ]
