# Generated by Django 3.0.2 on 2020-02-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0110_auto_20200210_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecontainment',
            name='verb_phrase',
            field=models.CharField(blank=True, choices=[('', '-----'), ('cited', 'cited'), ('quoted', 'quoted'), ('reproduced', 'reproduced')], default='', max_length=10),
        ),
    ]
