# Generated by Django 3.0.2 on 2020-02-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0111_auto_20200210_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcecontainment',
            old_name='verb_phrase',
            new_name='phrase',
        ),
    ]
