# Generated by Django 3.0.2 on 2020-02-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0112_auto_20200210_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecontainment',
            name='phrase',
            field=models.CharField(blank=True, choices=[('', '-----'), ('cited', 'cited'), ('copy', 'copy'), ('quoted', 'quoted'), ('reproduced', 'reproduced')], default='', max_length=10),
        ),
    ]
