# Generated by Django 3.0.2 on 2020-02-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0113_auto_20200210_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
