# Generated by Django 3.0.2 on 2020-02-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0114_collection_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editors2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='editors2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='editors2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='editors2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='editors2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='editors2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
