# Generated by Django 3.0.2 on 2020-02-11 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0115_auto_20200211_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='editors',
        ),
    ]
