# Generated by Django 3.0.2 on 2020-02-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0117_auto_20200211_0252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcefile',
            options={'ordering': ['file']},
        ),
    ]
