# Generated by Django 3.0.2 on 2020-02-11 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0118_auto_20200211_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationnumber',
            name='file2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_numbers', to='sources.SourceFile'),
        ),
        migrations.AddField(
            model_name='publicationvolume',
            name='file2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_volumes', to='sources.SourceFile'),
        ),
    ]
