# Generated by Django 3.0.2 on 2020-02-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0119_auto_20200211_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationnumber',
            old_name='file',
            new_name='file3',
        ),
        migrations.RenameField(
            model_name='publicationvolume',
            old_name='file',
            new_name='file3',
        ),
    ]
