# Generated by Django 3.0.2 on 2020-02-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0120_auto_20200211_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationnumber',
            old_name='file2',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='publicationvolume',
            old_name='file2',
            new_name='file',
        ),
    ]
