# Generated by Django 3.0.2 on 2020-02-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0123_sourcefile_name2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcefile',
            old_name='name2',
            new_name='name',
        ),
    ]
