# Generated by Django 3.0.2 on 2020-02-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0124_auto_20200211_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcecontainment',
            options={'ordering': ['position', 'source']},
        ),
        migrations.AlterModelOptions(
            name='sourcefile',
            options={'ordering': ['name']},
        ),
    ]
