# Generated by Django 3.0.2 on 2020-02-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0125_auto_20200211_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='file',
            new_name='file2',
        ),
    ]
