# Generated by Django 3.0.2 on 2020-02-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0126_auto_20200211_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='sources.SourceFile'),
        ),
    ]
