# Generated by Django 3.0.2 on 2020-02-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0127_journal_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='number_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='volume_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
