# Generated by Django 3.0.2 on 2020-02-12 12:59

from django.db import migrations
import functools
import history.fields.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0128_auto_20200211_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='file',
            field=history.fields.file_field.SourceFileField(null=True, upload_to=functools.partial(history.fields.file_field._update_filename, *(), **{'path': 'sources/'})),
        ),
    ]
