# Generated by Django 3.0.2 on 2020-02-12 13:09

from django.db import migrations
import functools
import history.fields.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0129_auto_20200212_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='file',
            field=history.fields.file_field.SourceFileField(blank=True, null=True, upload_to=functools.partial(history.fields.file_field._update_filename, *(), **{'path': 'sources/'})),
        ),
    ]
