# Generated by Django 3.0.2 on 2020-02-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0130_auto_20200212_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationvolume',
            name='file',
        ),
        migrations.RemoveField(
            model_name='publicationvolume',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='article',
            name='number',
        ),
        migrations.RemoveField(
            model_name='article',
            name='volume',
        ),
        migrations.DeleteModel(
            name='PublicationNumber',
        ),
        migrations.DeleteModel(
            name='PublicationVolume',
        ),
    ]
