# Generated by Django 3.0.2 on 2020-02-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0131_auto_20200212_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='number_number',
            new_name='number',
        ),
    ]
