# Generated by Django 3.0.2 on 2020-02-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0133_auto_20200212_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sources.Source')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('editors', models.CharField(blank=True, max_length=100, null=True)),
                ('website_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('sources.source', models.Model),
        ),
    ]
