# Generated by Django 3.0.2 on 2020-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0134_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
