# Generated by Django 3.0.2 on 2020-02-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0135_speech_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='topic',
        ),
    ]
