# Generated by Django 3.0.2 on 2020-02-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0023_auto_20200203_1435'),
        ('occurrences', '0044_occurrence_postscript'),
        ('quotes', '0030_auto_20200211_0739'),
        ('sources', '0136_remove_speech_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
