# Generated by Django 3.0.2 on 2020-02-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0137_delete_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='type',
            field=models.CharField(choices=[('letter', 'letter'), ('memorandum', 'memorandum')], default='letter', max_length=10),
        ),
    ]
