# Generated by Django 3.0.2 on 2020-02-16 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0138_letter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='source',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
