# Generated by Django 3.0.2 on 2020-02-16 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0140_remove_source_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
