# Generated by Django 3.0.2 on 2020-02-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0143_auto_20200216_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
