# Generated by Django 3.0.2 on 2020-02-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0144_book_translator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='type',
            new_name='type2',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='type',
            new_name='type2',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='type',
            new_name='type2',
        ),
        migrations.RenameField(
            model_name='speech',
            old_name='type',
            new_name='type2',
        ),
    ]
