# Generated by Django 3.0.2 on 2020-02-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0145_auto_20200217_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecontainment',
            name='phrase',
            field=models.CharField(blank=True, choices=[('', '-----'), ('cited', 'cited'), ('copy', 'copy'), ('quoted', 'quoted'), ('reproduced', 'reproduced'), ('transcribed', 'transcribed')], default='', max_length=12),
        ),
    ]
