# Generated by Django 3.0.2 on 2020-02-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0146_auto_20200220_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
