# Generated by Django 3.0.2 on 2020-02-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0147_webpage_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='first_page_number',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='page_offset',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
