# Generated by Django 3.0.2 on 2020-02-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0148_auto_20200221_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='date_is_circa',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
