# Generated by Django 3.0.2 on 2020-02-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0149_source_date_is_circa'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='hidden',
            field=models.BooleanField(default=False, help_text="Don't let this item appear in search results."),
        ),
    ]
