# Generated by Django 3.0.2 on 2020-02-24 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0151_auto_20200224_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sources.Source')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('editors', models.CharField(blank=True, max_length=100, null=True)),
                ('source_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='sources.Book', verbose_name='book')),
            ],
            options={
                'abstract': False,
            },
            bases=('sources.source', models.Model),
        ),
    ]
