# Generated by Django 3.0.2 on 2020-02-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0152_chapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceTag',
        ),
    ]
