# Generated by Django 3.0.2 on 2020-02-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0153_delete_sourcetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='citations',
        ),
    ]
