# Generated by Django 3.0.2 on 2020-02-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0154_remove_source_citations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='source_book',
        ),
    ]
