# Generated by Django 3.0.2 on 2020-02-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0155_remove_chapter_source_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecontainment',
            name='phrase',
            field=models.CharField(blank=True, choices=[('', '-----'), ('archived', 'archived'), ('cited', 'cited'), ('copy', 'copy'), ('quoted', 'quoted'), ('recorded', 'recorded'), ('reproduced', 'reproduced'), ('transcribed', 'transcribed')], default='', max_length=12),
        ),
    ]
