# Generated by Django 3.0.2 on 2020-02-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0156_auto_20200225_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcefactderivation',
            name='notes',
        ),
    ]
