# Generated by Django 3.0.2 on 2020-02-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0157_remove_sourcefactderivation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='type2',
            field=models.CharField(choices=[('chapter', 'Chapter'), ('section', 'Section')], default='chapter', max_length=7),
        ),
    ]
