# Generated by Django 3.0.2 on 2020-03-01 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0158_chapter_type2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affidavit',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sources.Source')),
                ('editors', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_number', models.PositiveSmallIntegerField(blank=True, help_text='aka acquisition number', null=True)),
                ('location_info', models.CharField(blank=True, help_text='Ex: John H. Alexander Papers, Series 1: Correspondence, 1831-1848, Folder 1', max_length=400, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affidavit', to='sources.Collection')),
            ],
            options={
                'abstract': False,
            },
            bases=('sources.source', models.Model),
        ),
    ]
