# Generated by Django 3.0.2 on 2020-03-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0159_affidavit'),
    ]

    operations = [
        migrations.AddField(
            model_name='affidavit',
            name='certifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
