# Generated by Django 3.0.2 on 2020-03-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0162_auto_20200303_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.Journal'),
        ),
    ]
