# Generated by Django 3.0.2 on 2020-03-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0163_auto_20200303_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='journal',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
