# Generated by Django 3.0.2 on 2020-03-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0164_auto_20200303_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name_plural': 'Journal entries'},
        ),
    ]
