# Generated by Django 3.0.2 on 2020-03-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0165_auto_20200304_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='type2',
            field=models.CharField(choices=[('email', 'email'), ('letter', 'letter'), ('memorandum', 'memorandum')], default='letter', max_length=10),
        ),
    ]
