# Generated by Django 3.0.2 on 2020-03-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0166_auto_20200304_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'verbose_name': 'Correspondence', 'verbose_name_plural': 'Correspondence'},
        ),
    ]
