# Generated by Django 3.0.2 on 2020-03-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0167_auto_20200304_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'verbose_name': 'correspondence', 'verbose_name_plural': 'correspondence'},
        ),
    ]
