# Generated by Django 3.0.4 on 2020-03-06 11:53

from django.db import migrations
import functools
import history.fields.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0168_auto_20200304_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='file',
            field=history.fields.file_field.SourceFileField(blank=True, null=True, unique=True, upload_to=functools.partial(history.fields.file_field._update_filename, *(), **{'path': 'sources/'})),
        ),
    ]
