# Generated by Django 3.0.4 on 2020-03-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0169_auto_20200306_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
