# Generated by Django 3.1.13 on 2021-07-27 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='creator',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='untitled', max_length=200, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='creator',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='title',
            field=models.CharField(default='untitled', max_length=200, verbose_name='title'),
            preserve_default=False,
        ),
    ]
