# Generated by Django 3.1.13 on 2021-07-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20210730_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='issues_resolved',
            field=models.ManyToManyField(
                blank=True, related_name='pull_requests', to='cms.Issue'
            ),
        ),
    ]
