# Generated by Django 3.1.13 on 2021-07-30 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0004_pullrequest_issues_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='source_branch',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to='cms.branch'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='target_branch',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='pull_requests',
                to='cms.branch',
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'pull_request',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviews',
                        to='cms.pullrequest',
                    ),
                ),
                (
                    'reviewer',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='cms_reviews',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
