# Generated by Django 3.1.13 on 2021-07-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20210730_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='number',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='number',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
