# Generated by Django 3.1.9 on 2021-05-20 20:08

import autoslug.fields
import concurrency.fields
from django.db import migrations, models

import apps.dates.fields
import core.fields
import core.fields.html_field
import core.fields.json_field
import core.fields.sorted_m2m_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('places', '0003_auto_20210519_1729'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    'citation_phrase',
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, '-------'),
                            ('quoted in', 'quoted in'),
                            ('cited in', 'cited in'),
                            ('partially reproduced in', 'partially reproduced in'),
                        ],
                        default=None,
                        max_length=25,
                        null=True,
                    ),
                ),
                ('citation_html', models.TextField(blank=True, null=True)),
                ('pages', core.fields.json_field.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypedProposition',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('propositions.proposition', 'proposition'),
                            ('propositions.occurrence', 'occurrence'),
                            ('propositions.birth', 'birth'),
                            ('propositions.death', 'death'),
                            ('propositions.publication', 'publication'),
                            ('propositions.verbalization', 'verbalization'),
                        ],
                        db_index=True,
                        max_length=255,
                    ),
                ),
                (
                    'cache',
                    core.fields.json_field.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    'slug',
                    autoslug.fields.AutoSlugField(
                        blank=True,
                        editable=True,
                        null=True,
                        populate_from='get_slug',
                        unique=True,
                        verbose_name='slug',
                    ),
                ),
                (
                    'date_is_circa',
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text='whether the date is estimated/imprecise',
                        verbose_name='date is circa',
                    ),
                ),
                (
                    'date',
                    apps.dates.fields.HistoricDateTimeField(
                        null=True, verbose_name='date'
                    ),
                ),
                (
                    'end_date',
                    apps.dates.fields.HistoricDateTimeField(
                        blank=True, null=True, verbose_name='end date'
                    ),
                ),
                (
                    'verified',
                    models.BooleanField(default=False, verbose_name='verified'),
                ),
                (
                    'title',
                    models.CharField(
                        blank=True,
                        help_text='The title can be used for the detail page header and title tag, SERP result card header, etc.',
                        max_length=120,
                        null=True,
                        verbose_name='title',
                    ),
                ),
                (
                    'hidden',
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text='Hide this item from search results.',
                    ),
                ),
                (
                    'version',
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text='record revision number'
                    ),
                ),
                (
                    'notes',
                    core.fields.HTMLField(
                        blank=True,
                        null=True,
                        paragraphed=True,
                        processed=False,
                        processor=None,
                        verbose_name='note',
                    ),
                ),
                (
                    'summary',
                    core.fields.HTMLField(
                        paragraphed=False,
                        processed=False,
                        processor=None,
                        unique=True,
                        verbose_name='summary',
                    ),
                ),
                (
                    'elaboration',
                    core.fields.HTMLField(
                        null=True,
                        paragraphed=True,
                        processed=True,
                        processor=core.fields.html_field.process,
                        verbose_name='elaboration',
                    ),
                ),
                (
                    'certainty',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'No credible evidence'),
                            (1, 'Some credible evidence'),
                            (2, 'A preponderance of evidence'),
                            (3, 'Beyond reasonable doubt'),
                            (4, 'Beyond any shadow of a doubt'),
                        ],
                        null=True,
                        verbose_name='certainty',
                    ),
                ),
                (
                    'postscript',
                    core.fields.HTMLField(
                        blank=True,
                        help_text='Content to be displayed below all related data',
                        null=True,
                        paragraphed=True,
                        processed=True,
                        processor=core.fields.html_field.process,
                        verbose_name='postscript',
                    ),
                ),
                (
                    'images',
                    core.fields.sorted_m2m_field.SortedManyToManyField(
                        blank=True,
                        help_text=None,
                        related_name='typedproposition_set',
                        sort_value_field_name='position',
                        to='images.Image',
                        verbose_name='images',
                    ),
                ),
                (
                    'locations',
                    core.fields.sorted_m2m_field.SortedManyToManyField(
                        blank=True,
                        help_text=None,
                        related_name='typedproposition_set',
                        sort_value_field_name='position',
                        to='places.Place',
                        verbose_name='locations',
                    ),
                ),
                (
                    'premises',
                    models.ManyToManyField(
                        related_name='conclusions',
                        through='propositions.Support',
                        to='propositions.TypedProposition',
                        verbose_name='premises',
                    ),
                ),
                (
                    'related_entities',
                    models.ManyToManyField(
                        blank=True,
                        related_name='typedproposition_set',
                        to='entities.Entity',
                        verbose_name='related entities',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
