# Generated by Django 3.1.9 on 2021-05-20 20:08

from django.db import migrations

import apps.quotes.models.model_with_related_quotes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propositions', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polymorphicproposition',
            name='related_quotes',
            field=apps.quotes.models.model_with_related_quotes.RelatedQuotesField(
                blank=True,
                related_name='new_propositions',
                through='propositions.QuoteRelation',
                to='quotes.Quote',
                verbose_name='related quotes',
            ),
        ),
    ]
