# Generated by Django 3.1.9 on 2021-05-14 18:15

from django.db import migrations, models

import core.fields
import core.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_auto_20210514_1815'),
        ('propositions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='_elaboration',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='_summary',
        ),
        migrations.AddField(
            model_name='proposition',
            name='elaboration',
            field=core.fields.HTMLField(
                null=True,
                paragraphed=True,
                processed=True,
                processor=core.fields.html_field.process,
                verbose_name='elaboration',
            ),
        ),
        migrations.AddField(
            model_name='proposition',
            name='summary',
            field=core.fields.HTMLField(
                default='',
                paragraphed=False,
                processed=False,
                processor=None,
                unique=True,
                verbose_name='summary',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposition',
            name='related_entities',
            field=models.ManyToManyField(
                blank=True,
                related_name='proposition_set',
                to='entities.Entity',
                verbose_name='related entities',
            ),
        ),
    ]
