# Generated by Django 3.1.9 on 2021-05-20 20:08

import django.db.models.deletion
from django.db import migrations, models

import apps.sources.models.model_with_sources
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propositions', '0002_polymorphicproposition_related_quotes'),
        ('sources', '0001_initial'),
        ('topics', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polymorphicproposition',
            name='sources',
            field=apps.sources.models.model_with_sources.SourcesField(
                blank=True,
                related_name='new_propositions',
                through='propositions.Citation',
                to='sources.Source',
                verbose_name='sources',
            ),
        ),
        migrations.AddField(
            model_name='polymorphicproposition',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='polymorphicproposition_set',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
        migrations.AddField(
            model_name='support',
            name='conclusion',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='conclusion_supports',
                to='propositions.polymorphicproposition',
            ),
        ),
        migrations.AddField(
            model_name='support',
            name='premise',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='supports',
                to='propositions.polymorphicproposition',
            ),
        ),
        migrations.AddField(
            model_name='quoterelation',
            name='new_content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quote_relations',
                to='propositions.polymorphicproposition',
                verbose_name='proposition',
            ),
        ),
        migrations.AddField(
            model_name='quoterelation',
            name='quote',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='propositions_quoterelations',
                to='quotes.quote',
            ),
        ),
        migrations.AddField(
            model_name='citation',
            name='new_content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='citations',
                to='propositions.polymorphicproposition',
                verbose_name='proposition',
            ),
        ),
        migrations.AddField(
            model_name='citation',
            name='source',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='propositions_citations',
                to='sources.source',
            ),
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[],
            options={
                'ordering': ['date'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.polymorphicproposition',),
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.polymorphicproposition',),
        ),
        migrations.CreateModel(
            name='Birth',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.occurrence',),
        ),
        migrations.CreateModel(
            name='Death',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.occurrence',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.occurrence',),
        ),
        migrations.CreateModel(
            name='Verbalization',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.occurrence',),
        ),
    ]
