# Generated by Django 3.1.9 on 2021-05-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0002_auto_20210514_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='polymorphicproposition_ptr',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='premises',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='related_entities',
        ),
        migrations.RemoveField(
            model_name='support',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='support',
            name='premise',
        ),
        migrations.DeleteModel(
            name='PolymorphicProposition',
        ),
        migrations.DeleteModel(
            name='Proposition',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
