# Generated by Django 3.1.9 on 2021-05-15 20:32

import autoslug.fields
import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models

import core.fields
import core.fields.html_field
import core.fields.json_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0014_auto_20210514_1815'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('propositions', '0003_auto_20210514_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'computations',
                    core.fields.json_field.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    'slug',
                    autoslug.fields.AutoSlugField(
                        blank=True,
                        editable=True,
                        null=True,
                        populate_from='get_slug',
                        unique=True,
                        verbose_name='slug',
                    ),
                ),
                (
                    'verified',
                    models.BooleanField(default=False, verbose_name='verified'),
                ),
                (
                    'title',
                    models.CharField(
                        blank=True,
                        help_text='The title can be used for the detail page header and title tag, SERP result card header, etc.',
                        max_length=120,
                        null=True,
                        verbose_name='title',
                    ),
                ),
                (
                    'hidden',
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text='Hide this item from search results.',
                    ),
                ),
                (
                    'version',
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text='record revision number'
                    ),
                ),
                (
                    'notes',
                    core.fields.HTMLField(
                        blank=True,
                        null=True,
                        paragraphed=True,
                        processed=False,
                        processor=None,
                    ),
                ),
                (
                    'summary',
                    core.fields.HTMLField(
                        paragraphed=False,
                        processed=False,
                        processor=None,
                        unique=True,
                        verbose_name='summary',
                    ),
                ),
                (
                    'elaboration',
                    core.fields.HTMLField(
                        null=True,
                        paragraphed=True,
                        processed=True,
                        processor=core.fields.html_field.process,
                        verbose_name='elaboration',
                    ),
                ),
                (
                    'certainty',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'No credible evidence'),
                            (1, 'Some credible evidence'),
                            (2, 'A preponderance of evidence'),
                            (3, 'Beyond reasonable doubt'),
                            (4, 'Beyond any shadow of a doubt'),
                        ],
                        null=True,
                        verbose_name='certainty',
                    ),
                ),
                (
                    'polymorphic_ctype',
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='polymorphic_propositions.proposition_set+',
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    'conclusion',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='conclusion_supports',
                        to='propositions.proposition',
                    ),
                ),
                (
                    'premise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='supports',
                        to='propositions.proposition',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='proposition',
            name='premises',
            field=models.ManyToManyField(
                related_name='conclusions',
                through='propositions.Support',
                to='propositions.Proposition',
                verbose_name='premises',
            ),
        ),
        migrations.AddField(
            model_name='proposition',
            name='related_entities',
            field=models.ManyToManyField(
                blank=True,
                related_name='proposition_set',
                to='entities.Entity',
                verbose_name='related entities',
            ),
        ),
    ]
