# Generated by Django 3.1.12 on 2021-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0003_auto_20210604_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='type',
            field=models.CharField(
                choices=[
                    ('propositions.conclusion', 'conclusion'),
                    ('propositions.occurrence', 'occurrence'),
                    ('propositions.birth', 'birth'),
                    ('propositions.death', 'death'),
                    ('propositions.publication', 'publication'),
                    ('composition', 'Composition'),
                    ('speech', 'Speech'),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
    ]
