# Generated by Django 3.1.11 on 2021-05-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0004_remove_polymorphicproposition_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='new_content_object',
            new_name='content_object',
        ),
        migrations.RenameField(
            model_name='quoterelation',
            old_name='new_content_object',
            new_name='content_object',
        ),
    ]
