# Generated by Django 3.1.9 on 2021-05-15 21:38

from django.db import migrations, models

import core.fields.sorted_m2m_field


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_auto_20210514_1815'),
        ('topics', '0003_auto_20210428_2009'),
        ('propositions', '0004_auto_20210515_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='new_citations',
            field=core.fields.sorted_m2m_field.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name='proposition_set',
                sort_value_field_name='position',
                to='sources.Source',
                verbose_name='citations',
            ),
        ),
        migrations.AddField(
            model_name='proposition',
            name='new_tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='proposition_set',
                to='topics.Topic',
                verbose_name='citations',
            ),
        ),
    ]
