# Generated by Django 3.1.11 on 2021-05-21 13:34

import django.db.models.deletion
from django.db import migrations

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_quote_version'),
        ('sources', '0001_initial'),
        ('propositions', '0006_auto_20210521_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='propositions_citation_set',
                to='sources.source',
            ),
        ),
        migrations.AlterField(
            model_name='quoterelation',
            name='quote',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='propositions_quoterelation_set',
                to='quotes.quote',
            ),
        ),
    ]
