# Generated by Django 3.1.9 on 2021-05-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0007_auto_20210516_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='sources',
        ),
    ]
