# Generated by Django 3.1.11 on 2021-05-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0007_auto_20210521_1334'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.UniqueConstraint(
                fields=('source', 'content_object', 'position'),
                name='propositions_citation_unique_positions',
            ),
        ),
    ]
