# Generated by Django 3.1.11 on 2021-05-22 15:58

from django.db import migrations

import apps.dates.fields


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0008_auto_20210522_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedproposition',
            name='date',
            field=apps.dates.fields.HistoricDateTimeField(
                blank=True, null=True, verbose_name='date'
            ),
        ),
    ]
