# Generated by Django 3.1.9 on 2021-05-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_auto_20210516_0543'),
        ('propositions', '0008_remove_proposition_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='sources',
            field=models.ManyToManyField(
                blank=True,
                related_name='proposition_citations',
                through='propositions.PropositionCitation',
                to='sources.Source',
                verbose_name='sources',
            ),
        ),
    ]
