# Generated by Django 3.1.12 on 2021-06-10 21:57

from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0008_collectioninclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallacy',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=40)),
                (
                    'description',
                    core.fields.HTMLField(
                        blank=True,
                        paragraphed=True,
                        processed=False,
                        processor=None,
                        verbose_name='description',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='FallacyIdentification',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='argumentsupport',
            unique_together={('position', 'argument'), ('argument', 'premise')},
        ),
    ]
