# Generated by Django 3.1.9 on 2021-05-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0010_auto_20210517_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propositioncitation',
            old_name='proposition',
            new_name='content_object',
        ),
    ]
