# Generated by Django 3.1.11 on 2021-05-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0012_auto_20210525_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymorphicproposition',
            name='type',
            field=models.CharField(
                choices=[
                    ('propositions.proposition', 'proposition'),
                    ('propositions.occurrence', 'occurrence'),
                    ('propositions.birth', 'birth'),
                    ('propositions.death', 'death'),
                    ('propositions.publication', 'publication'),
                    ('propositions.verbalization', 'verbalization'),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
    ]
