# Generated by Django 3.1.9 on 2021-05-17 16:54

import django.db.models.deletion
from django.db import migrations, models

import core.fields.json_field
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0030_auto_20210517_1654'),
        ('sources', '0013_auto_20210517_1459'),
        ('propositions', '0013_auto_20210517_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    'citation_phrase',
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, '-------'),
                            ('quoted in', 'quoted in'),
                            ('cited in', 'cited in'),
                            ('partially reproduced in', 'partially reproduced in'),
                        ],
                        default=None,
                        max_length=25,
                        null=True,
                    ),
                ),
                ('citation_html', models.TextField(blank=True, null=True)),
                ('pages', core.fields.json_field.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='sources',
        ),
        migrations.DeleteModel(
            name='PropositionCitation',
        ),
        migrations.AddField(
            model_name='quoterelation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quote_relations',
                to='propositions.proposition',
            ),
        ),
        migrations.AddField(
            model_name='quoterelation',
            name='quote',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='propositions_quoterelations',
                to='quotes.quote',
            ),
        ),
        migrations.AddField(
            model_name='citation',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='citations',
                to='propositions.proposition',
            ),
        ),
        migrations.AddField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='citation_citations',
                to='sources.source',
            ),
        ),
    ]
