# Generated by Django 3.1.12 on 2021-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0013_auto_20210627_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='certainty',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (None, '-------'),
                    (0, 'No credible evidence'),
                    (1, 'Some credible evidence'),
                    (2, 'A preponderance of evidence'),
                    (3, 'Beyond reasonable doubt'),
                    (4, 'Beyond any shadow of a doubt'),
                ],
                null=True,
                verbose_name='certainty',
            ),
        ),
    ]
