# Generated by Django 3.1.9 on 2021-05-17 17:53

import django.db.models.deletion
from django.db import migrations

import apps.sources.models.model_with_sources
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0013_auto_20210517_1459'),
        ('propositions', '0014_auto_20210517_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='sources',
            field=apps.sources.models.model_with_sources.SourcesField(
                blank=True,
                related_name='proposition_set',
                through='propositions.Citation',
                to='sources.Source',
                verbose_name='sources',
            ),
        ),
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='propositions_citations',
                to='sources.source',
            ),
        ),
    ]
