# Generated by Django 3.1.13 on 2021-07-27 03:01

import django.db.models.deletion
from django.db import migrations, models

import apps.cms.models
import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('propositions', '0014_auto_20210628_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modification',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'content_object',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='modifications',
                        to='propositions.proposition',
                        verbose_name='proposition',
                    ),
                ),
                (
                    'pull_request',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='cms.pullrequest'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='proposition',
            name='pull_requests',
            field=apps.cms.models.PullRequestsField(
                blank=True,
                related_name='proposition_set',
                through='propositions.Modification',
                to='cms.PullRequest',
                verbose_name='pull requests',
            ),
        ),
    ]
