# Generated by Django 3.1.11 on 2021-05-28 22:23

import autoslug.fields
from django.db import migrations, models

import core.fields
import core.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0015_convert_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='citation_html',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citation',
            name='citation_phrase',
            field=models.CharField(
                blank=True,
                choices=[
                    (None, '-------'),
                    ('quoted in', 'quoted in'),
                    ('cited in', 'cited in'),
                    ('partially reproduced in', 'partially reproduced in'),
                ],
                default=None,
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name='typedproposition',
            name='elaboration',
            field=core.fields.HTMLField(
                default='',
                paragraphed=True,
                processed=True,
                processor=core.fields.html_field.process,
                verbose_name='elaboration',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typedproposition',
            name='postscript',
            field=core.fields.HTMLField(
                blank=True,
                default='',
                help_text='Content to be displayed below all related data',
                paragraphed=True,
                processed=True,
                processor=core.fields.html_field.process,
                verbose_name='postscript',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typedproposition',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                blank=True,
                default='',
                editable=True,
                populate_from='get_slug',
                unique=True,
                verbose_name='slug',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typedproposition',
            name='title',
            field=models.CharField(
                blank=True,
                default='',
                help_text='The title can be used for the detail page header and title tag, SERP result card header, etc. It should be a noun phrase!',
                max_length=120,
                verbose_name='title',
            ),
            preserve_default=False,
        ),
    ]
