# Generated by Django 3.1.9 on 2021-05-17 18:11

from django.db import migrations

import apps.quotes.models.model_with_related_quotes


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0031_auto_20210517_1753'),
        ('propositions', '0015_auto_20210517_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='related_quotes',
            field=apps.quotes.models.model_with_related_quotes.RelatedQuotesField(
                blank=True,
                related_name='proposition_set',
                through='propositions.QuoteRelation',
                to='quotes.Quote',
                verbose_name='related quotes',
            ),
        ),
    ]
