# Generated by Django 3.1.9 on 2021-05-17 18:52

from django.db import migrations

import apps.quotes.models.model_with_related_quotes
import apps.sources.models.model_with_sources


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0032_auto_20210517_1811'),
        ('sources', '0013_auto_20210517_1459'),
        ('propositions', '0016_proposition_related_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='related_quotes',
            field=apps.quotes.models.model_with_related_quotes.RelatedQuotesField(
                blank=True,
                related_name='propositions',
                through='propositions.QuoteRelation',
                to='quotes.Quote',
                verbose_name='related quotes',
            ),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='sources',
            field=apps.sources.models.model_with_sources.SourcesField(
                blank=True,
                related_name='propositions',
                through='propositions.Citation',
                to='sources.Source',
                verbose_name='sources',
            ),
        ),
    ]
