# Generated by Django 3.1.11 on 2021-05-29 03:38

import django.db.models.deletion
from django.db import migrations

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0017_auto_20210529_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polymorphicproposition',
            old_name='_locations',
            new_name='locations',
        ),
        migrations.AlterField(
            model_name='location',
            name='content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='location_relations',
                to='propositions.polymorphicproposition',
                verbose_name='proposition',
            ),
        ),
    ]
