# Generated by Django 3.1.13 on 2021-08-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0017_auto_20210820_2138'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='argument',
            managers=[],
        ),
        migrations.AlterModelManagers(
            name='argumentsupport',
            managers=[],
        ),
        migrations.AlterModelManagers(
            name='citation',
            managers=[],
        ),
        migrations.AlterModelManagers(
            name='fallacyidentification',
            managers=[],
        ),
        migrations.AlterModelManagers(
            name='imagerelation',
            managers=[],
        ),
        migrations.AlterModelManagers(
            name='location',
            managers=[],
        ),
        migrations.AlterModelManagers(
            name='premisegroup',
            managers=[],
        ),
        migrations.AlterModelManagers(
            name='premisegroupinclusion',
            managers=[],
        ),
        migrations.AlterModelManagers(
            name='quoterelation',
            managers=[],
        ),
        migrations.RemoveField(
            model_name='fallacyidentification',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='quoterelation',
            name='deleted',
        ),
        migrations.AddField(
            model_name='argument',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='argumentsupport',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='citation',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='imagerelation',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='location',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='premisegroup',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='premisegroupinclusion',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
