# Generated by Django 3.1.13 on 2021-08-21 05:30

from typing import TYPE_CHECKING

import django.db.models.deletion
from django.db import migrations, models

import apps.topics.models.taggable
import core.fields.m2m_foreign_key

if TYPE_CHECKING:
    from apps.propositions.models.proposition import Proposition as _Proposition
    from apps.topics.models.topic import Topic


def forwards_func(apps, schema_editor):
    Proposition: type['_Proposition'] = apps.get_model('propositions', 'Proposition')
    TopicRelation = apps.get_model('propositions', 'TopicRelation')
    p: '_Proposition'
    for p in Proposition.objects.all():
        tag: 'Topic'
        for tag in p.tags.all():
            TopicRelation.objects.get_or_create(topic=tag, content_object=p)


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20210820_2138'),
        ('propositions', '0018_auto_20210821_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterelation',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='quoterelation',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='propositions_proposition_set',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
        migrations.CreateModel(
            name='TopicRelation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=0)),
                (
                    'content_object',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='topic_relations',
                        to='propositions.proposition',
                        verbose_name='proposition',
                    ),
                ),
                (
                    'topic',
                    core.fields.m2m_foreign_key.ManyToManyForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='propositions_topicrelation_set',
                        to='topics.topic',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='proposition',
            name='new_tags',
            field=apps.topics.models.taggable.TagsField(
                blank=True,
                related_name='proposition_set',
                through='propositions.TopicRelation',
                to='topics.Topic',
                verbose_name='tags',
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
