# Generated by Django 3.1.11 on 2021-05-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0019_remove_polymorphicproposition_old_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymorphicproposition',
            name='certainty',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (None, '-------'),
                    (1, 'Some credible evidence'),
                    (2, 'A preponderance of evidence'),
                    (3, 'Beyond reasonable doubt'),
                    (4, 'Beyond any shadow of a doubt'),
                ],
                null=True,
                verbose_name='certainty',
            ),
        ),
    ]
