# Generated by Django 3.1.11 on 2021-05-30 22:23

import django.db.models.deletion
from django.db import migrations, models

import core.fields


def convert_data(apps, schema_editor):
    Support = apps.get_model('propositions', 'Support')
    Argument = apps.get_model('propositions', 'Argument')
    ArgumentSupport = apps.get_model('propositions', 'ArgumentSupport')
    for support in Support.objects.all():
        proposition = support.conclusion
        argument = proposition.arguments.first() if proposition.arguments.exists() else ''
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0020_auto_20210530_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.PositiveSmallIntegerField(
                        choices=[(None, '-------'), (1, 'deductive'), (2, 'inductive')],
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    'explanation',
                    core.fields.HTMLField(
                        paragraphed=True,
                        processed=False,
                        processor=None,
                        verbose_name='explanation',
                    ),
                ),
                (
                    'conclusion',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='arguments',
                        to='propositions.polymorphicproposition',
                        verbose_name='conclusion',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArgumentSupport',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'position',
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    'argument',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='_supports',
                        to='propositions.argument',
                    ),
                ),
                (
                    'premise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='_argument_supports',
                        to='propositions.polymorphicproposition',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='argument',
            name='premises',
            field=models.ManyToManyField(
                related_name='supported_arguments',
                through='propositions.ArgumentSupport',
                to='propositions.PolymorphicProposition',
                verbose_name='premises',
            ),
        ),
        migrations.RunPython(convert_data, migrations.RunPython.noop),
    ]
