# Generated by Django 3.1.11 on 2021-05-31 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0021_auto_20210530_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='argumentsupport',
            options={'verbose_name': 'support'},
        ),
        migrations.RemoveField(
            model_name='polymorphicproposition',
            name='premises',
        ),
        migrations.AlterUniqueTogether(
            name='argumentsupport',
            unique_together={('argument', 'premise')},
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
