# Generated by Django 3.1.13 on 2021-08-22 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0021_remove_proposition_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='new_tags',
            new_name='tags',
        ),
    ]
