# Generated by Django 3.1.11 on 2021-05-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0022_auto_20210531_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='polymorphicproposition',
            name='date_string',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='date string'
            ),
        ),
    ]
