# Generated by Django 3.1.11 on 2021-06-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0023_polymorphicproposition_date_string'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verbalization',
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.occurrence',),
        ),
        migrations.AlterField(
            model_name='polymorphicproposition',
            name='type',
            field=models.CharField(
                choices=[
                    ('propositions.proposition', 'proposition'),
                    ('propositions.occurrence', 'occurrence'),
                    ('propositions.birth', 'birth'),
                    ('propositions.death', 'death'),
                    ('propositions.publication', 'publication'),
                    ('composition', 'Composition'),
                    ('speech', 'Speech'),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
    ]
