# Generated by Django 3.1.13 on 2021-08-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0025_auto_20210823_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='conflict',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
