# Generated by Django 3.1.9 on 2021-05-19 19:17

from django.db import migrations, models

import apps.dates.fields
import core.fields
import core.fields.html_field
import core.fields.json_field
import core.fields.sorted_m2m_field


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_auto_20210519_1917'),
        ('places', '0003_auto_20210519_1729'),
        ('propositions', '0026_auto_20210519_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[],
            options={
                'ordering': ['date'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.typedproposition',),
        ),
        migrations.AddField(
            model_name='typedproposition',
            name='_cached_images',
            field=core.fields.json_field.JSONField(default=list, editable=False),
        ),
        migrations.AddField(
            model_name='typedproposition',
            name='date',
            field=apps.dates.fields.HistoricDateTimeField(
                null=True, verbose_name='date'
            ),
        ),
        migrations.AddField(
            model_name='typedproposition',
            name='date_is_circa',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='whether the date is estimated/imprecise',
                verbose_name='date is circa',
            ),
        ),
        migrations.AddField(
            model_name='typedproposition',
            name='end_date',
            field=apps.dates.fields.HistoricDateTimeField(
                blank=True, null=True, verbose_name='end date'
            ),
        ),
        migrations.AddField(
            model_name='typedproposition',
            name='images',
            field=core.fields.sorted_m2m_field.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name='typedproposition_set',
                sort_value_field_name='position',
                to='images.Image',
                verbose_name='images',
            ),
        ),
        migrations.AddField(
            model_name='typedproposition',
            name='locations',
            field=core.fields.sorted_m2m_field.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name='typedproposition_set',
                sort_value_field_name='position',
                to='places.Place',
                verbose_name='locations',
            ),
        ),
        migrations.AddField(
            model_name='typedproposition',
            name='postscript',
            field=core.fields.HTMLField(
                blank=True,
                help_text='Content to be displayed below all related data',
                null=True,
                paragraphed=True,
                processed=True,
                processor=core.fields.html_field.process,
                verbose_name='postscript',
            ),
        ),
        migrations.AlterField(
            model_name='typedproposition',
            name='type',
            field=models.CharField(
                choices=[('propositions.occurrence', 'occurrence')],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
