# Generated by Django 3.1.11 on 2021-06-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0026_remove_polymorphicproposition_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polymorphicproposition',
            old_name='_images',
            new_name='images',
        ),
    ]
