# Generated by Django 3.1.11 on 2021-06-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0027_auto_20210603_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymorphicproposition',
            name='date_string',
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=100,
                null=True,
                verbose_name='date string',
            ),
        ),
    ]
