# Generated by Django 3.1.9 on 2021-05-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0027_auto_20210519_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProposition',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.typedproposition',),
        ),
        migrations.AlterField(
            model_name='typedproposition',
            name='type',
            field=models.CharField(
                choices=[
                    ('propositions.newproposition', 'new proposition'),
                    ('propositions.occurrence', 'occurrence'),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
