# Generated by Django 3.1.9 on 2021-05-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0028_auto_20210519_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='_cached_tags',
        ),
        migrations.RemoveField(
            model_name='typedproposition',
            name='_cached_tags',
        ),
    ]
