# Generated by Django 3.1.13 on 2021-08-26 23:07

import re

from django.db import migrations


def forwards_func(apps, schema_editor):
    Proposition = apps.get_model('propositions', 'Proposition')
    for p in Proposition.objects.all():
        elaboration = p.elaboration
        elaboration = re.sub(
            r'data-src="([^"]+?)" src="[^"]+?"',
            r'src="\g<1>" loading="lazy"',
            elaboration,
        )
        elaboration = re.sub(
            r'src="[^"]+?".+?\s+data-src="([^"]+?)"',
            r'src="\g<1>" loading="lazy"',
            elaboration,
        )
        elaboration = re.sub(r'"(\.\.\/)+', '"/', elaboration)
        elaboration = re.sub(
            r'<figure>(<img [^>]+(style="max-width: \d+px); )',
            r'<figure \g<2>">\g<1>',
            elaboration,
        )
        # Avoid calling save()
        Proposition.objects.filter(pk=p.pk).update(elaboration=elaboration)


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0028_auto_20210824_1528'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
