# Generated by Django 3.1.9 on 2021-05-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0030_auto_20210520_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typedproposition',
            name='_cached_images',
        ),
    ]
