# Generated by Django 3.1.9 on 2021-05-20 18:07

import django.db.models.deletion
from django.db import migrations, models

import core.fields.m2m_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0036_auto_20210520_1807'),
        ('propositions', '0031_remove_typedproposition__cached_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.occurrence',),
        ),
        migrations.CreateModel(
            name='Death',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.occurrence',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.occurrence',),
        ),
        migrations.CreateModel(
            name='Verbalization',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('propositions.occurrence',),
        ),
        migrations.RemoveField(
            model_name='citation',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='quoterelation',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='support',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='support',
            name='premise',
        ),
        migrations.AlterField(
            model_name='citation',
            name='new_content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='citations',
                to='propositions.typedproposition',
                verbose_name='proposition',
            ),
        ),
        migrations.AlterField(
            model_name='quoterelation',
            name='new_content_object',
            field=core.fields.m2m_foreign_key.ManyToManyForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quote_relations',
                to='propositions.typedproposition',
                verbose_name='proposition',
            ),
        ),
        migrations.AlterField(
            model_name='typedproposition',
            name='type',
            field=models.CharField(
                choices=[
                    ('propositions.newproposition', 'new proposition'),
                    ('propositions.occurrence', 'occurrence'),
                    ('propositions.birth', 'birth'),
                    ('propositions.death', 'death'),
                    ('propositions.publication', 'publication'),
                    ('propositions.verbalization', 'verbalization'),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name='Proposition',
        ),
    ]
