# Generated by Django 3.1.9 on 2021-05-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0032_auto_20210520_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='new_premise',
            new_name='premise',
        ),
    ]
