# Generated by Django 3.1.9 on 2021-05-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0033_auto_20210520_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='new_conclusion',
            new_name='conclusion',
        ),
        migrations.AlterField(
            model_name='support',
            name='premise',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='supports',
                to='propositions.typedproposition',
            ),
        ),
    ]
