# Generated by Django 3.1.9 on 2021-05-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0034_auto_20210520_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='conclusion',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='conclusion_supports',
                to='propositions.typedproposition',
            ),
        ),
    ]
