# Generated by Django 3.1.9 on 2021-05-20 18:33

from django.db import migrations, models


def update_types(apps, schema_editor):
    TypedProposition = apps.get_model('propositions', 'TypedProposition')
    TypedProposition.objects.filter(type='propositions.newproposition').update(
        type='propositions.proposition'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0035_auto_20210520_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewProposition',
            new_name='Proposition',
        ),
        migrations.AlterField(
            model_name='typedproposition',
            name='type',
            field=models.CharField(
                choices=[
                    ('propositions.proposition', 'proposition'),
                    ('propositions.occurrence', 'occurrence'),
                    ('propositions.birth', 'birth'),
                    ('propositions.death', 'death'),
                    ('propositions.publication', 'publication'),
                    ('propositions.verbalization', 'verbalization'),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.RunPython(update_types),
    ]
