# Generated by Django 3.1.2 on 2020-10-16 18:21

from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields
import modularhistory.fields
import modularhistory.fields.historic_datetime_field
import modularhistory.fields.json_field
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_is_circa', models.BooleanField(blank=True, default=False)),
                ('computations', modularhistory.fields.json_field.JSONField(blank=True, default=dict, null=True)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('hidden', models.BooleanField(blank=True, default=False, help_text="Don't let this item appear in search results.")),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', modularhistory.fields.HTMLField(verbose_name='Text')),
                ('bite', modularhistory.fields.HTMLField(blank=True, null=True, verbose_name='Bite')),
                ('pretext', modularhistory.fields.HTMLField(blank=True, help_text='Content to be displayed before the quote', null=True, verbose_name='Pretext')),
                ('context', modularhistory.fields.HTMLField(blank=True, help_text='Content to be displayed after the quote', null=True, verbose_name='Context')),
                ('date', modularhistory.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='Determines the order of quotes.', null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='quotes.quote')),
            ],
            options={
                'ordering': ['position', 'quote'],
                'unique_together': {('quote', 'content_type', 'object_id', 'position')},
            },
        ),
        migrations.CreateModel(
            name='QuoteBite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computations', modularhistory.fields.json_field.JSONField(blank=True, default=dict, null=True)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bites', to='quotes.quote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteAttribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('attributee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_attributions', to='entities.entity')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='quotes.quote')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('quote', 'attributee')},
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='attributees',
            field=models.ManyToManyField(blank=True, related_name='quotes', through='quotes.QuoteAttribution', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='quote',
            name='related',
            field=gm2m.fields.GM2MField('occurrences.Occurrence', 'entities.Entity', 'quotes.Quote', blank=True, related_name='related_quotes', through='quotes.QuoteRelation', through_fields=['quote', 'content_object', 'content_type', 'object_id']),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('date', 'bite')},
        ),
    ]
