# Generated by Django 3.0.1 on 2019-12-22 11:00

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('sources', '0001_initial'),
        ('occurrences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('context', tinymce.models.HTMLField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('attributee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='people.Person')),
                ('source', models.ManyToManyField(related_name='quotes', to='sources.Source')),
                ('year', models.ManyToManyField(blank=True, related_name='quotes', to='occurrences.Year')),
            ],
        ),
    ]
