# Generated by Django 3.0.4 on 2020-03-13 00:04

from django.db import migrations, models
import django.db.models.deletion
import history.fields.historic_datetime_field
import history.fields.html_field
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_is_circa', models.BooleanField(blank=True, default=False)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('hidden', models.BooleanField(blank=True, default=False, help_text="Don't let this item appear in search results.")),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', history.fields.HTMLField()),
                ('bite', history.fields.HTMLField(blank=True, null=True)),
                ('pretext', history.fields.HTMLField(blank=True, help_text='Content to be displayed before the quote', null=True)),
                ('context', history.fields.HTMLField(blank=True, help_text='Content to be displayed after the quote', null=True)),
                ('date', history.fields.HistoricDateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='QuoteBite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteSourceReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='reference position')),
                ('page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='quotes.Quote')),
            ],
            options={
                'ordering': ['source', 'page_number'],
            },
        ),
    ]
