# Generated by Django 3.0.5 on 2020-04-27 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='Determines the order of quotes.', null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='quotes.Quote')),
            ],
            options={
                'ordering': ['position', 'quote'],
                'unique_together': {('quote', 'content_type', 'object_id', 'position')},
            },
        ),
    ]
