# Generated by Django 3.1.2 on 2020-10-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='Set to 0 if the image is positioned manually.', null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.image')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_images', to='quotes.quote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='quotes', through='quotes.QuoteImage', to='images.Image'),
        ),
    ]
