# Generated by Django 3.0.4 on 2020-03-10 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('quotes', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesourcereference',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_from_quotes', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='quotebite',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bites', to='quotes.Quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='attributee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='quote',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='quotes', through='quotes.QuoteSourceReference', to='sources.Source'),
        ),
        migrations.AlterUniqueTogether(
            name='quotesourcereference',
            unique_together={('quote', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('date', 'attributee', 'bite')},
        ),
    ]
