# Generated by Django 3.1.2 on 2020-10-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_squashed_0014_quotebite_computations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotebite',
            name='end',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quotebite',
            name='start',
            field=models.PositiveIntegerField(),
        ),
    ]
