# Generated by Django 3.0.1 on 2019-12-28 21:12

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('occurrences', '0002_auto_20191228_2112'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('quotes', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesourcereference',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_from_quotes', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='quote',
            name='attributee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='quote',
            name='sources',
            field=models.ManyToManyField(blank=True, through='quotes.QuoteSourceReference', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='quotes.QuoteTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='quote',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='occurrences.Year'),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('slug', 'date')},
        ),
    ]
