# Generated by Django 3.0.1 on 2019-12-28 23:41

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20191228_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='context',
            field=history.fields.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=history.fields.HTMLField(),
        ),
    ]
