# Generated by Django 3.0.4 on 2020-03-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20200313_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotesourcereference',
            options={'ordering': ['source', 'page_number'], 'verbose_name': 'citation'},
        ),
    ]
