# Generated by Django 3.0.5 on 2020-04-27 22:44

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quotes', '0002_quoterelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='related',
            field=gm2m.fields.GM2MField('occurrences.Occurrence', blank=True, related_name='quotes', through='quotes.QuoteRelation', through_fields=['quote', 'content_object', 'content_type', 'object_id']),
        ),
    ]
