# Generated by Django 3.0.1 on 2019-12-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20191222_1246'),
        ('quotes', '0002_auto_20191222_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='source',
        ),
        migrations.CreateModel(
            name='QuoteSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('page_number', models.CharField(max_length=20)),
                ('notes', models.TextField(unique=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='quotes.Quote')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='sources.Source')),
            ],
        ),
    ]
