# Generated by Django 3.1.2 on 2020-10-20 07:04

from django.db import migrations

import modularhistory.fields.historic_datetime_field


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20201018_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=modularhistory.fields.historic_datetime_field.HistoricDateTimeField(
                null=True
            ),
        ),
    ]
