# Generated by Django 3.0.4 on 2020-03-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200317_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesourcereference',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='quotes.Quote'),
        ),
    ]
