# Generated by Django 3.0.5 on 2020-04-29 01:01

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quotes', '0003_quote_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='related',
            field=gm2m.fields.GM2MField('occurrences.Occurrence', 'entities.Entity', 'quotes.Quote', blank=True, related_name='related_quotes2', through='quotes.QuoteRelation', through_fields=['quote', 'content_object', 'content_type', 'object_id']),
        ),
    ]
