# Generated by Django 3.0.1 on 2019-12-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20191222_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesource',
            name='notes',
            field=models.TextField(),
        ),
    ]
