# Generated by Django 3.0.1 on 2019-12-29 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20191228_2157'),
        ('quotes', '0004_auto_20191229_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='attributee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='entities.Entity'),
        ),
    ]
