# Generated by Django 3.0.5 on 2020-04-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20200429_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='_attributee',
        ),
    ]
