# Generated by Django 3.0.1 on 2019-12-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20191222_1246'),
        ('quotes', '0004_auto_20191222_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='reference position')),
                ('page_number', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='quotes.Quote')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_references', to='sources.Source')),
            ],
        ),
        migrations.DeleteModel(
            name='QuoteSource',
        ),
    ]
