# Generated by Django 3.0.5 on 2020-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20200407_0910'),
        ('quotes', '0005_remove_quote__attributee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='attributees',
            field=models.ManyToManyField(blank=True, related_name='quotes', through='quotes.QuoteAttribution', to='entities.Entity'),
        ),
    ]
