# Generated by Django 3.1.3 on 2020-11-18 20:05

from django.db import migrations

import modularhistory.fields
import modularhistory.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20201031_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='context',
            field=modularhistory.fields.HTMLField(blank=True, help_text='Content to be displayed after the quote', null=True, paragraphed=True, processor=modularhistory.fields.html_field.process, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pretext',
            field=modularhistory.fields.HTMLField(blank=True, help_text='Content to be displayed before the quote', null=True, paragraphed=False, processor=modularhistory.fields.html_field.process, verbose_name='Pretext'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=modularhistory.fields.HTMLField(paragraphed=True, processor=modularhistory.fields.html_field.process, verbose_name='Text'),
        ),
    ]
