# Generated by Django 3.0.1 on 2019-12-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20191229_1721'),
        ('quotes', '0005_auto_20191229_0033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('date', 'attributee')},
        ),
        migrations.RemoveField(
            model_name='quote',
            name='slug',
        ),
    ]
