# Generated by Django 3.1.3 on 2020-11-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20201118_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
