# Generated by Django 3.0.4 on 2020-03-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('quotes', '0006_auto_20200319_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteAttribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_attributions', to='entities.Entity')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='quotes.Quote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='attributees',
            field=models.ManyToManyField(blank=True, related_name='quotes2', through='quotes.QuoteAttribution', to='entities.Entity'),
        ),
    ]
