# Generated by Django 3.0.1 on 2019-12-30 01:00

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20191229_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=history.fields.historic_datetime_field.HistoricDateTimeField(blank=True, null=True),
        ),
    ]
