# Generated by Django 3.0.4 on 2020-03-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20200323_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteattribution',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Set to 0 if the image is positioned manually.'),
        ),
    ]
