# Generated by Django 3.0.1 on 2019-12-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20191230_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesourcereference',
            name='end_page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
