# Generated by Django 3.0.4 on 2020-03-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('quotes', '0007_auto_20200323_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='attributee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_set', to='entities.Entity'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='attributees',
            field=models.ManyToManyField(blank=True, related_name='quotes', through='quotes.QuoteAttribution', to='entities.Entity'),
        ),
    ]
