# Generated by Django 3.0.10 on 2020-10-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20200503_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='db_citation_html',
            field=models.CharField(blank=True, max_length=1000, verbose_name='database string'),
        ),
    ]
