# Generated by Django 3.0.4 on 2020-03-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('quotes', '0008_quoteattribution_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteattribution',
            options={'ordering': ['position']},
        ),
        migrations.AlterUniqueTogether(
            name='quoteattribution',
            unique_together={('quote', 'attributee')},
        ),
    ]
