# Generated by Django 3.0.4 on 2020-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_auto_20200324_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteattribution',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
