# Generated by Django 3.0.4 on 2020-03-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_auto_20200324_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='attributee',
            new_name='_attributee',
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('date', 'bite')},
        ),
    ]
