# Generated by Django 3.0.1 on 2020-01-02 20:07

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_auto_20200101_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=history.fields.HistoricDateField(blank=True, null=True),
        ),
    ]
