# Generated by Django 3.0.10 on 2020-10-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_auto_20201013_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='db_attributee_html',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
