# Generated by Django 3.0.1 on 2020-01-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_auto_20200102_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
        migrations.AddField(
            model_name='quote',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotesourcereference',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
