# Generated by Django 3.0.10 on 2020-10-14 01:36

from django.db import migrations
import modularhistory.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_auto_20201013_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotebite',
            name='computations',
            field=modularhistory.fields.json_field.JSONField(blank=True, default=dict, null=True),
        ),
    ]
