# Generated by Django 3.0.1 on 2020-01-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_auto_20200103_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='quotesourcereference',
            name='verified',
        ),
    ]
