# Generated by Django 3.0.1 on 2020-01-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_auto_20200103_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesourcereference',
            name='source_type',
            field=models.CharField(blank=True, choices=[('P', 'Primary'), ('S', 'Secondary'), ('T', 'Tertiary')], max_length=3, null=True),
        ),
    ]
