# Generated by Django 3.0.1 on 2020-01-04 04:52

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_auto_20200104_0345'),
        ('quotes', '0015_auto_20200104_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='bite',
            field=history.fields.html_field.HTMLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('date', 'attributee', 'bite')},
        ),
    ]
