# Generated by Django 3.0.1 on 2020-01-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_auto_20200104_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='attributee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
