# Generated by Django 3.0.1 on 2020-01-24 15:15

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0017_quote_attributee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='datetime',
            field=history.fields.HistoricDateTimeField(blank=True, null=True),
        ),
    ]
