# Generated by Django 3.0.1 on 2020-01-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0021_auto_20200124_1507'),
        ('quotes', '0018_quote_datetime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('datetime', 'attributee', 'bite')},
        ),
        migrations.RemoveField(
            model_name='quote',
            name='date',
        ),
    ]
