# Generated by Django 3.0.1 on 2020-01-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0021_auto_20200124_1507'),
        ('quotes', '0019_auto_20200124_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('date', 'attributee', 'bite')},
        ),
    ]
