# Generated by Django 3.0.1 on 2020-01-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0073_auto_20200128_1846'),
        ('quotes', '0020_auto_20200124_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='quotes', through='quotes.QuoteSourceReference', to='sources.Source'),
        ),
        migrations.DeleteModel(
            name='QuoteTag',
        ),
    ]
