# Generated by Django 3.0.1 on 2020-01-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_auto_20200129_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotesourcereference',
            name='source_type',
        ),
    ]
