# Generated by Django 3.0.2 on 2020-02-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0022_auto_20200201_1734'),
        ('quotes', '0022_remove_quotesourcereference_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='attributee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='entities.Entity'),
        ),
    ]
