# Generated by Django 3.0.2 on 2020-02-02 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0093_auto_20200202_0226'),
        ('quotes', '0024_remove_quote_attributee_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotesourcereference',
            unique_together={('quote', 'source')},
        ),
    ]
