# Generated by Django 3.0.2 on 2020-02-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0025_auto_20200202_0226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotesourcereference',
            unique_together=set(),
        ),
    ]
