# Generated by Django 3.0.2 on 2020-02-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0027_auto_20200202_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='year',
        ),
    ]
