# Generated by Django 3.0.2 on 2020-02-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0028_remove_quote_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['date']},
        ),
    ]
