# Generated by Django 3.0.2 on 2020-02-11 07:39

from django.db import migrations
import history.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0029_auto_20200207_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pretext',
            field=history.fields.HTMLField(blank=True, help_text='Content to be displayed before the quote', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='context',
            field=history.fields.HTMLField(blank=True, help_text='Content to be displayed after the quote', null=True),
        ),
    ]
