# Generated by Django 3.0.2 on 2020-02-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0030_auto_20200211_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotesourcereference',
            options={'ordering': ['source', 'page_number']},
        ),
    ]
