# Generated by Django 3.0.2 on 2020-02-16 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0031_auto_20200214_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
