# Generated by Django 3.0.2 on 2020-02-16 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0035_auto_20200216_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
