# Generated by Django 3.0.2 on 2020-02-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0039_auto_20200224_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteBite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bites', to='quotes.Quote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
