# Generated by Django 3.0.2 on 2020-02-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0040_quotebite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotesourcereference',
            name='notes',
        ),
    ]
