# Generated by Django 3.1.3 on 2020-11-16 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('markup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='highlight',
            old_name='agent',
            new_name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='attribute_name',
            field=models.CharField(default='', help_text='The name of the attribute that maps to the interacted content', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='end',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='start',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highlight',
            name='attribute_name',
            field=models.CharField(default='', help_text='The name of the attribute that maps to the interacted content', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('attribute_name', models.CharField(help_text='The name of the attribute that maps to the interacted content', max_length=20)),
                ('before', models.TextField()),
                ('after', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
