# Generated by Django 3.1.13 on 2021-09-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                (
                    'enable_comments',
                    models.BooleanField(default=False, verbose_name='enable comments'),
                ),
                (
                    'registration_required',
                    models.BooleanField(
                        default=False,
                        help_text='If this is checked, only logged-in users will be able to view the page.',
                        verbose_name='registration required',
                    ),
                ),
                ('sites', models.ManyToManyField(to='sites.Site', verbose_name='sites')),
            ],
            options={
                'verbose_name': 'flat page',
                'verbose_name_plural': 'flat pages',
                'ordering': ['url'],
            },
        ),
    ]
