# Generated by Django 3.1.13 on 2021-09-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
