# Generated by Django 3.1.13 on 2021-09-02 08:23

import django.core.validators
from django.db import migrations, models

import core.fields
import core.fields.html_field


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0002_auto_20210902_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='content',
            field=core.fields.HTMLField(
                blank=True,
                paragraphed=None,
                processed=True,
                processor=core.fields.html_field.process,
                verbose_name='content',
            ),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='url',
            field=models.CharField(
                db_index=True,
                help_text='Example: “/about/contact/”. Requires leading and trailing slashes.',
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(regex='^\\/[-\\w/\\.\\/]+\\/$')
                ],
                verbose_name='URL',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='flatpage',
            unique_together={('url',)},
        ),
    ]
