# Generated by Django 3.1.13 on 2021-09-07 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0004_auto_20210906_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='path',
            field=models.CharField(
                db_index=True,
                help_text='Example: “/about/contact/”. Requires leading and trailing slashes.',
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(regex='^\\/[-\\w/\\.\\/]+\\/$')
                ],
                verbose_name='URL path',
            ),
        ),
    ]
