# Generated by Django 3.1.13 on 2021-09-10 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0005_auto_20210908_0421'),
        ('flatpages', '0006_auto_20210909_0111'),
    ]

    operations = []
