# Generated by Django 3.2.8 on 2021-10-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0006_auto_20210909_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='meta_description',
            field=models.TextField(
                default='This is a great page; take a look!',
                help_text="Content for the page's meta description, which is displayed underneath the page title on Google SERPs; should catch users' attention and increase and increase the click rate",
                verbose_name='meta description',
            ),
            preserve_default=False,
        ),
    ]
