# Generated by Django 3.2.7 on 2021-09-16 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0007_merge_20210910_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='path',
            field=models.CharField(
                db_index=True,
                help_text='Example: “/about/contact”. Requires a leading slash and no trailing slash.',
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(regex='^\\/[-\\w/\\.\\/]+[^\\/]$')
                ],
                verbose_name='URL path',
            ),
        ),
    ]
