# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: delivery
on:
  push:
    branches: [main]
    paths-ignore:
    - .gitignore
    - .github/**
    - '!.github/workflows/delivery.yml'
    - .idea/**
    - .vscode/**
    - '**.md'
    - '**.rst'
    - '**.txt'
    - tests.py
    - setup.sh
    - config/hooks/**
    - frontend/package*.json

env:
  ADMINS: ${{ secrets.ADMINS }}
  ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
  AUTH_DISCORD_CLIENT_ID: ${{ secrets.SOCIAL_AUTH_DISCORD_CLIENT_ID }}
  AUTH_DISCORD_KEY: ${{ secrets.SOCIAL_AUTH_DISCORD_KEY }}
  AUTH_DISCORD_SECRET: ${{ secrets.SOCIAL_AUTH_DISCORD_SECRET }}
  AUTH_FACEBOOK_KEY: ${{ secrets.SOCIAL_AUTH_FACEBOOK_KEY }}
  AUTH_FACEBOOK_SECRET: ${{ secrets.SOCIAL_AUTH_FACEBOOK_SECRET }}
  AUTH_GITHUB_CLIENT_ID: ${{ secrets.SOCIAL_AUTH_GITHUB_CLIENT_ID }}
  AUTH_GITHUB_SECRET: ${{ secrets.SOCIAL_AUTH_GITHUB_SECRET }}
  AUTH_GOOGLE_CLIENT_ID: ${{ secrets.SOCIAL_AUTH_GOOGLE_CLIENT_ID }}
  AUTH_GOOGLE_SECRET: ${{ secrets.SOCIAL_AUTH_GOOGLE_SECRET }}
  AUTH_TWITTER_KEY: ${{ secrets.SOCIAL_AUTH_TWITTER_KEY }}
  AUTH_TWITTER_SECRET: ${{ secrets.SOCIAL_AUTH_TWITTER_SECRET }}
  BRAINTREE_MERCHANT_ID: ${{ secrets.BRAINTREE_MERCHANT_ID }}
  BRAINTREE_PUBLIC_KEY: ${{ secrets.BRAINTREE_PUBLIC_KEY }}
  BRAINTREE_PRIVATE_KEY: ${{ secrets.BRAINTREE_PRIVATE_KEY }}
  CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
  CLOUDFLARE_PASSWORD: ${{ secrets.CLOUDFLARE_PASSWORD }}
  CONTENT_MANAGER_EMAIL: ${{ secrets.CONTENT_MANAGER_EMAIL }}
  CONTENT_MANAGER_PAT: ${{ secrets.CONTENT_MANAGER_PAT }}
  DJANGO_PORT: 8002
  ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
  ENVIRONMENT: prod
  FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  POSTGRES_DB: modularhistory
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  RCLONE_GDRIVE_SA_CREDENTIALS: ${{ secrets.RCLONE_GDRIVE_SA_CREDENTIALS }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  SENTRY_BACKEND_DSN: ${{ secrets.SENTRY_BACKEND_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_FRONTEND_DSN: ${{ secrets.SENTRY_FRONTEND_DSN }}
  SHA: ${{ github.sha }}
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  generate-dotenv:
    name: Generate .env file
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate .env file
      uses: iacobfred/generate-dotenv@v0.3.0
      with:
        template-paths: |
          .config/_.env
          .config/_.env.prod
  continue:
    name: Approve workflow continuation
    needs: generate-dotenv
    runs-on: ubuntu-latest
    permissions:
      actions: write
      deployments: write
      packages: write
    steps:
    - name: Wait for pending deployments
      run: sleep 15s
      shell: bash
    - name: Approve pending deployments
      id: approve-pending-deployments
      shell: bash
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.ACTIONS_PAT }}" \
        https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/pending_deployments \
        -d '{"environment_ids":[98022716],"state":"approved","comment":"Go!"}'
  build:
    name: Build Docker image (${{ matrix.image }})
    needs: generate-dotenv
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        image: [backend, frontend]
    steps:
    - name: Check out main branch
      uses: actions/checkout@v3
    - name: Generate .env file
      uses: iacobfred/generate-dotenv@v0.3.0
      with:
        template-paths: |
          .config/_.env
          .config/_.env.prod
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image
      id: build-image
      # https://github.com/docker/build-push-action
      uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./${{ matrix.image }}/Dockerfile.${{ matrix.image }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        secret-files: ENV_FILE=./.env
        tags: ghcr.io/modularhistory/${{ matrix.image }}:${{ github.sha }},ghcr.io/modularhistory/${{ matrix.image }}:latest
    - name: Build image without cache
      if: failure()
      uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./${{ matrix.image }}/Dockerfile.${{ matrix.image }}
        load: false
        push: true
        no-cache: true
        secret-files: ENV_FILE=./.env
        tags: ghcr.io/modularhistory/${{ matrix.image }}:${{ github.sha }},ghcr.io/modularhistory/${{ matrix.image }}:latest
  deploy:
    name: Deploy
    needs: build
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Check out main branch
      uses: actions/checkout@v3
    - name: Generate .env file
      uses: iacobfred/generate-dotenv@v0.3.0
      with:
        template-paths: |
          .config/_.env
          .config/_.env.prod
    - name: Deploy to server
      uses: iacobfred/deploy-docker-ssh@v0.3.1
      with:
        host: ${{ secrets.DOMAIN }}
        user: jacob
        target: /var/www/${{ secrets.DOMAIN }}
        files: '.env docker-compose.yml docker-compose.prod.yml .config'
        ssh-port: ${{ secrets.SSH_PORT }}
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          mv docker-compose.prod.yml docker-compose.override.yml && 
          set -a && source .env && set +a && 
          SHA=${{ github.sha }} GHCR_PASSWORD=${{ secrets.GITHUB_TOKEN }} bash .config/scripts/deploy.sh
    # - name: Create Sentry release
    #   uses: getsentry/action-release@v1.2.0
    #   env:
    #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    #     SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
    #     SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
    #   with:
    #     environment: prod