# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: integration

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  schedule:
    - cron: '0 9 * * *'

env:
  IMAGE_PREFIX: ghcr.io/modularhistory/
  SHA: ${{ github.sha }}
  ADMINS: ${{ secrets.ADMINS }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SOCIAL_AUTH_TWITTER_KEY: ${{ secrets.SOCIAL_AUTH_TWITTER_KEY }}
  SOCIAL_AUTH_TWITTER_SECRET: ${{ secrets.SOCIAL_AUTH_TWITTER_SECRET }}
  SOCIAL_AUTH_FACEBOOK_KEY: ${{ secrets.SOCIAL_AUTH_FACEBOOK_KEY }}
  SOCIAL_AUTH_FACEBOOK_SECRET: ${{ secrets.SOCIAL_AUTH_FACEBOOK_SECRET }}
  SOCIAL_AUTH_GITHUB_KEY: ${{ secrets.SOCIAL_AUTH_GITHUB_KEY }}
  SOCIAL_AUTH_GITHUB_SECRET: ${{ secrets.SOCIAL_AUTH_GITHUB_SECRET }}
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
  ALPHA_VANTAGE_ACCESS_KEY: ${{ secrets.ALPHA_VANTAGE_ACCESS_KEY }}
  IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
  IMGUR_CLIENT_SECRET: ${IMGUR_CLIENT_SECRET}
  X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }}
  MEGA_USERNAME: ${{ secrets.MEGA_USERNAME }}
  MEGA_PASSWORD: ${{ secrets.MEGA_PASSWORD }}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [
          #macos-latest,  # TODO
          ubuntu-latest
        ]
        python-version: [ 3.7 ]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      POSTGRES_HOST: localhost
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    steps:
    - uses: ./.github/actions/setup
      with:
        os: ${{ runner.os }}
        python-version: ${{ matrix.python-version }}
    - name: Check the console scripts interface
      run: |
        poetry run seleniumbase
        poetry run sbase
    - name: Install chromedriver and geckodriver (Firefox Webdriver)
      run: |
        poetry run seleniumbase install chromedriver
        poetry run seleniumbase install geckodriver
    - name: Make sure pytest is working
      run: |
        echo "def test_pytest(): pass" > nothing.py
        poetry run pytest nothing.py
    - name: Run tests
      if: ${{ success() }}
      run: poetry run invoke test

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.7 ]
    env:
      POSTGRES_HOST: postgres
      POSTGRES_DB: modularhistory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
    - uses: ./.github/actions/setup
    - name: Inject environment vars
      run: |
        envsubst < config/env.yaml > env.yaml.tmp && mv env.yaml.tmp config/env.yaml
        while read assign; do echo "$assign"; done < <(sed -nr '/env_variables:/,$ s/  ([A-Z_]+): (.*)/\1=\2/ p' config/env.yaml) > .env
    - name: Build Docker image
      run: poetry run invoke build --github-actor $GITHUB_ACTOR --access-token $CR_PAT --sha $SHA
    - name: Run Snyk to check Docker image for vulnerabilities
      # Snyk can be used to break the build when it detects vulnerabilities.
      # In this case, we want to upload the issues to GitHub Code Scanning.
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
        args: --file=Dockerfile.django
  
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'python' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more: https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main
    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  OSSAR-Scan:
    name: OSSAR Scan
    # OSSAR runs on windows-latest.
    # ubuntu-latest and macos-latest support coming soon.
    runs-on: windows-latest
    steps:
    # Checkout your code repository to scan
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
    # Run open source static analysis tools
    - name: Run OSSAR
      uses: github/ossar-action@v1
      id: ossar
    # Upload results to the Security tab
    - name: Upload OSSAR results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}
