# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - '.github/**'
      - '!.github/integration.yml'
      - '.idea/**'
      - '.vscode/**'
      - '**.md'
      - '**.rst'
      - 'config/hooks/**'
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      jobs:
        description: Comma-separated list of names of jobs to trigger
        required: false
        default: 'setup-script,build,pytest,e2e,test-deploy'

env:
  ADMINS: ${{ secrets.ADMINS }}
  ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
  ALPHA_VANTAGE_ACCESS_KEY: ${{ secrets.ALPHA_VANTAGE_ACCESS_KEY }}
  BRAINTREE_MERCHANT_ID: ${{ secrets.BRAINTREE_MERCHANT_ID }}
  BRAINTREE_PUBLIC_KEY: ${{ secrets.BRAINTREE_PUBLIC_KEY }}
  BRAINTREE_PRIVATE_KEY: ${{ secrets.BRAINTREE_PRIVATE_KEY }}
  CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
  CLOUDFLARE_PASSWORD: ${{ secrets.CLOUDFLARE_PASSWORD }}
  CONTENT_MANAGER_EMAIL: ${{ secrets.CONTENT_MANAGER_EMAIL }}
  CONTENT_MANAGER_PAT: ${{ secrets.CONTENT_MANAGER_PAT }}
  ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
  FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
  IMGUR_CLIENT_SECRET: ${IMGUR_CLIENT_SECRET}
  POSTGRES_HOST: postgres
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  RCLONE_GDRIVE_SA_CREDENTIALS: ${{ secrets.RCLONE_GDRIVE_SA_CREDENTIALS }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_FRONTEND_DSN: ${{ secrets.SENTRY_FRONTEND_DSN }}
  SHA: ${{ github.sha }}
  SOCIAL_AUTH_DISCORD_CLIENT_ID: ${{ secrets.SOCIAL_AUTH_DISCORD_CLIENT_ID }}
  SOCIAL_AUTH_DISCORD_KEY: ${{ secrets.SOCIAL_AUTH_DISCORD_KEY }}
  SOCIAL_AUTH_DISCORD_SECRET: ${{ secrets.SOCIAL_AUTH_DISCORD_SECRET }}
  SOCIAL_AUTH_FACEBOOK_KEY: ${{ secrets.SOCIAL_AUTH_FACEBOOK_KEY }}
  SOCIAL_AUTH_FACEBOOK_SECRET: ${{ secrets.SOCIAL_AUTH_FACEBOOK_SECRET }}
  SOCIAL_AUTH_GITHUB_CLIENT_ID: ${{ secrets.SOCIAL_AUTH_GITHUB_CLIENT_ID }}
  SOCIAL_AUTH_GITHUB_SECRET: ${{ secrets.SOCIAL_AUTH_GITHUB_SECRET }}
  SOCIAL_AUTH_GOOGLE_CLIENT_ID: ${{ secrets.SOCIAL_AUTH_GOOGLE_CLIENT_ID }}
  SOCIAL_AUTH_GOOGLE_SECRET: ${{ secrets.SOCIAL_AUTH_GOOGLE_SECRET }}
  SOCIAL_AUTH_TWITTER_KEY: ${{ secrets.SOCIAL_AUTH_TWITTER_KEY }}
  SOCIAL_AUTH_TWITTER_SECRET: ${{ secrets.SOCIAL_AUTH_TWITTER_SECRET }}
  X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }} 

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      added-files: ${{ steps.changed-files.outputs.added_files }}
      deleted-files: ${{ steps.changed-files.outputs.deleted_files }}
      modified-files: ${{ steps.changed-files.outputs.modified_files }}
      all-changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changed-files
      # https://github.com/tj-actions/changed-files
      uses: tj-actions/changed-files@v11

  setup-script:
    name: Test setup script
    needs: changed-files
    if: ${{ contains(needs.changed-files.outputs.modified-files, 'setup.sh') }}
    strategy:
      matrix:
        # OS options: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
        # NOTE: Services (running in Docker containers) only work on ubuntu.
        os: [ macos-latest, ubuntu-latest ]
        python-version: [ 3.9 ]
    runs-on: ${{ matrix.os }}
    environment: dev
    env:
      TESTING: true
    steps:
    - includes: ./.github/actions/setup
      with:
        os: ${{ matrix.os }}
        python-version: ${{ matrix.python-version }}
        environment: dev
    - name: Run setup script
      run: bash setup.sh
      shell: bash

  build:
    name: Build image
    needs: changed-files
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        image: [ django, next ]
    environment: test
    steps:
    - includes: ./.github/actions/setup
      with:
        environment: test
    - includes: ./.github/actions/build
      with:
        image: ${{ matrix.image }}
        tags: ghcr.io/modularhistory/${{ matrix.image }}:${{ github.sha }}
        push: true

  pytest:
    name: Run backend integration tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [ 3.9 ]
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started.
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    environment: test
    env:
      TESTING: true
    steps:
    - includes: ./.github/actions/setup
      with:
        os: ${{ runner.os }}
        python-version: ${{ matrix.python-version }}
        environment: test
    - name: Make sure pytest is working
      run: |
        echo "def test_pytest(): pass" > nothing.py
        poetry run pytest nothing.py
    - name: Run tests
      run: poetry run invoke test --no-docker

  jest:
    name: Run frontend unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm install --prefix frontend/
      - name: Run jest
        run: npm run test --prefix frontend/

  e2e:
    name: Run e2e tests
    needs: [build]
    environment: test
    env:
      ENVIRONMENT: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ chrome ]
        container: [ 1, 2, 3 ]
    steps:
    - includes: ./.github/actions/setup
      with:
        environment: test
    - includes: ./.github/actions/run
    - name: Run Cypress
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        # Pass the GitHub token to determine the unique run id necessary to re-run the checks.
        # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >
        docker compose -f docker-compose.yml -f docker-compose.test.yml run cypress
        --browser ${{ matrix.browser }} --group "${{ matrix.browser }}"
        --parallel --ci-build-id $GITHUB_TOKEN --record --key $CYPRESS_RECORD_KEY

  test-deploy:
    name: Test deploy
    needs: [changed-files, build]
    if: ${{ contains(needs.changed-files.outputs.modified-files, 'deploy.sh') || (github.event_name == 'workflow_dispatch' && contains(github.event.inputs.jobs, 'deploy')) }}
    runs-on: ubuntu-latest
    environment: test
    steps:
    - includes: ./.github/actions/setup
      with:
        environment: test
    - includes: ./.github/actions/run
    - name: Run deploy script
      run: bash .config/scripts/deploy.sh
    - name: Run deploy script x2
      run: bash .config/scripts/deploy.sh

  check-types:
    name: Check types
    needs: changed-files
    if: ${{ contains(needs.changed-files.outputs.modified-files, 'py') }}
    runs-on: ubuntu-latest
    environment: test
    strategy:
      max-parallel: 3
      matrix:
        executable: [ mypy, pytype ]
        python-version: [ 3.9 ]
    continue-on-error: ${{ matrix.executable == 'mypy' }}
    steps:
    - 
      includes: ./.github/actions/setup
      with:
        python-version: ${{ matrix.python-version }}
        environment: test
    - 
      name: Cache type stubs
      id: cache-stubs
      uses: actions/cache@v2
      with:
        path: .cache/${{ matrix.executable }}
        key: ${{ matrix.python-version }}-${{ matrix.executable }}-types
    - 
      name: Determine args
      id: args
      run: |
        if [ ${{ matrix.executable }} = mypy ]; then args="--config-file=./setup.cfg .";
        elif [ ${{ matrix.executable }} = pytype ]; then args="--config=./setup.cfg"; fi;
        echo "::set-output name=args::$args"
    -
      name: Run static type checker
      run: poetry run ${{ matrix.executable }} ${{ steps.args.outputs.args }}

  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    environment: test
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'python' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more: https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed
    # Don't cancel other jobs if CodeQL analysis fails.
    continue-on-error: true
    steps:
    - includes: ./.github/actions/setup
      with:
        environment: test
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        setup-python-dependencies: false
    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
